### ISSUE TITLE
pm2 commands not works

### ISSUE THREAD

**Issue by araczkowski** [tsl0922/ttyd#1001]
**Describe the bug**
pm2 commands not works, ends Aborted

**To Reproduce**
1. run ttyd in pm2 via comand
```
pm2 start ttyd -- -p 8080 bash
```
2. Go to ttyd in browser <ip>:8080
3. run any pm2 command for example ``pm2 status``
4. the output is Aborted
![image](https://user-images.githubusercontent.com/1263968/195563690-f529ed7b-84d5-4011-bc2b-e891318a5467.png)

**Expected behavior**
pm2 commands should works
![image](https://user-images.githubusercontent.com/1263968/195564207-a31423b9-f703-43d8-a141-a04cf6e8f9c7.png)

**Screenshots**

**Environment:**
 - OS: Android Termux
 - Browser: Any
 
**Additional context**
when the ttyd is runung from bash via command ``ttyd -p 8080 bash`` all works as expected, the ``Aborted`` problem is only when ttyd is runing in pm2

**Comment by tsl0922** [comment]
Can not reproduce. you may want to ask pm2 why, since it crashes.
