### ISSUE TITLE
Any way of knowing if ttyd is running a process?

### ISSUE THREAD

**Issue by abhijit-hota** [tsl0922/ttyd#1009]
I'd like to check if `ttyd` is currently "busy" or "free" to take any commands.

**Comment by tsl0922** [comment]
I think you are talking about process insides a shell?

No. ttyd is a tty io forwarder, you can't konw if a process is exited with the input/output data.

the only way to know if a process is exited is to [wait](https://man7.org/linux/man-pages/man2/wait.2.html) it, this is done by the shell.

**Comment by abhijit-hota** [comment]
Thanks for the response!

> I think you are talking about process insides a shell?

Yep.

> the only way to know if a process is exited is to [wait](https://man7.org/linux/man-pages/man2/wait.2.html) it

Got it. Thanks for the pointer. 

If I'm running `ttyd` via a browser automation tool and want to get the `pid` of a process that I executed inside `ttyd`, how do you suggest I go about it?

**Comment by tsl0922** [comment]
you can use `$!` to get the last command's pid in a shell sessoin, otherwise no direct way.
