### ISSUE TITLE
theme selection color option not changing value

### ISSUE THREAD

**Issue by toddwint** [tsl0922/ttyd#1010]
Updated from 1.7.1 to 1.7.2. (ttyd version 1.7.2-020e2f3) x86-64

Selection color was working in 1.7.1. I cannot get it to work in 1.7.2

My option is
```
-t 'theme={"foreground":"black","background":"white", "selection":"red"}'
```

I've tried on two different computers and Chrome and Firefox. 

The background, foreground, cursor, cursorAccent all work. Just not the selection for me.

**Comment by dmartin** [comment]
I think this is a side effect of the switch to xterm.js 5.0 (that option is [now called `selectionBackground`](https://github.com/xtermjs/xterm.js/releases/tag/5.0.0#:~:text=ITheme.selection%20has%20been%20renamed%20to%20selectionBackground%20for%20consistency%20(%233964)%20via%20%40Tyriar))

**Comment by toddwint** [comment]
Looks like that did the trick! Thank you! I get to keep my colors and theme. :)

I updated my code and notes.

```
# selection changed to selectionBackground in 1.7.2
# `-t 'theme={"foreground":"black","background":"white", "selection":"red"}'` # 1.7.1
# `-t 'theme={"foreground":"black","background":"white", "selectionBackground":"red"}'` # 1.7.2
```
