### ISSUE TITLE
Feature request: Copy to clipboard on select

### ISSUE THREAD

**Issue by summershrimp** [tsl0922/ttyd#102]
ATT. Same behavior as iTerm and mintty.

**Comment by tsl0922** [comment]
I'm not sure if there's an api can do this, It's better to implement this feature in the upstream project ([xterm.js](https://github.com/xtermjs/xterm.js)).

**Comment by tsl0922** [comment]
Added support on master (11c1e1bc79f8405f91009e7ab6968bbcd8bef578).

**Comment by mritzmann** [comment]
As a user, can I disable this feature?
