### ISSUE TITLE
[Q] invoke a system script via url arg

### ISSUE THREAD

**Issue by eadmaster** [tsl0922/ttyd#1031]
I'd like to execute a system command with curl like this, is it possible?
````
curl 'http://myopenwrt.local:7681/?arg=poweroff'
curl 'http://myopenwrt.local:7681/?arg=/sbin/poweroff'
````

EDIT: my config:
````
# cat /etc/config/ttyd

config ttyd
        option command '/usr/libexec/login.sh'
        option url_arg '1'
````

**Comment by tsl0922** [comment]
yes. use a custom command, check command line argument from url arg, then run it.

**Comment by eadmaster** [comment]
i've tried with these curl commands, but it is not working:
````
curl 'http://myopenwrt.local:7681/?arg=poweroff'
curl 'http://myopenwrt.local:7681/?arg=/sbin/poweroff'
````

**Comment by tsl0922** [comment]
url-arg will not be invoked by ttyd directly, you need to invoke it yourself (in start command, url-arg will be passed to it)

**Comment by eadmaster** [comment]
i don't get it, can you post an example?

**Comment by tsl0922** [comment]
```sh
#!/bin/sh

ARG="$1"
if [ -n "$ARG" ]; then $ARG; fi

/usr/libexec/login.sh
```
use the above script as ttyd's start command.

**Comment by warmhug** [comment]
> url-arg will not be invoked by ttyd directly, you need to invoke it yourself (in start command, url-arg will be passed to it)

@tsl0922 Why not support direct invoke by ttyd? Sometimes it is inconvenient to have an extra script.
