### ISSUE TITLE
Homebrew still installs 1.7.1

### ISSUE THREAD

**Issue by tomtom215** [tsl0922/ttyd#1032]
**Is your feature request related to a problem? Please describe.**

Homebrew still installs 1.7.1
https://formulae.brew.sh/formula/ttyd

**Describe the solution you'd like**

Homebrew install would install the latest release (1.7.2)

**Comment by adriens** [comment]
Same here : 

![image](https://user-images.githubusercontent.com/5235127/204898935-390c728f-55e5-462c-af56-de7b33f00080.png)

**Comment by maaslalani** [comment]
I have made a PR to update to 1.7.2 but there are some blockers on it:

* https://github.com/Homebrew/homebrew-core/pull/116321

**Comment by adriens** [comment]
:pray:
