### ISSUE TITLE
Example systemd usage does not work.

### ISSUE THREAD

**Issue by Oman395** [tsl0922/ttyd#1035]
**Describe the bug**
The example given for systemd doesn't work (at least on my system) because the login command appears not to work as expected

**To Reproduce**
Run "ttyd login" as sudo

**Expected behavior**
When you go to the page, it greets you with a login page

**Environment:**
Arch 6.0.8-arch1-1
Linode server

**Additional context**
I also tried using the -u flag, which didn't work (running whoami returned root, although that might be a seperate issue). My workaround is just creating a user named "ttyd", and setting the command to "sudo -u ttyd su -". I also had to change the sudo configuration, specifically uncommenting these two lines:
```
Defaults targetpw  # Ask for the password of the target user
ALL ALL=(ALL:ALL) ALL  # WARNING: only use this together with 'Defaults targetpw'
```
And here's my systemd unit, if anyone needs it (with reference to SSL removed):
```
[Unit]
Description=TTYD
After=syslog.target
After=network.target

[Service]
Description=TTYD Service, for remote SSH access
ExecStart=/bin/ttyd sudo -u ttyd su -
Type=simple
Restart=always
User=root
Group=root

[Install]
WantedBy=multi-user.target
```
I could probably also change the configuration of the user to allow it to do everything ttyd needs to do and make ttyd just run "su -", but it's easier to do it my way.

E: Fixed example

**Comment by tsl0922** [comment]
Hi, 

It's a public wiki, you can edit it yourself to help other people.
