### ISSUE TITLE
Cannot load page in IE-11

### ISSUE THREAD

**Issue by briandant** [tsl0922/ttyd#104]
I see that you are in theory supporting [ie-11 with some polyfills](https://github.com/tsl0922/ttyd/blob/master/html/js/app.js#L3), but I cannot get the app to respond when using IE-11. I get a `SCRIPT5022: SecurityError` pointing to `socket.js (18,3)`. ([Screenshot of the error](https://www.dropbox.com/s/s2xu5w3bvmpfybg/Screenshot%202018-06-08%2000.15.22.png?dl=0).)

Do you officially support IE-11?  

Thanks for building and sharing this great app!

**Comment by tsl0922** [comment]
Yes, ttyd supports IE11.

I've tested it inside a win7 vm with IE11 but can't reproduce your problem. It looks like your IE11 didn't load the index page fully, since the css style is broken.

**Comment by briandant** [comment]
Thanks so much! I’ll dig into this a bit further. Kudos for supporting 
IE-11 :)

**Comment by tsl0922** [comment]
Close due to not reproducible.
