### ISSUE TITLE
Add yubikey authentication method 

### ISSUE THREAD

**Issue by QuentinBens** [tsl0922/ttyd#1044]
**Is your feature request related to a problem? Please describe.**
The security is super important for me, and I'm wondering if it's possible to add a new authentication method like yubikey

**Describe the solution you'd like**
Add another authentication method: yubikey

**Describe alternatives you've considered**
Not everyone own a Yubikey, so I see two solutions between many of them: **FIDO U2F key**.  or we could imagine a 2 factors authentication, username/password and **two-factor authentication codes provider like Authenticator** (google or else). 

**Additional context**
The main goal is two add another authentication method, with an increased level of security compare with http basis authentication

**Comment by tsl0922** [comment]
This not what should be done by ttyd. you can use some existing tools that already support yubikey auth, for example: ssh
