### ISSUE TITLE
Mouse does not work in 1.7.2

### ISSUE THREAD

**Issue by zhizheng1** [tsl0922/ttyd#1052]
**Describe the bug**
Mouse reporting does not work in latest version. With a mouse enabled vim (verified mouse working with Terminal.app), ttyd does not have mouse function at all, in both Safari and Chrome.

**To Reproduce**
Enabled mouse report in vim
Verified mouse working in vim in Terminal.app
Mouse does not work at all (no effect) with ttyd sessions

**Expected behavior**
Mouse reporting should work.

**Environment:**
macOS latest, Safari and Chrome latest

**Additional context**

**Comment by zhizheng1** [comment]
I should further mention that mouse in vim in a ttyd session has no effect at all, including not being able to select and copy as in normal command line.

**Comment by tsl0922** [comment]
try the latest main branch.

**Comment by zhizheng1** [comment]
> try the latest main branch.

It works, thanks. Closing the issue.
