### ISSUE TITLE
Is there any reason why you are using mbedtls on windows?

### ISSUE THREAD

**Issue by mikoto2000** [tsl0922/ttyd#1054]
I try to fix [the build failure on windows](https://github.com/tsl0922/ttyd/actions/runs/3791872454/jobs/6447615051).
Maybe this build fails to fix, want need to fix libwebsockets.

I try to disable LWS_WITH_MBEDTLS and build success.
Is there any reason why you are using mbedtls on windows?

```diff
$ git diff ./scripts/mingw-build.sh
diff --git a/scripts/mingw-build.sh b/scripts/mingw-build.sh
index 750d147..fe3e119 100644
--- a/scripts/mingw-build.sh
+++ b/scripts/mingw-build.sh
@@ -4,8 +4,6 @@ set -eo pipefail

 build_libwebsockets() {
   svn co https://github.com/msys2/MINGW-packages/trunk/mingw-w64-libwebsockets
-  sed -i 's/openssl/mbedtls/' mingw-w64-libwebsockets/PKGBUILD
-  sed -i '/-DCMAKE_INSTALL_PREFIX=${MINGW_PREFIX}/a \    -DLWS_WITH_MBEDTLS=ON \\' mingw-w64-libwebsockets/PKGBUILD
   sed -i '/-DCMAKE_INSTALL_PREFIX=${MINGW_PREFIX}/a \    -DLWS_WITH_LIBUV=ON \\' mingw-w64-libwebsockets/PKGBUILD
   pushd mingw-w64-libwebsockets
     makepkg-mingw --cleanbuild --syncdeps --force --noconfirm
```

**Comment by mikoto2000** [comment]
I try install mbedtls from https://mirror.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-mbedtls-2.28.0-1-any.pkg.tar.zst, build success with mbedtls.

**Comment by tsl0922** [comment]
to make the static linked binary smaller

**Comment by mikoto2000** [comment]
Thank you for your answer.
I built with each and confirmed that the mbedtls version is 1.4MB and the openssl version is 3.6MB.
It seems better to build with the mbedtls version.
