### ISSUE TITLE
ttyd should ask again for user:password when the browser window is closed.

### ISSUE THREAD

**Issue by ericxuo** [tsl0922/ttyd#1055]
Hi,

I've noticed that if I close my browser window or if I refresh it, ttyd does not ask again for my credentials. It does if I close my browser (Firefox) or if I change my htpasswd.
Is it possible to add this feature ?
I'm using Apache with the following : 

<IfModule mod_proxy_http.c>

    RewriteEngine On
    RewriteRule .* - [E=PROXY_USER:%{LA-U:REMOTE_USER},NS]
    RequestHeader set X-WEBAUTH-USER "%{PROXY_USER}e"
    ProxyRequests Off
    RequestHeader unset Authorization
    <Location /ttyd/>
	AuthType Basic
	AuthName ttyd
        AuthBasicProvider file
        AuthUserFile /etc/ttyd/ttyd_htpasswd
        Require valid-user
	Order allow,deny
	Allow from all
	ProxyPass unix:/tmp/ttyd.sock|http://192.168.0.14:7681/
	ProxyPassReverse unix:/tmp/ttyd.sock|http://192.168.0.14:7681/
    </Location>

    <Location /ttyd/ws>
	Order allow,deny
	Allow from all
	ProxyPass unix:/tmp/ttyd.sock|ws://192.168.0.14:7681/ws
	ProxyPassReverse unix:/tmp/ttyd.sock|ws://192.168.0.14:7681/ws
    </Location>
    
</IfModule>

I'm running systemd with the following : 
/mnt/Softs/bin/ttyd.x86_64 -i /tmp/ttyd.sock -H X-WEBAUTH-USER -w /home/ttyd tcsh

Regards.

Xuo.

**Comment by tsl0922** [comment]
basic auth cred is cached by browser session, it 's not what ttyd can control.
