### ISSUE TITLE
How to use the html directory ?

### ISSUE THREAD

**Issue by ericxuo** [tsl0922/ttyd#1056]
Hi,

Currently, I start ttyd with : 
ttyd tcsh
then I get logged into my shell account.
Is it possible to have an html frontend before accessing the shell window. It is maybe the goal of the html directory. I'm not sure of that => Could you add a secion in the Wiki that explains what is the goal of this html directory and how to use it ?

Regards.

Xuo.

**Comment by tsl0922** [comment]
see #181.

**Comment by ericxuo** [comment]
Hi,

This post (https://github.com/tsl0922/ttyd/issues/181) is just not understandable.

Xuo.
