### ISSUE TITLE
Problem with a jailed user (jailshell)

### ISSUE THREAD

**Issue by jaimbh** [tsl0922/ttyd#1060]
I have jailed a user using jailshell app that I installed from github. Link:- [https://github.com/pymumu/jail-shell](url)
A jailed user has limited access to certain directories and files.

When I login to ttyd terminal as that jailed user, I am able to see directories of other users in /home and also enter them using cd command which is wrong. (means it is working like normal shell rather than jailed shell)
I am able to see all dirs and files that were restricted for the jailed user  which is wrong.

However when I login that user using ssh, console or even doing su from ttyd terminal as root, I see the proper jailed restricted environment. I face this problem only when I login to ttyd terminal as user.

![image](https://user-images.githubusercontent.com/115988572/211851480-eb65468e-83f0-4776-b6fa-a2da55334697.png)

![image](https://user-images.githubusercontent.com/115988572/211851538-bfc92171-4bb1-49d1-898f-5e94bbda8310.png)

I open ttyd terminal from a php script where I call:
exec(SOMEPATH/bin/ttyd --once -u UID_OF_USER -g GID_OF_USER -P 10 -b /tty/ -i dir/username sock /bin/bash);

Adding su with this command like mentioned below gets the job done but it asks for password in the web terminal which I dont want.
exec(SOMEPATH/bin/ttyd --once -u UID_OF_USER -g GID_OF_USER -P 10 -b /tty/ -i dir/username sock su username);

After using su I am able to login as the jailed user but I have to enter password in the terminal to login.
I am looking for a solution where the user gets logged in without password.

**Comment by tsl0922** [comment]
This has nothing to do with ttyd, the auth is not handled by ttyd, but the program you let ttyd to run.
