### ISSUE TITLE
No way to listen on a single address

### ISSUE THREAD

**Issue by AddisonG** [tsl0922/ttyd#1062]
TTYD doesn't support listening to only a single address (or address range).

I would expect that an `--address` option would be possible, so that ttyd only listens to connections from a single address, but this doesn't seem to be possible.

For example, if I wanted to make sure that only connections from `192.168.0.1` were accepted, I would expect to see the following in `netstat`:

```
netstat -lp
Proto Recv-Q Send-Q Local Address     Foreign Address   State   PID/Program name    
tcp        0      0 192.168.0.1:7681  0.0.0.0:*         LISTEN  987654/ttyd         
                    ^^^^^^^^^^^
```

I don't know if this is possible, but it would be a welcome security feature.

--

EDIT - It looks like libwebsockets allows this, through the use of `vhost_name`, in the info/context.

```
VHOST: name of vhost, must match external DNS name used to access the site, like "warmcat.com" as it's used to match Host: header and / or SNI name for SSL.
```

**Comment by tsl0922** [comment]
```
ttyd -i 127.0.0.1
```
