### ISSUE TITLE
Terminal hangs on running npm

### ISSUE THREAD

**Issue by evil-shrike** [tsl0922/ttyd#1063]
I have a Dockerfile with ttyd. 

```Dockerfile
FROM google/cloud-sdk:alpine
RUN apk add --update nodejs npm
RUN apk update &&  apk add --no-cache bash ttyd tzdata sudo nano curl
CMD ["ttyd", "bash"] 
EXPOSE 7681/tcp
```
I tested with local Docker, it works fine. Now I want run an app on Google Cloud Run.

When I run on Cloud Run the terminal starts well and bash works, but when I execute `npm -v` (or any other npm command) terminal hangs (not returning to the prompt):
<img width="212" alt="image" src="https://user-images.githubusercontent.com/1203230/213131345-bbc19e12-af0a-430c-bc51-9f656e608d56.png">

If I open another session and execute `ps` I can see that 'npm' process. 
I can't see anything in logs.

What can be wrong? What would you recommend?
Thanks.

**Comment by evil-shrike** [comment]
<img width="293" alt="image" src="https://user-images.githubusercontent.com/1203230/213134140-f112a9e3-fbde-4757-8401-e86d45e1ceea.png">

**Comment by evil-shrike** [comment]
this is logs:
![image](https://user-images.githubusercontent.com/1203230/215983448-e05ec7f5-4524-4b6a-b3fe-6e7ef2e074f1.png)
I pressed Ctrl-C after 'npm -v' hung (didn't return control to shell), but nothing happened. after a while (a timeout) the terminal shows 'connection closed' and the page reloads.
Btw all npm commands I put into my Docker file work fine. So it doesn't look as a problem with npm itself (might be wrong).

**Comment by evil-shrike** [comment]
I've manage to narrow down the problem, it's not with npm, it's with running child processes.
This a reproducing example:
```
const cp = require('child_process');
console.log('executing a command');
let output = cp.execSync('which gcloud').toString().trim();
console.log(output)
```

run it `node test.js` and it'll freeze at the first 'execSync' line.

**Comment by tsl0922** [comment]
> Interesting enough that spawnSync works

Maybe you should check the difference between them. It should not be related to ttyd.

**Comment by evil-shrike** [comment]
Actually it's not just spawn and spawnSync, it hangs in other cases as well.

But your reasoning for closing is quite weird:   
>It should not be related to ttyd.

I provided reproduction - Dockerfile in the first comment, you can run `npm -v` and the terminal hangs. I'm afraid it's not working as expected even if 'it should be not related'.

**Comment by tsl0922** [comment]
I can't reproduce it. ttyd just forwards input/output of you program, it does not change anything.

If it "hangs", that means your program do not write anything to stdout/stderr, check if the output is buffered in your program.

**Comment by evil-shrike** [comment]
well, I'm sorry, there's an important clarification - it 'hangs' only when running on Cloud Run.
The same Dockerfile, which I provided, works well with local Docker, but as soon as I deploy it as a docker container to Cloud Run via Cloud Run Button (https://github.com/GoogleCloudPlatform/cloud-run-button) `npm -v` hangs.
