### ISSUE TITLE
Sixel rendering is no longer working in latest version (1.7.3)

### ISSUE THREAD

**Issue by SubhashBose** [tsl0922/ttyd#1065]
**Describe the bug**
In the latest version sixel (img2sixel) graphics rendering is no longer working. In the previous version, it was working fine.

**To Reproduce**
Locate a image file, .jpg etc
Use the command to render in terminal `img2sixel file.jpg`
No graphics is rendered

**Expected behavior**
To render the .jpg file in terminal

**Environment:**
 - OS: Ubuntu 22
 - Browser: Chrome

**Comment by tsl0922** [comment]
https://github.com/jerch/xterm-addon-image/issues/38

**Comment by jerch** [comment]
Eww, this should be fixed with v0.3.1 already, which ttyd uses. So it does not work?

**Comment by SubhashBose** [comment]
Ok, I didn't know that `-t enableSixel=true` is required in this version. Until v1.7.2 this switch was not needed.

Now Sixel rendering works fine using this switch.

Thanks

**Comment by tsl0922** [comment]
Thanks, I've added a hint to the release note.
