### ISSUE TITLE
1.7.3 terminal display incorrectly

### ISSUE THREAD

**Issue by tianyuanhao** [tsl0922/ttyd#1067]
**Describe the bug**
When using `journalctl`, the bottom row shows a white background beyond the end of the line.

**To Reproduce**
1. Use `ttyd` 1.7.3
2. Enter `journalctl↵`

**Expected behavior**
```
lines█1-33▒
```

**Screenshots**
```
lines█1-33▒█████████████████████████████
```

**Environment**
- Browser: Chrome 103.0.5060.114

**Additional context**
xtermjs/xterm.js#4120

**Comment by tianyuanhao** [comment]
@tsl0922 This bug seems to have been introduced by `xterm` 5.1.0.

**Comment by tianyuanhao** [comment]
@Tyriar

**Comment by tsl0922** [comment]
updated to xterm 5.2.1 now
