### ISSUE TITLE
1.7.3 reconnection is not working

### ISSUE THREAD

**Issue by tianyuanhao** [tsl0922/ttyd#1068]
**Describe the bug**
`▒Reconnecting▒` does not disappear when the reconnection is successful.

**To Reproduce**
1. Start `ttyd login`
2. Kill the `login`
3. Press `↵` to reconnect

**Expected behavior**
The terminal is reset.
```
pc login:
```

**Screenshots**
```
pc login: pc login:


                ▒Reconnecting▒


```

**Environment**
- Browser: Chrome 103.0.5060.114

**Additional context**
microsoft/vscode#172782

**Comment by tsl0922** [comment]
Waiting for xterm.js 5.2.0

**Comment by tsl0922** [comment]
updated to xterm 5.2.1 now
