### ISSUE TITLE
E: Ran out of header data space (oauth2_proxy implementation)

### ISSUE THREAD

**Issue by oli4vr** [tsl0922/ttyd#1077]
In an implementation we setting up with oauth2_proxy, we have a problem in some cases that the hard coded max header size of 20k is not enough.
Some users have a lot of groups + a large cookie size makes it difficult to fit everything in the 20k

It could help if the max header would be a lot larger or if it could be customized through a parameter.

For the users that have a "too large" header, we clearly get the following error :
E: Ran out of header data space

**Comment by tsl0922** [comment]
It's controled by the `lws_context_creation_info.max_http_header_data` param of libwebsockets, hardcoded to 20k.

I can accept a PR that adding a command line option for it, or wait for the next release, may do it myself.

**Comment by oli4vr** [comment]
A new version with an significant increase of the hardcoded value would help us out a lot.
I am trying it myself but I have some issue getting ttyd statically compiled with all the prereq libraries on SLES15SP4. (and I'm not going to bother you with that ;) )

I will add a PR for an optional parameter.
Thank you for your reply.

**Comment by oli4vr** [comment]
Ok I was finally able to build it correctly myself.

I was able to solve our problem by changing :

info.max_http_header_data = 20480;

into

info.max_http_header_data = 65535;

65535 is also the max value possible as the variable in the libwebsockets library is an unsigned short...

I hope this helps...

**Comment by oli4vr** [comment]
If you allow me to publish a branch I can create a PR for this.

**Comment by tsl0922** [comment]
#1088
