### ISSUE TITLE
Header based authentication

### ISSUE THREAD

**Issue by jkinred** [tsl0922/ttyd#108]
Do you have any advice for configuring authentication methods other than basic auth in ttyd?

The README says:
> and many other custom options

Our use case would be to leverage external authentication with JWT or OAuth 2:
* Via headers set by a reverse proxy
* Within ttyd itself.

Additionally, some form of authorisation (like checking one or more JWT claims).

We'd be happy to collaborate on implementing this.

**Comment by tsl0922** [comment]
Basically, you can do it but not in ttyd core.

I have an idea: ttyd invokes a script with request information and use the exit code of the script to check authentication, then you can write your own auth logic in the script.

**Comment by jkinred** [comment]
We like this solution a lot as it makes `ttyd` very flexible for many use cases.

Do you have any input on how you'd like to proceed? We will begin working on a PR.

**Comment by tsl0922** [comment]
Sorry for the later response, I'm a little busy this month.

### Option 1

expose all of the request headers and params via env. 

```
env HEADER_h1=value HEADER_h2=value PARAM_p1=value PARAM_p2=value ./script
```

### Option 2

use custom syntax to expose only needed info to the script.

```
./script %h1 %h2 #p1 #p2
```

**Comment by pre** [comment]
Ttyd invoking a custom script and passing selected HTTP Headers to it for authentication (and even authorization) would be useful.

**Comment by tsl0922** [comment]
https://github.com/tsl0922/ttyd/wiki/Auth-Proxy
