### ISSUE TITLE
'minimumContrastRatio' Client Parameter No Longer Working in Build 1.7.3-a8cae75

### ISSUE THREAD

**Issue by hazarjast** [tsl0922/ttyd#1083]
**Describe the bug**
Client option ('-t') 'minimumContrastRatio' setting is no longer respected in 1.7.3-a8cae75.

**To Reproduce**
1. Enable high-contrast theme with an accessibility best practice contrast ratio of 21:1 using the supported underlying xterm.js parameter 'minimumContrastRatio' as follows:
```
ttyd -p 8080 -i lo -t titleFixed="Window Title" -t fontSize=16 -t minimumContrastRatio=21 \
-t 'theme={"background": "#ffffff", "foreground": "#000000", "cursor": "#000000", "selection": "#000000"}' \
/opt/my/script.sh
```
2. Connect to ttyd session in latest Chrome or Edge browsers and select any terminal text.
3. Observe that the selection is not visible: white selection is shown on a white background making it impossible to see what text you are trying to select. Thus, it seems 'minimumContrastRatio' setting of 21:1 is not effective.
4. Revert back to ttyd version 1.7.1-45ef578 and select the same text which is now shown properly; black selection bar on selected black text turns the text white so you can see what you are selecting.

**Expected behavior**
When high contrast theming is in use (ex. white background, black foreground, white selection), 'minimumContrastRatio=21' should be respected by ttyd.

**Screenshots**
![image](https://user-images.githubusercontent.com/30390295/222178303-11b9fa4d-1e40-49b0-87d5-40c166dbb990.png)
![image](https://user-images.githubusercontent.com/30390295/222178364-1cb92816-490b-4eaf-a4bc-38e4e8961c1d.png)

**Environment:**
 - ttyd server: OS Ubuntu Server 22.04, client: Windows 10 21H2
 - Browser: Chrome 110.0.5481.177, MS Edge 110.0.1587.57

**Additional context**
Not sure if this was something broken between ttyd versions or broken in underlying xterm.js. If it is determined that nothing changed in ttyd with respect to 'minimumContrastRatio' client option, then I am happy to open a bug report with the underlying xterm.js devs. Thank you for your excellent software and continued support. You are greatly appreciated.

**Comment by tsl0922** [comment]
> Not sure if this was something broken between ttyd versions or broken in underlying xterm.js

You can check if it can be reproduced with xterm.js [demo](https://github.com/xtermjs/xterm.js/wiki/Contributing#running-the-demo)

**Comment by hazarjast** [comment]
Hello,
Thank you for your quick response and suggestion of testing the xterm.js demo. I should have RTFM or, more specifically, checked the xterm.js ITheme changes prior to opening this bug report for ttyd as the source of the problem was not related to ttyd *or* 'minimumContrastRatio' at all. The root cause was actually a change in the ITheme interface option, "selection". It seems the old, singular "selection" option has now itself been replaced and broken out into multiple options which offer more fine-grained control over text selection color:

![image](https://user-images.githubusercontent.com/30390295/222987373-5d35eaf6-3b21-4e39-a7e0-9eafcb9e363b.png)

After testing, I have found the following updated configuration to sufficiently replicate the behavior I required without having to use "minimumContrastRatio" at all:
```
ttyd -p 8080 -i lo -t titleFixed="Window Title" -t fontSize=16 \
-t 'theme={"background": "white", "foreground": "black", "cursor": "black", "selectionBackground": "black", "selectionForeground": "white"}' \
/opt/my/script.sh
```
Please accept my apologies for opening this bug report in error. I know too well the headache of users opening false bug reports and the undue frustration it can cause. In future I will do better about checking upstream changes in xterm.js before making any assumptions about ttyd.
