### ISSUE TITLE
Proxy TTYD using NodeJs

### ISSUE THREAD

**Issue by rahulmukati** [tsl0922/ttyd#1090]
Describe your problem or question here.
I am using NodeJS for my app, I want to proxy TTYD.

I used Axios to proxy /, /token URL. And everything seems to be fine until it requests websocket to /ws.
For the web socket, I wrote the below code:

```
// TTYD WS
exports.ttydWs = async (ws, req) => {
  try {

    const ttydWs = new websocket('ws://localhost:7681/ws')

    ttydWs.on('message', (ttydMessage) => {
      console.log('TTYD SENT A MESSAGE')
      ws.send(ttydMessage)
    })

    ttydWs.on('error', () => {
      ws.close()
    })

    ttydWs.on('close', () => {
      ws.close()
    })

    ws.on('message', (message) => {
      console.log('Client sent a msg')
      ttydWs.send(message)
    })

    ws.on('close', () => {
      ttydWs.close()
    })

  } catch (err) {
    ws.close()
  }
}
```

Now the issue is, I am receiving messages from TTYD frontend which it sends in starting, and I am forwarding the same message to TTYD websocket, but TTYD websocket is not responding back.

Any solution for this?

**Comment by rahulmukati** [comment]
@tsl0922 Any help?

**Comment by tsl0922** [comment]
It's not a ttyd issue, you may want to ask it on [stackoverflow](https://stackoverflow.com).

**Comment by Floyddotnet** [comment]
you missing the subprotocol `tty`

change

`const ttydWs = new websocket('ws://localhost:7681/ws')`

to

`const ttydWs  = new WebSocket(this.options.wsUrl, ['tty']);`

and it will work.
