### ISSUE TITLE
ttyd built from sources and deployed to Cloud Run started failing recently

### ISSUE THREAD

**Issue by evil-shrike** [tsl0922/ttyd#1095]
I have a couple of solutions that deploy ttyd to Google Cloud Run. They have been working fine till recently one that builds ttyd from sources has started failing.
By 'failing' I mean ttyd seems to start but Cloud's healthcheck says it's not running and as so terminates deployment.

In both cases the outputs in logs are the same:
```
[2023/05/01 09:23:36:3394] N: ttyd 1.7.3-e01e213 (libwebsockets 4.0.20)
2023-05-01 13:23:36.349 GST
[2023/05/01 09:23:36:3427] N: tty configuration:
2023-05-01 13:23:36.349 GST
[2023/05/01 09:23:36:3427] N: start command: bash -c ./main.sh
2023-05-01 13:23:36.349 GST
[2023/05/01 09:23:36:3427] N: close signal: SIGHUP (1)
2023-05-01 13:23:36.349 GST
[2023/05/01 09:23:36:3427] N: terminal type: xterm-256color
2023-05-01 13:23:36.349 GST
[2023/05/01 09:23:36:3427] N: allow url arg: true
2023-05-01 13:23:36.349 GST
[2023/05/01 09:23:36:3430] N: Using foreign event loop...
2023-05-01 13:23:36.349 GST
[2023/05/01 09:23:36:3434] N: Listening on port: 7681
```

but the one that fails has this in logs:
```
STARTUP TCP probe failed 1 time consecutively for container "myapp" on port 7681. The instance was not started.
```

Dockerfile for one that doesn't works (built from sources):
```
FROM google/cloud-sdk
# Install ttyd
RUN apt-get install -y build-essential cmake git libjson-c-dev libwebsockets-dev
RUN git clone https://github.com/tsl0922/ttyd.git
WORKDIR ./ttyd
RUN cmake . && make && make install

...
CMD ["ttyd", "--url-arg", "bash", "-c", "./main.sh"]
```

Dockerfile for one that works (alpine based and installs ttyd as a Linux package):
```
FROM google/cloud-sdk:alpine
RUN apk add --update nodejs npm
RUN apk update &&  apk add --no-cache bash ttyd tzdata sudo nano curl
EXPOSE 7681/tcp
WORKDIR /app

...
CMD ["ttyd", "--url-arg", "bash", "-c", "./main.sh"]
```

I'd suspect that it's smth wrong with GCloud's health-check but that fact that ttyd works when installed as a package makes me think that there might be some changes introduced recently that haven't incorporated into the package yet (so it continue to work).

Unfortunately I can't use alpine-based image due to issues with installing Python dependencies on it (it requires them to be built and that is extremely slowly).

The Google Cloud health-check works via tcp, http or grpc. I tried both tcp and http with no luck.

**Comment by tsl0922** [comment]
I have no idea, you may want to contact Google Cloud Support.
