### ISSUE TITLE
Unable to build the Windows version

### ISSUE THREAD

**Issue by brugnara** [tsl0922/ttyd#110]
Hi there.

First of all, thank you for this great tool. 

Sadly I am not able to build the Windows version. Following the guide provided, the build of both `json-c` and `libwebsocket` fails. I tried upgrading `json-c` to the latest version and it builds but after the build, the `ttyd` build fails saying json-p is missing (please note that the first check says `json-c` is built but the build itself fails). Also, upgrading the `libwebsocket` didn't helped.

As someone else stated, it would be useful providing the binaries into the release here on github. #101 

I hope you can fix this as this tool is great!
Many thanks.

**Comment by brugnara** [comment]
Here some more details:

## msys2 is updated/upgraded

```cmd
IEUser@IE8WIN7 MINGW32 ~/dev/ttyd/msys2
$ pacman -Su
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do

IEUser@IE8WIN7 MINGW32 ~/dev/ttyd/msys2
$ pacman -Syu
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do
```
## json-c compile error

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -Wall -Werror -Wno-error=deprecated-declarations -Wextra -Wwrite-strings -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -D_REENTRANT -march=i686 -mtune=generic -O2 -pipe -MT json_c_version.lo -MD -MP -MF .deps/json_c_version.Tpo -c json_c_version.c -o json_c_version.o >/dev/null 2>&1
json_object.c: In function 'json_object_get_int64':
json_object.c:554:5: error: this statement may fall through [-Werror=implicit-fallthrough=]
  if (json_parse_int64(jso->o.c_string.str, &cint) == 0) return cint;
     ^
json_object.c:555:3: note: here
   default:
   ^~~~~~~
mv -f .deps/json_c_version.Tpo .deps/json_c_version.Plo
```

## libwebsockets build error

The build starts but the msys2 freezes itself.

Best regards.

**Comment by tsl0922** [comment]
Fixed by 44272fa213c386ce7aa259f1d64809b6abaf4aab

**Comment by brugnara** [comment]
Thank you.

Same problem occurs, but we understood the problem here is Windows 7 386. Compiling with Windows 10 x64, everything worked as expected.

I also suggest you to add this line to the msys2 building instructions as are both required in order to build:

`pacman -S git binutils`

**Comment by brugnara** [comment]
In order to build on a 32 bit windows, a lib is required:

```
pacman -S mingw-w64-i686-cmake
```

**Comment by comicer424** [comment]
When i use MSYS2 has error
`Administrator@win7-sp1-0 MINGW32 ~/ttyd-master/msys2/ttyd
# makepkg --skipchecksums
==> 正在创建软件包：ttyd 1.5.2-1 (2019年11月 6日 19:11:36)
==> 正在检查运行时依赖关系...
==> 正在检查编译时依赖关系
==> 获取源代码...
  -> 找到 ttyd-1.5.2.tar.gz
==> 警告： 正在跳过校验源文件校验值。
==> 正在释放源码...
  -> 正在解压缩 ttyd-1.5.2.tar.gz，使用 bsdtar
==> 正在开始 prepare()...
==> 正在删除现存的 $pkgdir/ 目录...
==> 正在开始 build()...
-- Configuring done
-- Generating done
-- Build files have been written to: C:/msys32/home/Administrator/ttyd-master/msys2/ttyd/src/build-i686
[ 16%] Generating html.h from index.html
Scanning dependencies of target ttyd
[ 33%] Building C object CMakeFiles/ttyd.dir/src/server.c.obj
[ 50%] Building C object CMakeFiles/ttyd.dir/src/http.c.obj
[ 66%] Building C object CMakeFiles/ttyd.dir/src/protocol.c.obj
C:/msys32/home/Administrator/ttyd-master/msys2/ttyd/src/ttyd-1.5.2/src/protocol.c:8:10: fatal error: sys/ioctl.h: No such file or directory
    8 | #include <sys/ioctl.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/ttyd.dir/build.make:93：CMakeFiles/ttyd.dir/src/protocol.c.obj] 错误 1
make[2]: *** 正在等待未完成的任务....
In file included from C:/msys32/home/Administrator/ttyd-master/msys2/ttyd/src/ttyd-1.5.2/src/server.c:14:
C:/msys32/home/Administrator/ttyd-master/msys2/ttyd/src/ttyd-1.5.2/src/server.h:3:10: fatal error: sys/ioctl.h: No such file or directory
    3 | #include <sys/ioctl.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/ttyd.dir/build.make:67：CMakeFiles/ttyd.dir/src/server.c.obj] 错误 1
In file included from C:/msys32/home/Administrator/ttyd-master/msys2/ttyd/src/ttyd-1.5.2/src/http.c:4:
C:/msys32/home/Administrator/ttyd-master/msys2/ttyd/src/ttyd-1.5.2/src/server.h:3:10: fatal error: sys/ioctl.h: No such file or directory
    3 | #include <sys/ioctl.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/ttyd.dir/build.make:80：CMakeFiles/ttyd.dir/src/http.c.obj] 错误 1
make[1]: *** [CMakeFiles/Makefile2:76：CMakeFiles/ttyd.dir/all] 错误 2
make: *** [Makefile:130：all] 错误 2
==> 错误： 在 build() 中发生一个错误。
    正在放弃...
`
