### ISSUE TITLE
-U option is not available, still shows on the command line

### ISSUE THREAD

**Issue by lcuwx2016** [tsl0922/ttyd#1102]
**Describe the bug**
-U 选项不可用，但仍然在界面输入-h命令后显示

**To Reproduce**
执行命令 ttyd -i /dev/shm/ttyd.socket -H X-WEBAUTH-USER login

**Expected behavior**
Everything is fine

**Screenshots**
![image](https://user-images.githubusercontent.com/31233561/236616450-cd13cdf7-c894-4225-926c-34548f25d18a.png)
![image](https://user-images.githubusercontent.com/31233561/236616419-e79b3e2e-cc98-4544-b572-0377bef5c8c4.png)

**Environment:**
 - OS: Ubuntu 20.04 LTS
 - Browser:  Edge

**Additional context**
使用守护进程启动 ttyd, 每次都需要手动修改socket 文件权限 nginx才能访问，有无更加优雅的方式可以处理？

**Comment by tsl0922** [comment]
should be fixed on latest main branch now.
