### ISSUE TITLE
ping-interval probably not working

### ISSUE THREAD

**Issue by mstenz** [tsl0922/ttyd#1106]
I have watched the ws connection in the Browser developers tools and I think even when using the latest version which have ping-interval of 5 it only send from client to server ~300 seconds. 
Is there something hardcoded somewhere so the change default is not used?
Also setting the value manually to 30 with -P doesnt change anything

**Comment by tsl0922** [comment]
The browser may not displaying ping/pong frame, did you capture the traffic using something like Wireshark?

**Comment by tsl0922** [comment]
See also #949
