### ISSUE TITLE
Could you help me

### ISSUE THREAD

**Issue by knight-666** [tsl0922/ttyd#1107]
docker run -p 7681:7681 tsl0922/ttyd

I started using Docker, but the source ads is 127.0.0.1, and I am unable to open a web page on port 7681

Where should I change?
![image](https://user-images.githubusercontent.com/28332512/237010449-eab02977-00ce-4d83-b25c-8d2f414eca06.png)

**Comment by tsl0922** [comment]
I have reverted the `127.0.0.1` change, try the latest image.

**Comment by knight-666** [comment]
> I have reverted the `127.0.0.1` change, try the latest image.

thank

**Comment by knight-666** [comment]
I would like to have ttyd log in with a username and password by default after the Docker container is started. Can I put the relevant configuration for default login into a config file and map the container to this file.

What should I do?

**Comment by tsl0922** [comment]
ttyd does not do system login itself.

You may want to ask it on [stackoverflow](https://stackoverflow.com/).

**Comment by knight-666** [comment]
I found a solution

docker-compose config

version: '3'
services:
  ttyd:
    restart: always
    image: tsl0922/ttyd:latest
    container_name: ttyd
    network_mode: bridge
    ports:
      - '7681:7681'
    command: /bin/bash -c "apt-get update; echo 'y' | apt-get install openssh-client; echo 'root:passwd' | chpasswd; ttyd -W login;"
