### ISSUE TITLE
How to build static version? 

### ISSUE THREAD

**Issue by nephaste** [tsl0922/ttyd#111]
I am trying to build ttyd  for Qnap NAS   ( did Gotty already for all plateform)

i follow build instruction for the armv7 and aarch64... build impossible to find a way to build it statically

 `root@ts531P:/SRC/ttyd/build# ldd ttyd
        linux-vdso.so.1 =>  (0x7dc40000)
        libutil.so.1 => /lib/arm-linux-gnueabihf/libutil.so.1 (0x759d0000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x759b0000)
        libssl.so.1.0.0 => /lib/arm-linux-gnueabihf/libssl.so.1.0.0 (0x75970000)
        libcrypto.so.1.0.0 => /lib/arm-linux-gnueabihf/libcrypto.so.1.0.0 (0x75860000)
        libjson-c.so.2 => /lib/arm-linux-gnueabihf/libjson-c.so.2 (0x75850000)
        libcap.so.2 => /lib/arm-linux-gnueabihf/libcap.so.2 (0x75840000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x75758000)
        /lib/ld-linux-armhf.so.3 (0x540f8000)
        libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x75748000)`

Do you have any tips please ? seems you built the x64 version statically already

**Comment by nephaste** [comment]
thanks for pointing me in right direction.. seems it miss something to passed to Library linker flag on my aarch64 tries... guess an -ldl -lpthread to pass somewhere

```
root@TS-128A:/SRC# git clone --depth=1 https://github.com/tsl0922/ttyd.git \
>  && cd ttyd && sed -i '5s;^;\nSET(CMAKE_FIND_LIBRARY_SUFFIXES ".a")\nSET(CMAKE_EXE_LINKER_FLAGS "-static")\n;' CMakeLists.txt \
>  && cmake . && make install && cd .. && rm -rf ttyd
Cloning into 'ttyd'...
remote: Counting objects: 78, done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 78 (delta 1), reused 39 (delta 0), pack-reused 0
Unpacking objects: 100% (78/78), done.
Checking connectivity... done.
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/local/lib/libssl.a;/usr/local/lib/libcrypto.a (found version "1.0.2l")
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Looking for lws_config.h
-- Looking for lws_config.h - found
-- Checking for module 'json-c'
--   Found json-c, version 0.12.1
-- Found JSON-C: /usr/local/lib/libjson-c.a
-- Configuring done
-- Generating done
-- Build files have been written to: /SRC/ttyd
make: Warning: File 'Makefile' has modification time 3 s in the future
make[1]: Warning: File 'CMakeFiles/Makefile2' has modification time 2.9 s in the future
make[2]: Warning: File 'CMakeFiles/ttyd.dir/flags.make' has modification time 2.9 s in the future
[ 16%] Generating html.h from index.html
Scanning dependencies of target ttyd
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
make[2]: Warning: File 'CMakeFiles/ttyd.dir/flags.make' has modification time 2.4 s in the future
[ 33%] Building C object CMakeFiles/ttyd.dir/src/server.c.o
[ 50%] Building C object CMakeFiles/ttyd.dir/src/http.c.o
[ 66%] Building C object CMakeFiles/ttyd.dir/src/protocol.c.o
[ 83%] Building C object CMakeFiles/ttyd.dir/src/utils.c.o
[100%] Linking C executable ttyd
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libpthread.a(pthread_create.o): In function `allocate_stack':
/build/glibc-BinVK7/glibc-2.23/nptl/allocatestack.c:475: undefined reference to `_dl_stack_flags'
/build/glibc-BinVK7/glibc-2.23/nptl/allocatestack.c:475: undefined reference to `_dl_stack_flags'
/build/glibc-BinVK7/glibc-2.23/nptl/allocatestack.c:613: undefined reference to `_dl_stack_flags'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libpthread.a(unwind.o): In function `_jmpbuf_sp':
/build/glibc-BinVK7/glibc-2.23/nptl/../sysdeps/aarch64/jmpbuf-offsets.h:52: undefined reference to `__pointer_chk_guard_local'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libpthread.a(unwind.o): In function `unwind_stop':
/build/glibc-BinVK7/glibc-2.23/nptl/unwind.c:60: undefined reference to `__pointer_chk_guard_local'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libpthread.a(nptl-init.o): In function `__pthread_initialize_minimal_internal':
/build/glibc-BinVK7/glibc-2.23/nptl/nptl-init.c:305: undefined reference to `__libc_setup_tls'
/build/glibc-BinVK7/glibc-2.23/nptl/nptl-init.c:457: undefined reference to `_dl_pagesize'
/build/glibc-BinVK7/glibc-2.23/nptl/nptl-init.c:457: undefined reference to `_dl_pagesize'
/build/glibc-BinVK7/glibc-2.23/nptl/nptl-init.c:466: undefined reference to `_dl_pagesize'
/build/glibc-BinVK7/glibc-2.23/nptl/nptl-init.c:486: undefined reference to `_dl_init_static_tls'
/build/glibc-BinVK7/glibc-2.23/nptl/nptl-init.c:488: undefined reference to `_dl_wait_lookup_done'
/build/glibc-BinVK7/glibc-2.23/nptl/nptl-init.c:488: undefined reference to `_dl_wait_lookup_done'
/build/glibc-BinVK7/glibc-2.23/nptl/nptl-init.c:486: undefined reference to `_dl_init_static_tls'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libpthread.a(nptl-init.o): In function `__pthread_get_minstack':
/build/glibc-BinVK7/glibc-2.23/nptl/nptl-init.c:509: undefined reference to `_dl_pagesize'
/build/glibc-BinVK7/glibc-2.23/nptl/nptl-init.c:509: undefined reference to `_dl_pagesize'
/usr/local/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x18): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x28): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x34): undefined reference to `dlclose'
/usr/local/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x368): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x420): undefined reference to `dlerror'
/usr/local/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_var':
dso_dlfcn.c:(.text+0x498): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x550): undefined reference to `dlerror'
/usr/local/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
dso_dlfcn.c:(.text+0x5b0): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x618): undefined reference to `dlclose'
dso_dlfcn.c:(.text+0x650): undefined reference to `dlerror'
/usr/local/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x6f0): undefined reference to `dladdr'
dso_dlfcn.c:(.text+0x770): undefined reference to `dlerror'
/usr/local/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
dso_dlfcn.c:(.text+0x7c8): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
CMakeFiles/ttyd.dir/build.make:183: recipe for target 'ttyd' failed
make[2]: *** [ttyd] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ttyd.dir/all' failed
make[1]: *** [CMakeFiles/ttyd.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by santosh0705** [comment]
Dockerfile-static is an working example. Easiest way to get static binary is build the Docker image and get it from there.

**Comment by nephaste** [comment]
May be but i dont see reason why it didnt compile in my chrooted Xenial arm64

look like pthread try to link to a dynamic libc ... (not sure)... 

tried several option in CMakeList.txt with -lpthread or -ldl .. it remains always the same error...

i am out of idea for moment

**Comment by tsl0922** [comment]
[Dockerfile-static](https://github.com/tsl0922/ttyd/blob/master/Dockerfile-static) is based on alpine linux, which uses musl libc. I didn't use glibc because of it's size is large.

**Comment by santosh0705** [comment]
@tsl0922 I replaced openssl with llibressl and saved another 300kb.

**Comment by nephaste** [comment]
Finally build with shared for x86_64 and armv7 ... unfortunately arm v8 (aarch64) version start well.. but give a grey html page...  (nothing in debug -d 7 revelant)

wonder if next version can work with arm64 (aarch64) and also if you can add a daemonize flag and a pid file flag location

**Comment by santosh0705** [comment]
Grey color is the theme set for xterm in the code.
Daemonizing services are old school now. Modern init system and other process managers like supervisord/runit or even docker work with process running in foreground.

**Comment by nephaste** [comment]
yes.. i see grey is theme for xterm ... i initiate command /bin/login to have credential
but on ARMV8 got this behavior and command line is not display (tried with multiple browser)
it is an Ubuntu Xenial chroot used for compilation....

daemonize, and pid file are usefull, dont forget i am on a NAS system, not a standard distro
logfile as well should be a plus to have a debug log in plain text (from stdout)

**Comment by tsl0922** [comment]
> unfortunately arm v8 (aarch64) version start well.. but give a grey html page

Interesting , do you have any error on ttyd log or browser console?

**Comment by tsl0922** [comment]
**Good news:** I've cross compiled the static `x86_64-linux-musl` binary on my mac with [homebrew-musl-cross](https://github.com/FiloSottile/homebrew-musl-cross).

It's possible to setup automatic docker builds for other targets, I'm building cross compilers on linux now.

**Comment by tsl0922** [comment]
@neelchauhan I've cross compiled linux static binaries with musl libc for multiple targets (ttyd 1.4.0):

[ttyd-linux-musl-static.tar.gz](https://github.com/tsl0922/ttyd/files/2343181/ttyd-linux-musl-static.tar.gz)

Targets included:

- aarch64
- arm
- armhf
- mips
- mipsel
- i686
- x86_64

Tested the `x86_64` and `mipsel` version, works for me.

**Comment by tsl0922** [comment]
Pushd the cross compile script to repo:

https://github.com/tsl0922/ttyd/blob/master/scripts/cross.sh

**Comment by nephaste** [comment]
wow thanks a lot.. many thanks very good job....

i am checking asap

**Comment by nephaste** [comment]
all version are working nicely

arm64, armv7, armv5 tested working    :)

**Comment by tsl0922** [comment]
Good, if you want smaller binary on embed systems, consider using [upx](https://upx.github.io) to compress it.

**Comment by Zibri** [comment]
@tsl0922 
since the static versions are outdated, can you please tell me how to compile it statically on  x86_64 ?

**Comment by methaqualon** [comment]
> @tsl0922 since the static versions are outdated, can you please tell me how to compile it statically on x86_64 ?

in the project folder with all installed requirements:
`sudo /scripts/./cross-build.sh`


@tsl0922 thank you so much for your project!
