### ISSUE TITLE
Bump `xterm.js` dependency to `master`

### ISSUE THREAD

**Issue by maaslalani** [tsl0922/ttyd#1113]
Hey there, first off, thank you for the awesome project.

Secondly, there has been a recent bug fix in the canvas renderer for `xterm.js` which is on the latest `master` but hasn't been released yet.

https://github.com/xtermjs/xterm.js/issues/4120

Because `ttyd` is using the latest release (instead of `@master`) we are seeing the bug appear still in a project that depends on ttyd:

https://github.com/charmbracelet/vhs/issues/249

I was hoping it would be possible for `ttyd` to bump the `xterm.js` dependency, if possible, to use the latest `master` code so that we can fix the canvas renderer issues we are seeing.

Thank you!

**Comment by tsl0922** [comment]
I've already bumped it to a recent 5.2.0-beta release (e01e213dbb55bedf96551dfd7807ccc56d330484), does it work for you?

**Comment by maaslalani** [comment]
Thanks so much! I will try it out. Really appreciate it ❤️

**Comment by maaslalani** [comment]
Thank you, it worked! Very much appreciated!
