### ISSUE TITLE
use fontSize There will be one more line#

### ISSUE THREAD

**Issue by WPF0414** [tsl0922/ttyd#1131]
**Describe the bug**
use fontSize There will be one more line#

**To Reproduce**
1. apt install supervisor
2. supervisor command /root/ttyd.x86_64 -p 7681 -t "disableReconnect=true" -t "disableLeaveAlert=true" -t "fontSize=16" zsh
3. request 127.0.0.1:7681
4. There will be one more line#

**Expected behavior**
Delete the # of the first line

**Screenshots**
<img width="347" alt="image" src="https://github.com/tsl0922/ttyd/assets/41565284/343127fb-d529-429b-8562-ebba5d1728a0">
<img width="1089" alt="image" src="https://github.com/tsl0922/ttyd/assets/41565284/3793a89d-981e-4598-8225-e57d5bfe4fc4">
<img width="405" alt="image" src="https://github.com/tsl0922/ttyd/assets/41565284/f0c8914c-646d-4a2e-ab85-6af0fda17550">

**Environment:**
 - OS: Linux docker 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux
 - Browser: [e.g. Chrome 13.0.5672.126（正式版本） (arm64)]

**Comment by tsl0922** [comment]
Can not reproduce.

All the lines come from tty output, check your shell configuration.
