### ISSUE TITLE
option once doesn't work

### ISSUE THREAD

**Issue by xtuer** [tsl0922/ttyd#1140]
**Describe the bug**
option once doesn't work

**To Reproduce**
1. Start ttyd: `./ttyd.x86_64 -w --once -p 54321 bash`
   `./ttyd.x86_64 --once -p 54321 bash` works without option `-w`
3. Access the ttyd in browser with url http://localhost:54321
4. Access successfully.
5. Refresh the web page and the ttyd process doesn't quit.

**Expected behavior**
The ttyd process exit when the page is refreshed.

**Screenshots**

**Environment:**
 - OS: Centos 7.6
 - Browser: Chrome 113

**Comment by tsl0922** [comment]
```
-w, --cwd               Working directory to be set for the child program
-W, --writable          Allow clients to write to the TTY (readonly by default)
```

Your command will set `--cwd` with `--once`, you may want to use `-W`?

**Comment by xtuer** [comment]
> ```
> -w, --cwd               Working directory to be set for the child program
> -W, --writable          Allow clients to write to the TTY (readonly by default)
> ```
> 
> 
>     
>   
> 
> Your command will set `--cwd` with `--once`, you may want to use `-W`?

Thank you very much!
You are right. I had a mistake when using the option -w.
