### ISSUE TITLE
进luci空白无显示,手动输入ip+端口也进不去

### ISSUE THREAD

**Issue by nimasi** [tsl0922/ttyd#115]
openwrt编译无报错  启动项ttyd也没有被禁用

进luci空白无显示,只看见终端两个字
手动输入ip+端口也进不去

mt7620n

**Comment by tsl0922** [comment]
这个问题可能的原因是你的路由器没有 `br-lan` 接口，可以删除 `/etc/init.d/ttyd` 里的 `-i br-lan` 参数再试试看（注意这样 
ttyd 也会同时监听 wan 口，可被外网访问）。
