### ISSUE TITLE
Why is the generated image unusable?

### ISSUE THREAD

**Issue by Sanmejie** [tsl0922/ttyd#1160]
`FROM ubuntu:18.04
RUN apt-get update && apt-get install -y autoconf automake curl cmake git libtool make \
    && git clone --depth=1 https://github.com/tsl0922/ttyd.git /ttyd \
    && cd /ttyd && env BUILD_TARGET=x86_64 ./scripts/cross-build.sh

FROM alpine
COPY --from=0 /ttyd/build/ttyd /usr/bin/ttyd
RUN apk --no-cache add tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && apk del tzdata \
    && apk update \
    && apk upgrade \
    && apk add vim git zsh curl nano htop wget screen tini \
    && apk --no-cache add bash

EXPOSE 7681

WORKDIR /root

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["ttyd","-t","enableZmodem=true","bash"]`
I need to install some software into the container beforehand

The container service created with this image cannot input content, why?

Take a look

**Comment by tsl0922** [comment]
```
CMD ["ttyd", "-W", "bash"]
```

You need to add `-W` to make it writable.
