### ISSUE TITLE
Is it possible to check whether the target program successfully started?

### ISSUE THREAD

**Issue by xtuer** [tsl0922/ttyd#1169]
Such as run ttyd using the command `/root/ttyd -p 25006 --once mysql -h192.168.12.21 -P35001 -uroot -pmypassxx`,
actually the program `mysql` is launched at the first time accessed from the browser instead of execute the above command after pressing the enter key.

It would be better when the enter key is pressed which immediately starts the target program such mysql, so that we can analyze the log to know whether the program start failed or success.

**Comment by tsl0922** [comment]
It has nothing to do with ttyd. ttyd is not a shell, it doesn't handle your input, the input is forwarded to the process.

You may want to write a shell script to check enter key and start mysql.
