### ISSUE TITLE
did ttyd support background color type like #aabbcc, only ANSI color?

### ISSUE THREAD

**Issue by Brian099** [tsl0922/ttyd#1172]
when I test with this code, in wiki:
ttyd -t cursorStyle=bar -t lineHeight=1.5 -t 'theme={"background": "green"}' bash
change green to #686868, and try on :7681, it display right, 
but when I add it ass an option "-t 'theme={"background": "#686868"}'"in initab file, it can not reach :7681 any more, only when I use color name, it wrok.

**Comment by tsl0922** [comment]
you don't use the issue template, it should have something in the log.

try:
```
-t "theme={\"background\": \"#686868\"}"
```
