### ISSUE TITLE
Suggestion - fail2ban integration with reverse proxy

### ISSUE THREAD

**Issue by hdijkema** [tsl0922/ttyd#1173]
I'm running ttyd behind an apache2 reverse proxy. 
I've created a setup that forwards the remote address of the party logging in with ttyd to /var/log/auth.log

To achieve that, I've written a simple alt-login program, which also always denies root access.

Also a script (install.sh) that:

*  installs ttyd as a system service 
* installs a fail2ban configuration to block ip addresses that try to login too often, as a security measure

The repository provides an apache2 configuration file with the reverse proxy setup and rewrite rules to let the whole setup work correctly.

Just to let you know.
 
Repository is here: https://github.com/hdijkema/alt-login

**Comment by tsl0922** [comment]
You may want to add it to the [wiki](https://github.com/tsl0922/ttyd/wiki)
