### ISSUE TITLE
Enable data compression

### ISSUE THREAD

**Issue by niutech** [tsl0922/ttyd#1179]
Please enable compression of TTYd standard output data, possibly using WebSocket compression ([RFC 7692](https://datatracker.ietf.org/doc/html/rfc7692.html)). When I scroll through an output of a big file, it is laggy. Thanks.

**Comment by niutech** [comment]
I can see that WebSocket extensions: `permessage-deflate` and `deflate-frame` are mentioned in [server.c](https://github.com/tsl0922/ttyd/blob/main/src/server.c#L35) but `LWS_WITHOUT_EXTENSIONS` is set to 1 by default in libwebsockets CMake. Could you please set `LWS_WITHOUT_EXTENSIONS=0`?

**Comment by tsl0922** [comment]
bf06c1449eae6e0d8da4dff12d7a91e4adc68fcb

**Comment by niutech** [comment]
Thank you!
