### ISSUE TITLE
after i start success, but i can't input any content in browser terminal

### ISSUE THREAD

**Issue by Crazyokd** [tsl0922/ttyd#1184]
**Describe the bug**
after i start success, but i can't input any content in browser terminal.

**To Reproduce**
1. install ttyd
2. ttyd bash
3. can't input anything in browser terminal

**Expected behavior**
input content successful.

**Screenshots**
![image](https://github.com/tsl0922/ttyd/assets/74645100/d00ab8c9-5ca6-47f5-8539-65f54b97a535).

**Environment:**
 - OS: [Windows11 wsl ubuntu]
 - Browser: [Chrome 115.0.5790.110]

**Comment by rhythm-appyhigh** [comment]
If you check the logs on terminal, you'll find that it's opened in readonly mode. You need to add a flag `--writable` to make it accept commands

**Comment by Crazyokd** [comment]
yes, i check the logs and find it's opend in readonly mode. then i checked the command option, find it need use -W or --writable to enable write option. Thank you so much.
