### ISSUE TITLE
ttyd automatically clears after small inactivity

### ISSUE THREAD

**Issue by sam5558** [tsl0922/ttyd#1186]
Hello,
I'm pretty new to ttyd project, however i have a setup with an already installed version of ttyd.
Current version used is 1.6.3.

I want to get rid of the auto-clearing of screen after small amount of time of inactivity (maybe 1 or 2 minutes ?)

Options used right now : 
```
TTYD_OPTS="-t disableLeaveAlert=true -t theme={'background':'black'} -t fontSize=15 -t fontFamily=monospace"
```
I've tried `-t disableReconnect=true` option, but it seems that it doesn't fix my issues.

Is there any option that can help me get rid of the auto-clear ?

Thank you

**Comment by Zibri** [comment]
check the PID... perhaps it's not a clear but it just starts another shell.
unfortunately ttyd is multisession and does not support resuming the previous session.

**Comment by tsl0922** [comment]
It's reconnected. ttyd will reset the terminal on new session.
