### ISSUE TITLE
A bar with special keys

### ISSUE THREAD

**Issue by cadaver123** [tsl0922/ttyd#1187]
**Is your feature request related to a problem? Please describe.**
On-screen keyboards lack special keys such as ctrl, alt, tab, home, end, arrows, etc. - it hinders the usage of a terminal, when somebody connects to it via a tablet or phone.

**Describe the solution you'd like**
It would be great to add an option for displaying a bar at the bottom of the screen with special keys, similar to the solution implemented in some native apps, e.g., Android ConnectBot:
![image](https://github.com/tsl0922/ttyd/assets/1839663/8826c5fa-eb36-4771-bdbe-9513bd85cb9c)

**Comment by Savanta** [comment]
Hacker's keyboard my man, but indeed something like termux extra keys would be great
