### ISSUE TITLE
Feature: option to connect to the same session or start a new one.

### ISSUE THREAD

**Issue by Zibri** [tsl0922/ttyd#1189]
The main reason I used a different program (I wrote) and not ttyd is this:

let's say you have a session going on and for a moment the client network goes down....
all work on that shell is lost.

Also, supporti a "session number" would allow two different people to interact with the same shell, which is what I do often.
That can be two different people or myself using the same shell on 2 different clients.

The solution could be to implement and url parameter as session number (or a random hash).
In this way if a connection starts without the session number, a new session will be generated.
If instead the session number/has is present, it will be connected to the one that had that hash.

**Comment by Zibri** [comment]
Update: I added an optional url parameter which will make ttyd use a single session.
So if you close the tab and open it again, you will get the same process (resume) and not a new one.
Now I just have to implement the multi user :D
If you are interested I can put the code up on github..

**Comment by Nriver** [comment]
What you are looking for is a terminal multipluxer like [tmux](https://github.com/tmux/tmux/wiki)

**Comment by tsl0922** [comment]
> What you are looking for is a terminal multipluxer like [tmux](https://github.com/tmux/tmux/wiki)

I would recommend tmux too.
