### ISSUE TITLE
No text is shown when using the Tizen browser on Tizen OS

### ISSUE THREAD

**Issue by lwbt** [tsl0922/ttyd#1198]
**Describe the bug**
No text is shown when using the Tizen browser on Tizen OS

**To Reproduce**
1. Start ttyd on Ubuntu
2. Access the address in Chrome or Firefox on a different machine to test that it can be accessed
3. Try to access the same address on a smart TV or beamer with Tizen and the Tizen browser

**Expected behavior**
The terminal is shown like on any other browser and operating system.

**Screenshots**
The background color is shown. The cursor changes from arrow to text input in the upper left corner of the page, but no text is shown at all. Also input like `ls` or `touch test.txt` has no effect. I tried `ttyd -t rendererType=dom` but it didn't help either.

**Environment:**
 - OS: Tizen OS Version <s>1420</s> 1523 on Samsung Freestyle LSP3 Beamer
 - Browser: Tizen Browser 5.2.06080

**Additional context**
- I tried finding a website hosting another kind of xtermjs application and found that the example on https://xtermjs.org/ was capable of displaying text and processing my input.
- I tried building ttyd from source with modifications to the style, but I was unable to produce static binaries to test further on the x86_64 client I want to run ttyd on.
- Tizen browser seems to be the only available browser for Tizen.
- I tried navigating some other sites like https://codesandbox.io/examples/package/xterm but the browser/device choked and didn't load the entire site. It would have been nice to use ttyd evenif only in some limited way though.

**Comment by tsl0922** [comment]
If you're using the latest version, start ttyd with `-W` option and try again.

**Comment by lwbt** [comment]
Hello, I tried with the `-W` or `--writable` option. But the issue remains. Meanwhile the OS has updated to 1523.

**Comment by lwbt** [comment]
A follow up:

* Newer device with: \
  `Mozilla/5.0 (SMART-TV; Linux; Tizen 7.0) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/6.0 Chrome/94.4696.31 TV Safari/537.36` \
  works
* Older device with: \
  `Mozilla/5.0 (SMART-TV; Linux; Tizen 6.5) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.0 Chrome/85.4183.93 TV Safari/537.36` \
  does not work
