### ISSUE TITLE
unicode handling?

### ISSUE THREAD

**Issue by Zibri** [tsl0922/ttyd#1199]
if I start ttyd and run bash -i
then I do:

echo "──────────"

I get --------- instead of ──────────

is there a way to avoid this and have unicode passthrough nicely?

![image](https://github.com/tsl0922/ttyd/assets/855176/f7de8b14-7844-407d-8435-fb37c041aaf8)

the above picture seems "normal" but i wrote: echo "──────────"

**Comment by tsl0922** [comment]
Can't reproduce, could you try the latest version?

**Comment by Zibri** [comment]
> Can't reproduce, could you try the latest version?

I am using the latest version....
if you clone it you can use it online on replit:
https://replit.com/@zibri/bash2

**Comment by tsl0922** [comment]
ttyd doesn't handle encoding itself. If you can reproduce it with [xterm.js demo](https://github.com/xtermjs/xterm.js/wiki/Contributing#running-the-demo), you may report it to the upstream xterm.js project.
