### ISSUE TITLE
ttyd listens by default on tcp 7681 on ALL interfaces, IPv4/IPv6, without any firewall rules.

### ISSUE THREAD

**Issue by Aditza2015** [tsl0922/ttyd#12]
cross-post from https://github.com/openwrt/packages/issues/3271

please use secure defaults if ttyd is started without any configuration

![r1725_ttyd_ - masked_ip6](https://cloud.githubusercontent.com/assets/16319504/19013187/4b602768-87d2-11e6-86fc-a777c4816800.png)

make it work only via https TLS 1.2/1.3, without http and change it so by default it listens only on local-network and only on IPv4 reserved-local addresses. This could be changed later from configuration, but the defaults should not allow access from outside the local network.

**Comment by tsl0922** [comment]
Closing this issue in favor of the openwrt side.
