### ISSUE TITLE
Opening URLs on the client browser

### ISSUE THREAD

**Issue by justinvdk** [tsl0922/ttyd#1200]
**Is your feature request related to a problem? Please describe.**

Outside of `ttyd` I use `open` or `xdg-open` to open "things" (files and directories mainly).
It allows me to open directories in a GUI file explorer and (http(s)) links in a browser.
With `ttyd` most URLs wouldn't make sense but http(s) links would be nice.
For example: I could script a way to open `VSCode` with a command called `code` just like the "real thing" but instead opening my [code-server](https://github.com/coder/code-server) instance at the correct location.

**Describe the solution you'd like**
A solution would be to have at least a way to open URLs, such that just `http|https` URLs can be opened.
A more bare bones solution where I'd have to implement some handling my self on the client (web, javascript) side of things would also be acceptable.

**Describe alternatives you've considered**
Copy pasting links, but sometimes its nice to just be able to fire up a new tab automatically, instead of dealing with clipboard. Especially because clipboard might be:
- polluted with newlines where there are none
- when using something such as `screen` or `tmux` a "line" in `ttyd`'s output might not represent an actual "line" in the terminal.

**Additional context**
I use `ttyd` primarily as a way to connect to a permanent `tmux` session as to not rely on local hardware/software and be able to just use a browser.

With this issue I mainly want to discuss options as all roads lead to Rome but I'd rather have a reliable implementation; and maybe others are in the same boat.

**Comment by tsl0922** [comment]
You can already click url while pressing `Ctrl`.
