### ISSUE TITLE
ttyd still listening from external IP

### ISSUE THREAD

**Issue by SubhashBose** [tsl0922/ttyd#1206]
**Describe the bug**
The release note of the latest version mentions that the default listening interface is 127.0.0.1. However, I can still connect to ttyd from external IPs.

**To Reproduce**
Command to start
$ ./ttyd -p 7777 bash
Then connect from a different computer with the external IP

**Expected behavior**
Not to connect from external IP

**Environment:**
 - OS: Raspberry PI OS
 - Browser: Chrome

However, if I add  the flag `-i 127.0.0.1`, then it works as intended. Although this is not a major issue, but this can be security issue if someone doesn't pay attention and go by documentation.

**Comment by tsl0922** [comment]
The code was reverted in f8efcddb0b615de7086fdb3c5f452d1ee42f32a3. Maybe I found some issue with `127.0.0.1` at that time. Removed it from 1.7.4 changelog.

> but this can be security issue

ttyd will start in readonly mode by default since 1.7.4
