### ISSUE TITLE
Unable to type in ttyd

### ISSUE THREAD

**Issue by sindhubb** [tsl0922/ttyd#1217]
**Describe the bug**
Not able to type in the ttyd 

**To Reproduce**
1. Run ttyd with `/opt/homebrew/bin/ttyd -t disableReconnect=true -t fontSize=16 --port 8182 /bin/zsh`
2. go to `http://localhost:8182` 
3. Try to type something
4. Nothing gets typed on screen

**Expected behavior**
I expect for what i typed on keyboard to appear on the ttyd

**Environment:**
 - OS: Mac OS Sonoma 14.0
 - Browser: Arc Browser 1.11.0

**Additional context**
Tried with Safari also, same results

**Comment by sindhubb** [comment]
> there is a workaround, I tried with the -W option and it works
> 
> ```
> ttyd -W -p 8889 bash
> ```

Tried this, works independently when run in terminal. But if its part of runit script it doesn't work.

**Comment by araczkowski** [comment]
I'm running it in pm2 and it works OK with -W option
![image](https://github.com/tsl0922/ttyd/assets/1263968/c80486d7-521f-4fee-b001-70bbe29c72ba)

**Comment by tsl0922** [comment]
I've warned you it:
```
The --writable option is not set, will start in readonly mode
```
