### ISSUE TITLE
Font spacing issue

### ISSUE THREAD

**Issue by hugomatic** [tsl0922/ttyd#122]
Is there a way to adjust the font or spacing?

OS: Ubuntu 18.04.1 LTS
Chrome Version 69.0.3493.3 (Official Build) dev (64-bit)

Built from source, git log:

```
commit 250ac186c76f600b2f847a021498e55c2a5d4537 (HEAD -> master, origin/master, origin/HEAD)
Author: Daniele <daniele@brugnara.me>
Date:   Tue Aug 21 10:24:42 2018 +0200

    Update README.md (#119)
```

![screenshot from 2018-08-28 18-45-09](https://user-images.githubusercontent.com/41060/44760239-c1800400-aaf2-11e8-9f11-72befb67608c.png)

**Comment by tsl0922** [comment]
Yes, you can.

```
./ttyd -t letterSpacing=3px -t lineHeight=2 bash
```

**Comment by hugomatic** [comment]
thanks :-)
