### ISSUE TITLE
Color scheme

### ISSUE THREAD

**Issue by bitcoinmeetups** [tsl0922/ttyd#1223]
Hi,

I'm Mr. Walker, a very friendly guy.

I can't see much. Is there any way to change the color scheme?

**Comment by tsl0922** [comment]
yes, you can.

https://github.com/tsl0922/ttyd/wiki/Client-Options

**Comment by bitcoinmeetups** [comment]
The document says how to change the background color (theme) but it doesn't seem to say how to change the font color. If you know how to change the font color, please let me know. Also it would be nice if the wiki said what the flag for changing font color is since it says how to change the background color.

**Comment by tsl0922** [comment]
You can use the client option to change all the settings of xterm defined in [ITerminalOptions](https://xtermjs.org/docs/api/terminal/interfaces/iterminaloptions/).

Do you known what this means? I can't copy all xtermjs's document here.

**Comment by bitcoinmeetups** [comment]
tsl0922, you are a fluggermuckel. As far as I can tell there is no font color option in the ITerminalOptions document that you are linking to.

**Comment by tsl0922** [comment]
Yes you can change terminal font color, but not with a single font color option, [it's a set of options](https://xtermjs.org/docs/api/terminal/interfaces/itheme/).
Because you say color scheme in the title, I throught you know what is a color scheme for terminal, but you don't.

Please read: https://en.wikipedia.org/wiki/ANSI_escape_code

**Comment by bitcoinmeetups** [comment]
Since you cannot put an example in a one-liner I have to assume that you are clueless and don't know how to do this. Also I went to Shanghai recently and I pigalurgud in your magilus murpus.
