### ISSUE TITLE
Excessive CPU Usage by ttyd in Docker Container on EC2 Instance

### ISSUE THREAD

**Issue by scheidp** [tsl0922/ttyd#1224]
**Describe the bug**
`ttyd` is consistently consuming 100% of the CPU when running inside a Docker container on an AWS EC2 instance. This behavior is observed even with a minimal setup and no active connections.

**To Reproduce**
1. Build the Docker image from the provided Dockerfile below[1] (build for linux/amd64).
2. Transfer the image to a Linux EC2 instance.
3. Run the container using `docker run -d -p 7681:7681 -v /home/ubuntu/data:/home/ubuntu/data ast-inflam_scrnaseq-spatial_image2:2.0.0 ttyd -c user:password bash`
4. Observe the excessive CPU consumption of `ttyd` using tools like `top`. `ttyd` terminal loads in the browser but is unresponsive.

**Expected behavior**
I expected `ttyd` to run inside the Docker container without consuming excessive CPU, especially when no active connections are made to it.

**Screenshots**
![image](https://github.com/tsl0922/ttyd/assets/29561479/effd7e7f-936d-4044-87ce-c101e8082e17)

**Environment:**
 - OS: Linux (on an EC2 instance)

**Additional context**
The Docker image was originally built on an M1 MacBook Air and then transferred and run on a Linux EC2 instance. This issue has caused significant performance concerns and potential resource overuse.

1. Dockerfile

```
# Use an Ubuntu base image
FROM ubuntu:20.04

# Set environment variables to non-interactive (this prevents some prompts)
ENV DEBIAN_FRONTEND=non-interactive

# Install necessary dependencies and tools for ttyd compilation
RUN apt-get update && \
    apt-get install -y wget openssh-server software-properties-common git cmake g++ pkg-config && \
    apt-get install -y libjson-c-dev libwebsockets-dev

# Clone ttyd repository and compile
RUN git clone https://github.com/tsl0922/ttyd.git && \
    cd ttyd && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make && \
    make install


# Create SSH user and set password
RUN useradd -m sshuser && \
    echo "sshuser:password" | chpasswd

# Configure SSH to listen on port 7681
RUN sed -i 's/#Port 22/Port 7681/' /etc/ssh/sshd_config

# Install samtools v1.12
RUN apt-get update && apt-get install -y libncurses5-dev libbz2-dev liblzma-dev && \
    wget https://github.com/samtools/samtools/releases/download/1.12/samtools-1.12.tar.bz2 && \
    tar -xjf samtools-1.12.tar.bz2 && \
    cd samtools-1.12 && \
    ./configure && \
    make && \
    make install && \
    cd .. && \
    rm -rf samtools-1.12.tar.bz2 samtools-1.12

# Copy and extract CellRanger
COPY  cellranger-3.0.2.tar.gz /tmp/
RUN tar -xzvf /tmp/cellranger-3.0.2.tar.gz -C /opt && \
    ln -s /opt/cellranger-3.0.2/cellranger /usr/local/bin/cellranger

# Copy and extract SpaceRanger from local machine
COPY spaceranger-1.2.0.tar.gz /tmp/
RUN tar -xzvf /tmp/spaceranger-1.2.0.tar.gz -C /opt && \
    ln -s /opt/spaceranger-1.2.0/spaceranger /usr/local/bin/spaceranger

# Install HISAT2
COPY hisat2-2.1.0 /hisat2-2.1.0
RUN mv /hisat2-2.1.0/hisat2 /usr/local/bin && rm -r /hisat2-2.1.0

# Install StringTie from local directory
COPY stringtie-2.1.1.Linux_x86_64 /usr/local/bin/stringtie-2.1.1.Linux_x86_64
RUN ln -s /usr/local/bin/stringtie-2.1.1.Linux_x86_64/stringtie /usr/local/bin/stringtie \
    && ln -s /usr/local/bin/stringtie-2.1.1.Linux_x86_64/prepDE.py /usr/local/bin/prepDE.py

# Expose SSH port and ttyd port
EXPOSE 7681

# Start SSH server
CMD ["/usr/sbin/sshd", "-D"]
```

**Comment by tsl0922** [comment]
Can not reproduce, check if too many connections are opened.
