### ISSUE TITLE
ttyd stopped to work in interactive way

### ISSUE THREAD

**Issue by TamasSzerb** [tsl0922/ttyd#1229]
**Describe the bug**

**To Reproduce**
1. sudo /usr/bin/ttyd --base-path /ggg/ --interface lo --port 7681 --check-origin --debug 20 login
2. hit with browser http://localhost:7681/ggg/
3. cannot login, I can't see anything typed
4. in log:
[2023/10/20 00:34:04:0367] N: WS   /ggg/ws - 127.0.0.1, clients: 1
[2023/10/20 00:34:04:0421] N: started process, pid: 1351699
[2023/10/20 00:34:09:0164] N: __lws_lc_untag:  -- [wsisrv|0|adopted] (1) 5.077s

and tons of D (debug) but cannot see anything errorous.

**Expected behavior**
till the last upgrade it was working: 
ttyd -v                                                                                                          ✔  76907  00:36:46
ttyd version 1.7.4

**Screenshots**

**Environment:**
 - OS: cat /etc/os-release                                                                                              ✔  76912  00:38:12
PRETTY_NAME="Debian GNU/Linux trixie/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=trixie
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

apt show ttyd                                                                                                    ✔  76913  00:38:15
Package: ttyd
Version: 1.7.4-1

 - Browser: [e.g. Chrome 79.0.3945.130]

**Additional context**

**Comment by cayspekko** [comment]
> The default listen interface/ip is changed to 127.0.0.1 now
> The web terminal is readonly by default now, to make it writable, use -W option.

should see this in logs:
N: The --writable option is not set, will start in readonly mode

**Comment by tsl0922** [comment]
Start with `-W` option.
