### ISSUE TITLE
Illegal back-to-back write error

### ISSUE THREAD

**Issue by needo37** [tsl0922/ttyd#124]
When using 1.4.0 still seeing this error with libwebsockets3. Running this on ArchLinux. Please see the attached logfile.

Thank you!

[ttyd.log](https://github.com/tsl0922/ttyd/files/2347360/ttyd.log)

**Comment by tsl0922** [comment]
I'm sorry, 1.4.0 isn't a new release, please compile from the latest mater branch and try again.

It's an accident that 1.4.0 got republished,  I was editing it to add new precompiled binaries 😢.
