### ISSUE TITLE
tmux with sixel support 

### ISSUE THREAD

**Issue by ctorney** [tsl0922/ttyd#1248]
**Is your feature request related to a problem? Please describe.**
Currently sixel images aren't displayed in ttyd when using tmux. This is because tmux will only show sixel images if it can detect the size of the window in pixels.

When I launch ttyd the values for ws_xpixel and ws_ypixel accessed [here](https://github.com/tmux/tmux/blob/381c00a74ea1eb136a97c86da9a7713190b10a62/tty.c#L129) are both 0. 

**Describe the solution you'd like**
It seems that the xterm image addon is able to get the win size in pixels (described [here](https://github.com/xtermjs/xterm.js/tree/fb2c39cb5748e071e0a1ed49824590aafd45e65e/addons/addon-image#general-notes)). Is it possible to set these parameters so that tmux can read them when it calls ioctl?

**Comment by ctorney** [comment]
It seems that zellij doesn't have this problem so I've switched to zellij and closing this issue

**Comment by Redst0neFlux** [comment]
This is still an issue. I run tmux on armhf (zellij is 64bit only) and encountered this problem. My TTYD_OPTIONS is TTYD_OPTIONS="-W -t enableTrzsz=true -t enableSixel=true machinectl shell delphi@ /usr/bin/tmux". My ttyd version is 1.7.4-fa1ee59
