### ISSUE TITLE
Colors are off in Firefox and Edge but look correct in Chrome

### ISSUE THREAD

**Issue by needo37** [tsl0922/ttyd#125]
Please see the attached screenshot. 

The colors do not look correct.

![ttyd](https://user-images.githubusercontent.com/5664046/45071744-6a070880-b09d-11e8-914e-9f1be0102628.PNG)

**Comment by tsl0922** [comment]
ttyd uses a custom color scheme. If you want to custom it, you can change the following lines, and rebuild ttyd:

https://github.com/tsl0922/ttyd/blob/master/html/js/app.js#L253-L273
