### ISSUE TITLE
development libreries in stage-packages???? 

### ISSUE THREAD

**Issue by Delphi251189** [tsl0922/ttyd#1253]
Is it really needed to include development versions of  package in stage-packages ?
Snap package install size is ~240 MB and includes compiler and  x86_64-linux-gnu-* files in install directory...
Is it a bug??? 

https://github.com/tsl0922/ttyd/blob/5aa2da4bd36858a287224e41a14cc3e6e6a47616/snap/snapcraft.yaml#L43

**Comment by tsl0922** [comment]
ping @kz6fittycent. Do you have any idea for it?
