### ISSUE TITLE
issue on fast keyboard repeat rate or delay on cursor move

### ISSUE THREAD

**Issue by shohey1226** [tsl0922/ttyd#126]
First of all, thank you for this amazing app.
I have a question that I could not solve by myself.

I started to use vim trough ttyd and found some delay issue on key repeat.
When I press "j" to move and could not place the cursor to the right place.
I also can see this behavior on terminal, for example, keep pressing down a key and press up, then the keys are pushed with slight delay.  (I don't see this through ssh)
When I change key repeat to fastest, the behavior is obvious.

May I know where I should check to solve this? browser's key repeat looks good to me. This kind of issue has not reported on xtermjs.. 

Thank you in advance.

**Comment by tsl0922** [comment]
Reproduced.

This issue seems to be introduced in the 1.4.1 release, I will prepare a fix later. Meanwhile, you can use the 1.4.0 release.

**Comment by shohey1226** [comment]
Thank you for checking this.  I use [forked 1.4.0](https://github.com/shohey1226/ttyd)(only html change) on Ubuntu.  It looks the same on ChromeOS. The key repeat can be fast on both OS.

I checked with my macOS and it looks much better with your key repeat setting on Chrome.  This is very little feeling and not sure it's being fixed by this setting..

**Comment by tsl0922** [comment]
@shohey1226 Can you try if the latest master works better?

**Comment by shohey1226** [comment]
@tsl0922  Thank you. It's better but 1.4.0 of cursor move on vim is still smoother than 1.4.1.  For example,  cursor block on 1.4.0 is rendered every time it moves, whereas on 1.4.1, cursor block is not rendered every time and skipped some, which makes me difficult to stop in the right place.

**Comment by tsl0922** [comment]
The Websocket backend on master is faster than 1.4.0 according to my tests, I'm not sure this is a xterm.js issue. Also, it I disable all the vim plugins, it renders incredibly fast on the web.

**Comment by tsl0922** [comment]
@shohey1226 I've downgraded xterm.js, it should works like 1.4.0 now, can you try the latest master again? Thanks.

**Comment by shohey1226** [comment]
@tsl0922 I've compared xtermjs 3.3.0's commit and master(xterm 3.7.0) and I don't see much difference. Most likely the fix you made for this makes cursor move fast and my eyes can't catch up with the move. I think this issue has been resolved.  Thank you very much for the quick fix.

**Comment by tsl0922** [comment]
Released 1.4.2 with this fix included.
