### ISSUE TITLE
Feature: web-based port forwarding for http services

### ISSUE THREAD

**Issue by jkroepke** [tsl0922/ttyd#1266]
**Is your feature request related to a problem? Please describe.**
I would like to run `python3 -m http.server` inside ttyd and open the port inside the browser.

**Describe the solution you'd like**
I'm looking for the same feature as provided by Azure Cloud Shell
https://learn.microsoft.com/en-us/azure/cloud-shell/using-the-shell-window#web-preview

The Web preview feature only works with HTTP and HTTPS services, which is FINE in my case.

![image](https://github.com/tsl0922/ttyd/assets/1560587/f56ecb35-ec9a-4164-878b-4389e514696e)

The Webshell asks for a port on the target shell (e.g. port 8000) and the port is availible under a specific sub-path `/proxy/8000`

This Youtube videos explains it well: https://www.youtube.com/watch?v=R1-JuJfrKNw

**Describe alternatives you've considered**
N/A

**Additional context**
I'm not expecting to share RAW TCP tunnel via this feature.

This feature would be great! I'm, using ttyd inside kubernetes and I would like to run `kubectl port-forward` to access Webfrontends of single pods.

**Comment by tsl0922** [comment]
No. I want to keep it simple, you do it with other tools.
