### ISSUE TITLE
Non-ASCII characters lost in tmux

### ISSUE THREAD

**Issue by angles-n-daemons** [tsl0922/ttyd#1267]
Hi there, I'm looking for support with a rendering issue. It seems like combining tmux and ttyd causes any non-ascii characters to appear as underscores `_` in the ttyd page. I've some examples below which show both ttyd and tmux working well on their own, but the combination of the two causing issues.

I'm happy to investigate this further, though I have little idea where to begin looking.

![image](https://github.com/tsl0922/ttyd/assets/7353765/06f5be6d-8e97-4d0b-bc6e-37843d298314)
ZSH in Terminal OSX

![image](https://github.com/tsl0922/ttyd/assets/7353765/cd8f46d2-e644-4541-bfba-575b16a1dad2)
ZSH in ttyd

![image](https://github.com/tsl0922/ttyd/assets/7353765/fd34bdcd-542a-4df3-ae07-6ccd4d8574cc)
tmux in Terminal OSX

![image](https://github.com/tsl0922/ttyd/assets/7353765/e988a756-dc1d-4105-b155-885a2a5c4b1a)
tmux in ttyd

**Comment by angles-n-daemons** [comment]
Notes:

➜  ~ tmux -V
tmux 3.3a

➜  ~ zsh --version
zsh 5.9 (x86_64-apple-darwin22.0)\

➜  ~ ttyd -v
ttyd version 1.7.4

**Comment by angles-n-daemons** [comment]
Chrome version: 119.0.6045.199 (Official Build) (x86_64)

**Comment by tsl0922** [comment]
Can not reproduce on my machine (running ttyd from WSL Ubuntu, open the web page with Chrome latest)

I don't think it will be a ttyd issue, if you think it is, check if it can be reproduced in [xterm.js demo](https://github.com/xtermjs/xterm.js/wiki/Contributing#running-the-demo)

**Comment by angles-n-daemons** [comment]
It may have been an incompatibility with my node version, after bumping node from v15 -> v20 it started working (needed to bump to run the demo)

**Comment by angles-n-daemons** [comment]
Thanks for the direction!

**Comment by angles-n-daemons** [comment]
The above resolution may have been hasty. The issue seems to be that I'm running ttyd as a launch daemon for osx. I'm not sure exactly why running it with launchctl would cause this issue, though I'm going to put the issue away for now

**Comment by angles-n-daemons** [comment]
If you have a mac, feel free to try by cloning [this repo](https://github.com/angles-n-daemons/env) and starting with the step `Setup ttyd`
