### ISSUE TITLE
Ability to set disableLeaveAlert=true in query string

### ISSUE THREAD

**Issue by mdevaev** [tsl0922/ttyd#1270]
Hi! I need a feature that would allow me to open the terminal in different modes: both with and without a closing warning. It would be great if it was possible to pass a parameter to the URL query string for this. The `-t disableLeaveAlert=true` option is not enough, since it determines the behavior of the entire daemon.

**Comment by mdevaev** [comment]
@tsl0922 boop

**Comment by mdevaev** [comment]
@tsl0922 I would give you $50 if you make this small feature :)

**Comment by tsl0922** [comment]
Well, this is a free software + side project, I make no profit from it. If you really want to support me financially, you can do it through github sponsors.

Feature requests from sponsors will be prioritized, but I can't make any guarantee that any request from sponsors will be implemented.

**Comment by mdevaev** [comment]
I understand your position, but I wanted to know if it's even possible to implement this in your current architecture with little blood.

**Comment by tsl0922** [comment]
It's possible, and not hard, will take a look at it when I'm free.

**Comment by mdevaev** [comment]
Crap, github won't accept my card for sponsorship for some reason. If you have a paypal, please send me the address to mdevaev@gmail.com, I'll tip you with it.

**Comment by tsl0922** [comment]
You don't need to pay me for it.

I sent this question to some friends and there is a guy who wants to help you implement it :)

**Comment by mdevaev** [comment]
Then let him send me his paypal, I'm eager to part with the money)

**Comment by tsl0922** [comment]
Wait for his PR, then you can contact him.

**Comment by cangzhang** [comment]
Hey @tsl0922 @mdevaev, I've sent a PR for it 😄

**Comment by mdevaev** [comment]
It was fast! Did you test it?

Send me your paypal to my email ^^^

**Comment by cangzhang** [comment]
@mdevaev It's merged https://github.com/tsl0922/ttyd/commit/dea883a7fced1030d7ce67db2ea3a524f1b4fda4

**Comment by tsl0922** [comment]
You can now override any client options with URL query parameters.

Note that URL query parameters has a higher priority than server side command-line arguments.

**Comment by tsl0922** [comment]
FYI: I've setup my Patreon account, you may sponsor me on github through patreon now:

https://docs.github.com/en/sponsors/sponsoring-open-source-contributors/sponsoring-an-open-source-contributor-through-patreon

or do it on patreon: https://www.patreon.com/tsl0922

**Comment by mdevaev** [comment]
Subscribed. Great work!

**Comment by mdevaev** [comment]
@tsl0922 Could you bump release? I need it for the upstream distro.

**Comment by tsl0922** [comment]
[1.7.5](https://github.com/tsl0922/ttyd/releases/tag/1.7.5)

**Comment by mdevaev** [comment]
Thanks!
