### ISSUE TITLE
ttyd server does not respond to user input

### ISSUE THREAD

**Issue by angles-n-daemons** [tsl0922/ttyd#1281]
I have this weird issue where loading tmux in Chrome will bring up the page, send the initial prompt - and then not respond to any additional keystrokes. For clarity, when I see the page using the below command, I only see the following prompt:

```./build/ttyd  -i 127.0.0.1 /bin/bash```
^ command to start ttyd

```bash-3.2$ ```
^ what I see in chrome when I load localhost:7681

Keystrokes seem to do nothing, and looking in the network tab it seems like there is an existing websocket connection which is sending the messages to the server. This leads me to believe that something at the server or beyond is failing. I should note that this used to work fine, but stopped working recently.

**System Details:**

Chrome version:
120.0.6099.129

➜ ~ tmux -V
tmux 3.3a

➜ ~ zsh --version
zsh 5.9 (x86_64-apple-darwin22.0)\

➜ ~ ttyd -v
ttyd version 1.7.4
also built from source @ fd280fee92cb874c74fc87559d9e723d900b3267

**Comment by tsl0922** [comment]
#1229
