### ISSUE TITLE
Start command before connection is made

### ISSUE THREAD

**Issue by stdweird** [tsl0922/ttyd#1287]
Start the command passed to ttyd asap, it now looks like the command is only started when the connection to ttyd is made (unless i am looking at some misconfig on my side or a bug).

**Comment by tsl0922** [comment]
It's by design.

**Comment by stdweird** [comment]
@tsl0922 i understand. is there a way to trigger the command start from cli, eg by crafting some http request?

**Comment by tsl0922** [comment]
No, the command start on websocket opened only, and killed on websocket close.

If you really want to do it, you may want to run the command with tmux.
