### ISSUE TITLE
SSL certificate and key for uhttpd on OpenWrt are not recognized.

### ISSUE THREAD

**Issue by masx200** [tsl0922/ttyd#1290]
**Describe the bug**
SSL certificate and key for uhttpd on OpenWrt are not recognized.
**To Reproduce**

```
/usr/bin/ttyd -p 7443 -6 -S -C /etc/uhttpd.crt -K /etc/uhttpd.key -d 15 login
```

ttyd can not work

**Expected behavior**

**Screenshots**

**Environment:**
 - OS: OpenWrt 23.05.2 r23630-842932a63d / LuCI openwrt-23.05 branch git-23.306.39416-c86c256
 - Browser:  Google Chrome 版本 120.0.6099.200（正式版本） （64 位）

**Additional context**

**Comment by masx200** [comment]
SSL certificate and key for uhttpd is not pem format

**Comment by tsl0922** [comment]
https://github.com/tsl0922/ttyd/wiki/SSL-Usage
