### ISSUE TITLE
No reply to commands for ttyd running at win10

### ISSUE THREAD

**Issue by Sfinx** [tsl0922/ttyd#1291]
**Describe the bug**

1. install ttyd with scoop. Run it with 'ttyd -p 8080 cmd'
2. go to http:ip/8080
3.  see the cmd prompt
4. try to enter any command
5. nothing is happened

**Expected behavior**

Keypresses must be displayed, commands must be entered

**Environment:*

ttyd:

```
ttyd 1.7.4-fa1ee59 (libwebsockets 4.3.2-unknown)
```

ttyd OS: 

```
Microsoft Windows [Version 10.0.19043.1052]
```

Browser:
```
Crome Version 121.0.6167.85 (Official Build) (64-bit)
```

Browser OS:

```
Ubuntu x86_64 22.04.3 LTS (Jammy Jellyfish)
```

**Comment by tsl0922** [comment]
Read the changelog: https://github.com/tsl0922/ttyd/releases/tag/1.7.4

Also, check log message:
```
N: The --writable option is not set, will start in readonly mode
```

**Comment by Sfinx** [comment]
-W did the trick ! 🙈
