### ISSUE TITLE
Query command

### ISSUE THREAD

**Issue by baterflyrity** [tsl0922/ttyd#1294]
Hi! Very nice tool, thanks.

It would be grateful to parse *initialization command* in URL in query that should be run on page load.

Example:
1. Developer shares new super-duper service link with manager or customer with built-in command: `https://example.org:1234?command=super-duper-service%20--help`
2. Manager opens this link during meetup.
3. When page is loaded, command `super-duper-service --help` is automatically inputted and return is pressed.
4. Manager sees help of *super-duper-service* or the most beautiful example and can follow working with it.

This would be very helpful when you want to share terminal with non-developers who have no time to study into environment or documentation - just show exciting chart and get promotion on one click :)

**Comment by tsl0922** [comment]
```
-a, --url-arg           Allow client to send command line arguments in URL (eg: http://localhost:7681?arg=foo&arg=bar)
```

You can implement it with `--url-arg`, for example: run a shell script as start command, parse the url arg in the script and do whatever you want.
