### ISSUE TITLE
Why can't ttyd let the browser save passwords?

### ISSUE THREAD

**Issue by masx200** [tsl0922/ttyd#1295]
**Is your feature request related to a problem? Please describe.**

Why can't ttyd let the browser save passwords?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![Screenshot_2024-02-08-09-45-22-578_com.android.chrome.jpg](https://github.com/tsl0922/ttyd/assets/34191203/8d1f6c3d-7bac-4522-acd5-6e86ef3d89cc)

**Comment by tsl0922** [comment]
Because it does not work like that way.
