### ISSUE TITLE
Does anyone know how to use nginx to reverse proxy ttyd?

### ISSUE THREAD

**Issue by pangqingyuan1991** [tsl0922/ttyd#130]
I have a web server http://xxx.yyy.zzz which is nginx server. And I also run ttyd at port 1234
Now I want to visit ttyd by http://xxx.yyy.zzz/console, so I need nginx proxy.
I have try several google solutions, but all failed.
Can anyone tell me how?
Thanks!

**Comment by pangqingyuan1991** [comment]
location ^~ /console {
            proxy_pass http://127.0.0.1:1234/;
        }

**Comment by pangqingyuan1991** [comment]
This works.
```
location ^~ /console {
                proxy_pass http://127.0.0.1:54366/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;        
                proxy_set_header Connection "upgrade";
        }

```

**Comment by shkim** [comment]
Doesn't work. In my case, i got /auth_token.js 404 error.
I think this feature requires #151 implemented.

**Comment by leifliddy** [comment]
Thanks! Would have taken me ages to figure that out.
