### ISSUE TITLE
Attach to process

### ISSUE THREAD

**Issue by MohamedKarrab** [tsl0922/ttyd#1300]
Is there a way to make ttyd not start a new process for each connection but attach all clients to one single instance/process ?
( -o doesn't solve this as I need to allow multiple connections)

**Comment by tsl0922** [comment]
It's possible, but you need other tools like tmux, see "Sharing single process with multiple clients" in [Example Usage](https://github.com/tsl0922/ttyd/wiki/Example-Usage).
