### ISSUE TITLE
Clear up security implications of default (no `--writable`) mode

### ISSUE THREAD

**Issue by JKHSDTV** [tsl0922/ttyd#1314]
I ask for myself, but think it would be very much worthwhile to add the answer to the landing page readme:

Is the default mode without the explicit `--writable` considered 'secure' in the sense that I could expose it to the internet ? Obviously, one needs to use their own judgment when it comes to what is exposed as possibly sensitive data (such as the process list when exposing `top`), and naturally, additional security ought to be imposed through authentication, IP/subnet restrictions and so on, but beyond those aspects, it is unclear whether that switch is a restriction on the level of `robots.txt`, where it blocks naive keypresses, but isn't designed to foil a determined bad actor, or whether the switch is expected to effectively block anyones 'best efforts', discounting the always-present option of undiscovered bugs.

I would suggest a paragraph in the readme with an answer along the following lines:

a) In the absence of `-W`/`--writable`, the displayed terminal will be entirely read-only and is safe to expose without worrying about users potentially abusing the process' privileges. The sensitivity of the displayed data should still be considered [...etc...]

b) The implicit lack of `-W`/`--writable` is a convenience feature to prevent accidental keystrokes, and should not be considered a security measure as it is not designed to foil a determined bad actor.

As a bonus, I would recommend an explicit `--non-writable` that would cause an error if a `-W` is added later on the line to allow for an explicit instead of implicit decision on the ... writability.

Thanks for making this tool, I use it mostly for monitoring so I don't have to leave a shell open and I love how easy it makes things.

**Comment by tsl0922** [comment]
Well, there is no absolute secure.

> a user should know the risk of running this program

The readonly default is a way to make it "looks secure", and make people to stop reporting it as a security problem (#692).
