### ISSUE TITLE
Cannot add PPA: 'ppa:~tsl0922/ubuntu/ttyd-dev', ERROR: '~tsl0922' user or team does not exist.

### ISSUE THREAD

**Issue by geekchy** [tsl0922/ttyd#132]
According to the linux installation guide, when I run 
step 2: 
**sudo add-apt-repository ppa:tsl0922/ttyd-dev**
Tips:
Cannot add PPA: 'ppa:~tsl0922/ubuntu/ttyd-dev', ERROR: '~tsl0922' user or team does not exist.

**Comment by tsl0922** [comment]
The ppa version is outdated, I'll update it later. Please download binary from the release page: 

https://github.com/tsl0922/ttyd/releases

**Comment by tsl0922** [comment]
I've updated the README to replace the ppa section with release url.
