### ISSUE TITLE
Feature request: custom webpage title

### ISSUE THREAD

**Issue by wdscxsj** [tsl0922/ttyd#133]
It seems that ttyd always sets the webpage title to the full terminal command. It's distracting if the command is long, and sometimes reveals too much detail. Could we have an option to use a custom title like "demo"?

Invoking a "demo" script to hide the detail is an easy workaround, but doesn't feel as natural. Thanks for your great work.

**Comment by tsl0922** [comment]
I'm not going to add this, because you can always change title with shell script, for example:

```
echo -ne "\033]0;demo\007"
```

The string `demo` will be prepended to the page title.

**Comment by wdscxsj** [comment]
But how to **set** the title? And this doesn't seem to work inside a tmux session...

**Comment by tsl0922** [comment]
Currently, the default title is always appended to the page title, I'm considering remove it when the terminal title is customized so that the page title will be on your control.

Again, there won't be an option to change the default title, because it may confuse people that the title may be changed later by a terminal program.

**Comment by wdscxsj** [comment]
OK, thanks for your explanation. 👍

**Comment by wdscxsj** [comment]
Sorry to bother again... I totally agree that the title shouldn't be changed from the executed command (e.g. a bash session), but it's not what I proposed. Isn't it better if the title can be controlled by `ttyd`, the "master" process? That is:

```bash
ttyd tmux new -A -s demo                # case 1
ttyd -t title=demo tmux new -A -s demo  # case 2
```

In case 1, the webpage title is a verbose `tmux new -A -s demo`, and gets longer easily.

In case 2, with an added client option or something, the webpage title is a succinct `demo`. Fully controlled by ttyd, not affected by what happens in the terminal session.

**Comment by tsl0922** [comment]
Well, I agree it is not flexible here, I will check how it behaves on other terminal applications.

`-t` is only used for [xterm.js](https://xtermjs.org/docs/api/terminal/interfaces/iterminaloptions/) options for now, we need a new option for title.

**Comment by XianwuLin** [comment]
Because I will use the ttyd to open multiple servers at the same time, I want to be able to customize the title like gotty, so I can distinguish which server is from the title. What should I do?

**Comment by BiatuAutMiahn** [comment]
Any Updates on this PR?

**Comment by archetype2142** [comment]
Still looking for this update

**Comment by tsl0922** [comment]
Added support on master, usage:

```bash
ttyd -t titleFixed=hello bash
```
