### ISSUE TITLE
1.7.6 reports incorrect version

### ISSUE THREAD

**Issue by maciejwalkowiak** [tsl0922/ttyd#1339]
**Describe the bug**

`ttyd -v` reports version `0.0.0-unknown` making it impossible to use with https://github.com/charmbracelet/vhs, as VHS checks the ttyd version number before it runs.

**To Reproduce**

```
$ brew install ttyd
$ ttyd -v
ttyd version 0.0.0-unknown
```

**Environment:**
 - OS: macOS 14.2.1

**Comment by tsl0922** [comment]
It should work if you install it with `brew install ttyd --HEAD`.

The version info is fetched from git tag in 1.7.6 release, homebrew uses source archive which is not a git repo, so no version info will be detected..

**Comment by maciejwalkowiak** [comment]
Thanks for quick reply. Confirming, installing with `--HEAD` solves the problem.

**Comment by tsl0922** [comment]
Sorry for the confusion, I've released 1.7.7 to revert the static version in source archive.

The release action now checks the version bump, it will fail if I forget to bump version in CMakeLists.txt.

**Comment by maciejwalkowiak** [comment]
Fantastic! Thank you!
