### ISSUE TITLE
[HELP] how to fix incorrect word spacing like this?

### ISSUE THREAD

**Issue by 77-arthur** [tsl0922/ttyd#1341]
I got incorrect word spacing with `unRaid`(6.11.5) which uses ttyd provide the webterminal window. 

And the build-in `ttyd` version is `1.6.3`

relate softwares and version:
- unraid: 6.11.5
- ttyd: 1.6.3
- browser: firefox 124.0.1

![图片](https://github.com/tsl0922/ttyd/assets/50293747/97d3652b-dca8-4077-bbce-5b420266860e)

**Comment by liyansong2018** [comment]
I also encountered the same problem.

**Comment by liyansong2018** [comment]
https://github.com/tsl0922/ttyd/wiki/Client-Options

**Comment by 77-arthur** [comment]
I fixed it by use [noMeiryoUI](https://github.com/Tatsu-syo/noMeiryoUI) change win11 system font from `Microsoft YaHei UI` to  `PingFang`.

![图片](https://github.com/tsl0922/ttyd/assets/50293747/57b5e641-46ab-4e03-a267-d1c3bfd0c5a9)
