### ISSUE TITLE
How to use --url-arg

### ISSUE THREAD

**Issue by aditer00** [tsl0922/ttyd#1352]
Hi everybody,

I saw about this project and it's really cool, but I have a little question about the url argument ( --url-arg) option

How to use it? I don't understand, can any of you give me an example?

I plan to use it to run several commands, for example if I enter the url http://localhost:7681/?run=script1. Then bash script1 will be executed, and so on.

Thank you in advance

**Comment by tsl0922** [comment]
https://github.com/tsl0922/ttyd/issues/171#issuecomment-594311238

**Comment by aditer00** [comment]
Thank you for the answer, now I can execute script1 if I use http://localhost:7681/?arg=script1

I have another question, what if I want to change ?arg to something else?

For example, I want to change it to ?run
So it would be http://localhost:7681/?run=script1
