### ISSUE TITLE
slow performance when running neovim with a theme

### ISSUE THREAD

**Issue by aneeshdurg** [tsl0922/ttyd#136]
Using neovim with a dark theme is too slow to be considered usable. Theme I'm using: moloki.

When launching neovim without my config (nvim -u NONE) the issue goes away.

I suspect this is because neovim is continually trying to redraw the background if the background is a different color.

**Comment by shohey1226** [comment]
I've seen this on Vim8 too. I tried to find dark background and dracula theme is okay for the performance. I'm curious why this happens.

```
colorscheme dracula 
set background=dark
```

**Comment by aneeshdurg** [comment]
If I had to suggest a fix without even looking at the code, maybe the current background color could be cached and further requests to change the background can be ignored if it is the same.

Iirc tmux does something similar, which is why some vim themes don't render perfectly on it.

**Comment by tsl0922** [comment]
This maybe an upstream issue. Can you reproduce it with the [xterm.js](https://github.com/xtermjs/xterm.js) demo app and provide a chrome pref profile like what I did in xtermjs/xterm.js#1677?

**Comment by tsl0922** [comment]
I've upgraded xterm.js to `3.8.0`, please check if it works.

**Comment by shohey1226** [comment]
@tsl0922  Thank you. Just checked and looks much better.  If the width of window is bigger, like `296x62`, then it becomes a bit slow. But I think it's usable to have vim theme now.

**Comment by aneeshdurg** [comment]
It's still not usable when using with fullscreen, but yeah, with a smaller window size it is somewhat usable.

**Comment by 3ightbit** [comment]
I have some performance issues similar to what you describe. They are most noticeable with line/page redraws and when using Firefox. I think found out that the slow down is introduced with this commit: https://github.com/tsl0922/ttyd/commit/8ff3d313807c6c328956f297b0a86ca2589f7d31. I may try to look more into it later.

**Comment by tsl0922** [comment]
Please test the 1.6.0 release, and try if the webgl renderer (`-t rendererType=webgl`) helps.
