### ISSUE TITLE
滚动打印日志时终端出现重新连接

### ISSUE THREAD

**Issue by chclass** [tsl0922/ttyd#1364]
**Describe the bug**
在命令行cat文件内容或者滚动log打印几秒后会出现重新链接问题

**Environment:**
-  K8s 容器
 - Browser: [版本 124.0.6367.201（正式版本） (arm64)]

**Comment by j4ckstraw** [comment]
我们有同样的问题，目前怀疑和ingress有关。在经过ingress的情况下，会有此问题，直连pod的情况，暂时没有复现问题。

**Comment by tsl0922** [comment]
重新连接的原因可能有很多，程序自己退出或者网络问题等，仅凭你给的信息无法判断是不是 ttyd 的问题。

**Comment by j4ckstraw** [comment]
我们通过使用screen/tmux工具来绕过网络不稳定的问题。
