### ISSUE TITLE
How To implement OSCLinkProvider

### ISSUE THREAD

**Issue by openmax** [tsl0922/ttyd#1370]
This is the implementation in xterm.js of the OSCLinkProvider : 
https://github.com/xtermjs/xterm.js/blob/master/src/browser/OscLinkProvider.ts

if there isn't a linkHandler it uses a _defaultActivate_ where a STRONG WARNING push up appares, that advice you about the risk
if you open the url ...  

`activate: (e, text) => (linkHandler ? linkHandler.activate(e, text, range) : defaultActivate(e, text))`

So, my question is: how can i implement the linkHandler in ttyd in order to bypass the warning for a secured selected list of urls 
that i'm ok with .. ? 

Example : 
in my terminal  : 
`# echo -e 'click here: \x1b]8;;https://xtermjs.org\x07OSC 8 hyperlink text\x1b]8;;\x07'`
than i have a link to https://xtermjs.org that without the use of linkHandler it push out :   

> > Do you want to navigate to ${uri}?\n\nWARNING: This link could potentially be dangerous

**Comment by tsl0922** [comment]
The source code related to xterm is located at: [html/src/components/terminal/xterm/index.ts](https://github.com/tsl0922/ttyd/blob/main/html/src/components/terminal/xterm/index.ts),  you can change it yourself, then [rebuild the html](https://github.com/tsl0922/ttyd/tree/main/html#development) and recompile ttyd.
