### ISSUE TITLE
How to use the terminal ip address

### ISSUE THREAD

**Issue by AmbitionHX** [tsl0922/ttyd#1372]
Describe your problem or question here.
ttyd -p 48620 --ipv6 --ssl --ssl-cert *.pem --ssl-key *.key --ssl-ca ca.pem -W /secgate/bin/login
/secgate/bin/login This is a process, which is used to receive the account password verification sent by ttyd. I want to realize that ttyd will also send the terminal ip to this process. What should I do at present？？？

**Comment by tsl0922** [comment]
It not supported yet.

Similar issue: #709
