### ISSUE TITLE
Custom Font Support

### ISSUE THREAD

**Issue by LorenzHohermuth** [tsl0922/ttyd#1375]
**Is your feature request related to a problem? Please describe.**
I'm writing my own GitHub Codespace image for my personal GitTea but with neovim.
And i use Nerdfonts for my Icons. I tried to use a [fork](https://github.com/metorm/ttyd-nerd-font) but he adopted it not fully a lot broken and it dose not work in my Dockerfile. 

It would be really nice if it were possible to use custom fonts.

My repo: [https://git.lorenzzz.dev/lorenzhohermuth/nvim-pod](https://git.lorenzzz.dev/lorenzhohermuth/nvim-pod)

**Comment by tsl0922** [comment]
https://github.com/tsl0922/ttyd/wiki/Serving-web-fonts
