### ISSUE TITLE
Client option -t disableResizeOverlay=true does not seem to work

### ISSUE THREAD

**Issue by psgganesh** [tsl0922/ttyd#1378]
The client option -t disableResizeOverlay=true does not seem to work even when run with -t option nor on the browser with 

http://localhost:7681/?fontSize=24&disableLeaveAlert=true&rendererType=canvas&disableResizeOverlay=true&theme={%22background%22:%20%22green%22}

**Comment by psgganesh** [comment]
![Uploading Screenshot 2024-06-09 at 9.27.06 AM.png…]()

**Comment by psgganesh** [comment]
<img width="1165" alt="Screenshot 2024-06-09 at 9 27 06 AM" src="https://github.com/tsl0922/ttyd/assets/2221525/b02c3ef6-2d96-4181-8795-4a4e3ebf83e0">

**Comment by tsl0922** [comment]
Try `disableResizeOverlay=1`
