### ISSUE TITLE
[Question] How can I select all text on console to copy it to a local file?

### ISSUE THREAD

**Issue by dts-1504** [tsl0922/ttyd#1384]
I want to copy all output text then copy to a local file to do searching/filtering purpose. How can I do that?

Currently the only way I can use is to use mouse to select text and scroll all the way top to down bottom of the console screen, then copy it by CTRL+C.

I've tried CTRL+A but it does not take any effect. 

If possible, Search Box or Save Output button feature would be great

**Comment by tsl0922** [comment]
Use pipe to redirect it to a file, then send the file with [lrzsz](https://ohse.de/uwe/software/lrzsz.html).
