### ISSUE TITLE
Client option 'disableReconnect=true' seems is not working

### ISSUE THREAD

**Issue by xwhong** [tsl0922/ttyd#1385]
When i enabled client option 'disableReconnect=true', user still can reconnected to server after exited in the same page. What's the expected behavior for this option? Can you help explain in detail, thanks.

<img width="590" alt="image" src="https://github.com/tsl0922/ttyd/assets/11023610/df1854f5-bac5-4a58-8f59-4a752576b37c">

And can we have a way to disable 'Press ⏎ to Reconnect'
https://github.com/tsl0922/ttyd/blob/1.7.7/html/src/components/terminal/xterm/index.ts

**Comment by tsl0922** [comment]
It disables the auto reconnect feature.
