### ISSUE TITLE
How to capture the logs from the screen that is shared using ttyd

### ISSUE THREAD

**Issue by mahesware** [tsl0922/ttyd#1386]
Describe your problem or question here.
i ran the below instance of ttyd on my centos machine
** ttyd --writable -p 8080 telnet <ip> **

this resulting terminal window was shared on a web browser using <machineIp:8080> ,  i wanted to capture what ever being executed on that terminal window shared over browser, i have gone through the documentation of ttyd, I did not found any such logging mechanism. how to achieve this ?

**Comment by tsl0922** [comment]
#251
