### ISSUE TITLE
request to authenticate Linux local user

### ISSUE THREAD

**Issue by chillancezen** [tsl0922/ttyd#1387]
**Is your feature request related to a problem? Please describe.**
yes, `--credential  ` is not a good option for me as it shows plain password where everyone is able to see it. instead, sometimes, I need to authenticate client with Linux user in a uniform way.

**Describe the solution you'd like**

add a new option `--authenticate-user <linux user name, e.g admin>` which has priority over `--credential `.

**Describe alternatives you've considered**
no workaround.

**Additional context**
``` 
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <shadow.h>
#include <crypt.h>
#include <string.h>

// Function to authenticate user
int authenticate(const char *username, const char *password) {
    struct spwd *spw;
    char *encrypted_password;
    
    // Get the shadow password entry
    spw = getspnam(username);
    if (spw == NULL) {
        perror("getspnam");
        return 0;
    }

    // Encrypt the input password with the salt from the stored password
    encrypted_password = crypt(password, spw->sp_pwdp);
    if (encrypted_password == NULL) {
        perror("crypt");
        return 0;
    }

    // Compare the encrypted password with the stored password
    if (strcmp(encrypted_password, spw->sp_pwdp) == 0) {
        return 1; // Authentication successful
    } else {
        return 0; // Authentication failed
    }
}

int main() {
    char username[256];
    char password[256];

    printf("Enter username: ");
    if (scanf("%255s", username) != 1) {
        fprintf(stderr, "Failed to read username\n");
        return 1;
    }

    printf("Enter password: ");
    if (scanf("%255s", password) != 1) {
        fprintf(stderr, "Failed to read password\n");
        return 1;
    }

    if (authenticate(username, password)) {
        printf("Authentication successful\n");
    } else {
        printf("Authentication failed\n");
    }

    return 0;
}
```
here is a very simple code snippet which utilize `/etc/password`  to authenticate client.  though I suppose it Linux/Unix only.

please let me know whether you accept this feature. 
I could submit my patch for it in my free time~

thanks.

**Comment by tsl0922** [comment]
https://github.com/tsl0922/ttyd/wiki/Example-Usage

If you want to login with your system accounts on the web browser, run `ttyd login`.

**Comment by chillancezen** [comment]
perfect.
