### ISSUE TITLE
Receive input from URL query

### ISSUE THREAD

**Issue by xiaodong-lx** [tsl0922/ttyd#1390]
**Is your feature request related to a problem? Please describe.**
`ttyd` can receive input from URL query to login as user or do other things.

**Describe the solution you'd like**
Run:
```bash
ttyd login
````

Open <https://ttyd-server-url:8080/?input=user%0Apassword> (`user\npassword` after encoded), so `ttyd` can auto input `user` and `password` to `login` command. Is safe if using Https.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by rchernobelskiy** [comment]
Here you go: https://github.com/tsl0922/ttyd/issues/1294
