### ISSUE TITLE
Publish images to ghcr.io

### ISSUE THREAD

**Issue by jkroepke** [tsl0922/ttyd#1391]
**Is your feature request related to a problem? Please describe.**
ttyd images are located at DockerHub. DockerHub has some rate-limits which can be problematic in some situations.

**Describe the solution you'd like**
Provide an alternative registry where images can be stored. For example, GitHub provides an own Container registry (ghcr.io) which can be used within the repository.

**Describe alternatives you've considered**

Docker-Sponsored Open Source Program is an alternative to resolve the rate-limits issue on a image basis. 

https://docs.docker.com/trusted-content/dsos-program/

**Additional context**
N/A

**Comment by tsl0922** [comment]
Good idea, will do it later.

**Comment by tsl0922** [comment]
Done.
