### ISSUE TITLE
start on boot, no need to open macos terminal

### ISSUE THREAD

**Issue by Rizkiacry** [tsl0922/ttyd#1392]
i want to replace my default terminal with ttyd open in browser. usually i have to type "ttyd -p 8080 zsh" first then open the one on the browser. maybe a solution is to start ttyd on boot. any help will be appreciated.

**Comment by tsl0922** [comment]
Check https://github.com/tsl0922/ttyd/wiki/Systemd-service.

For other os, ask it on https://stackoverflow.com.
