### ISSUE TITLE
./ttyd -W login ERROR

### ISSUE THREAD

**Issue by ancienter** [tsl0922/ttyd#1393]
**Describe the bug**
it do not work when run "./ttyd -W login ERROR" in openEuler 20.03 (LTS-SP4) ，and i cant see any error message.
web only this
![图片](https://github.com/user-attachments/assets/4d52f48e-22c5-4d9a-8c8f-f85c91784b6b)

**Comment by antedebaas** [comment]
im having the same issue.
this only happens if i start with login as command.
if i start it with bash it works fime

**Comment by tsl0922** [comment]
Check https://github.com/tsl0922/ttyd/issues/768
