### ISSUE TITLE
choose port to listen

### ISSUE THREAD

**Issue by fangxian** [tsl0922/ttyd#14]
We can listen to the port 0~1023 if we have the root access to run the program, however 1~1023 ports are "privileged" ports. It may not safe if we listen these ports. 
So in the code
if (info.port < 0) {
                    fprintf(stderr, "ttyd: invalid port: %s\n", optarg);
                    return -1;
}
Do we need to change the condition if( info.port < 0) to if(info.port < 1024)?

**Comment by tsl0922** [comment]
I don't think listening on a "privileged" port is not safe, if you don't want to use root user to run the command, you can use the `--uid` and `--gid` option to run ttyd as other user and group.
