### ISSUE TITLE
关于ttyd外网使用问题

### ISSUE THREAD

**Issue by wackejohn** [tsl0922/ttyd#140]
你好，目前ttyd如果需要在外网使用，必须在外网打开ttyd监听的端口（目前嵌套进luci的代码都是由客户端发起http/https连接请求），有没有可能实现由路由（服务端）本身发起http/https连接请求至ttyd，这样ttyd的监听端口就不用暴露在外网了。。。

**Comment by tsl0922** [comment]
理论上来说：有，但需要在 luci 上实现 websocket 的代理，这已经不是本项目的范围了。ttyd 本来就可以脱离 luci 使用，而且也可以通过配置保证安全性，嵌入进 luci 只是为了方便。
