### ISSUE TITLE
Please add xterm's addon-clipboard

### ISSUE THREAD

**Issue by olegkrutov** [tsl0922/ttyd#1408]
This addon provides OSC/52  sequences support, so TMUX selection can be copied to local clipboard. 

https://github.com/xtermjs/xterm.js/tree/master/addons/addon-clipboard

**Comment by tsl0922** [comment]
Added.

**Comment by chattytak** [comment]
Even if you try sending an OSC/52 signal, the string will not be copied to the system's clipboard.
```
printf "\e]52;c;%s\a" "$(echo "copy test" | base64 -w 0)"
```
If it is working correctly, this command should store the text "copy test" in the clipboard.
