### ISSUE TITLE
new terminal hang after I exit old terminal by type 'exit'

### ISSUE THREAD

**Issue by Xiaohua-Shen** [tsl0922/ttyd#142]
The steps to reproduce:
1. run a ttyd server
docker run -it --rm -p 7681:7681 tsl0922/ttyd:1.4.2
2. access it in browser,  and type in `exit`. 
3. after 10s, the terminal is reconnected, and type `ll`

it will hang, no output.

1.4.0 seems has no such issue.

it may caused by this commit. https://github.com/tsl0922/ttyd/commit/ff1f19d9ef2b3e1af6983a98ec36b3b9c1b677e2
or libwebsockets 3.0 related change.

**Comment by tsl0922** [comment]
This should not happen, clear the browser cache and try again.

**Comment by Xiaohua-Shen** [comment]
Thanks for the response.

I just retried on may laptop after clear the browser cache,  it still happened.    
my OS is macOS 10.14.2, and on macOS 10.13, it has same issue too.

**Comment by tsl0922** [comment]
This should be fixed on master now, try the `tsl0922/ttyd:latest` image.
