### ISSUE TITLE
cursor taller than line

### ISSUE THREAD

**Issue by Zibri** [tsl0922/ttyd#145]
![image](https://user-images.githubusercontent.com/855176/50384480-d13cdd00-06cd-11e9-8bf6-6355bffb9b0c.png)
is there any way to correct this?

**Comment by Zibri** [comment]
and, anyhow if you want a suggestion, defaults for xterm should these: https://jerbs.util.repl.run/

**Comment by tsl0922** [comment]
Upgraded to xterm.js 3.10.0 with upstream fix on master.
