### ISSUE TITLE
ERR_CONTENT_LENGTH_MISMATCH error

### ISSUE THREAD

**Issue by import-yuefeng** [tsl0922/ttyd#148]
首先非常感谢作者的ttyd, 它帮我们解决了一个我们项目中非常复杂的部分. 我们尝试实现用户在web界面进行选择任意的linux发行版, 后端系统可以启动一个安装好ttyd的对应容器, 实现用户可以在非常困难的情况下也可以学习和使用linux, 甚至在演讲时也可以快速得到一个干净的linux环境进行演示. 

不过当我们实现了第一个demo版本后, 我们发现连接到被启动的ttyd速度非常慢, 而且经常性无法连接到, 也就是同一个容器, 在不同时候得到的反馈不同, 有时可以连接, 有时不能连接.

我抓了下包, 分析了下网络, 我发现经常会报错ERR_CONTENT_LENGTH_MISMATCH, 导致无法连接到ttyd, 而在另一部分时间又可以连接上(针对同一个ttyd容器)

我不是很明确这个问题产生的原因和修复办法, 还请指导

这是super-inspire的临时体验地址: http://60.190.81.133:8888, 可以通过这个进行上述错误的测试和复现, 非常感谢. (目前我们开放了ubuntu14.04~16.04, centos全系统, alpine全系统 的体验)

代码可参考 super-inspire目前的地址为: github.com/super-inspire

感激不尽

附上测试信息如下:

Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
macOS Mojave 10.14.1 (18B75)

![error](https://user-images.githubusercontent.com/36234175/51086346-faa6d100-1780-11e9-9ddc-0af8217478fb.png)

**Comment by import-yuefeng** [comment]
当我清理了浏览器缓存之后, 这个问题出现的频率大幅度下降....

**Comment by import-yuefeng** [comment]
> 这个问题我在之前也遇到过，具体原因还没时间去查。ttyd 的 websocket 和 http 服务器功能都是由 libwebsockets 提供的，但这个库 3.x 版本较 2.x 版本改动很大，可能是在处理这部分兼容性的时候出现了问题，你可以尝试下 1.4.0 版本是不是好些。

好, 我尝试去修改一下这部分, 不过暂时发生的可能性不高, 所以我也没有特别在意

**Comment by shixiaobao17145** [comment]
> 这个问题我在之前也遇到过，具体原因还没时间去查。ttyd 的 websocket 和 http 服务器功能都是由 libwebsockets 提供的，但这个库 3.x 版本较 2.x 版本改动很大，可能是在处理这部分兼容性的时候出现了问题，你可以尝试下 1.4.0 版本是不是好些。

本地ttyd -I index.html就会复现这个问题，主要原因还是content length不对，应该是0，但是却出现233450，与实际的不匹配。
