### ISSUE TITLE
Implement file transfer

### ISSUE THREAD

**Issue by onny** [tsl0922/ttyd#150]
Hey,
would be cool to transfer files between the browser and ttyd. Like starting a file download to transfer files from ttyd to the local computer. Or drag and drop files into the shell window to upload them to the remote session.

Best regards,
Jonas

**Comment by tsl0922** [comment]
ttyd supports the [ZMODEM](https://en.wikipedia.org/wiki/ZMODEM) protocol, thus you can use tools like [lrzsz](https://ohse.de/uwe/software/lrzsz.html) to transfer files.

There's a screenshot on this release page: https://github.com/tsl0922/ttyd/releases/tag/1.4.0
