### ISSUE TITLE
Implement subdirectory / suburl

### ISSUE THREAD

**Issue by onny** [tsl0922/ttyd#151]
Hey,
Gotty has a feature to run the web terminal in a sub url, e.g. http://localhost:8080/ttyd.
Would it be possible to implement a command line argument like -s "ttyd" to enable suburl routing?

Best regards,
Jonas

**Comment by abduramann** [comment]
Is there any progress on this? If not, could you instruct how I can write the related part? I will try to add this feature.

**Comment by tsl0922** [comment]
resolved by #281

**Comment by onny** [comment]
Hey thanks for working on this! Guess this will be very useful in the future. Unfortunately it doesn't work for me yet.
```
ttyd -b "/ttyd" bash
ttyd --base-path "/ttyd" bash
```
But I only get 404 on http://playground.pi:7681/ttyd :,(
