### ISSUE TITLE
Unable to build html with nodejs > version 8.0

### ISSUE THREAD

**Issue by onny** [tsl0922/ttyd#156]
Hey,
the command ``yarn build`` fails with different errors when using nodejs > 8.0.
Best regards,
Jonas

**Comment by tsl0922** [comment]
Do you have any error logs? I've updated the `yarn.lock` file to download package from `yarnpkg.com`, please check if it works on master now.

**Comment by onny** [comment]
Thanks, works now with ``nodejs 11.10.0`` :+1:
