### ISSUE TITLE
100% cpu usage with Midnight Commander

### ISSUE THREAD

**Issue by zella** [tsl0922/ttyd#157]
I run `docker run -it --rm -p 7681:7681 tsl0922/ttyd` 

then install and run Midnight commander:  
`apt-get update && apt-get install mc && mc` 

Cpu usage become 100%  until I exit mc.  

Ubuntu 18.04, cpu - xeon 8 threads

**Comment by tsl0922** [comment]
Duplicate of #136,  I'm closing this one.

**Comment by tsl0922** [comment]
Sorry, it seems like you are reporting a backend issue?

**Comment by tsl0922** [comment]
Can not reproduce on my machine (running the command you given on docker on mac).

**Comment by patrickelectric** [comment]
I got the same problem on docker running on a raspberry, it was necessary to use --privileged option.
