### ISSUE TITLE
老师如何通过ttyd分享屏幕?

### ISSUE THREAD

**Issue by Postgres2016** [tsl0922/ttyd#158]
我做了多年IT培训工作。我想寻找一个软件，可以让学生通过浏览器看到老师的terminal. 譬如老师通过putty登录到Linux的shell，然后给一个网址给学员，学员打开任何支持浏览器的设备，包括手机，电脑和平板，就可以看到老师的操作了。不需要给学生通过Web界面操作的权限，他们只是观看，不能输入。

ttyd能实现这个功能吗？ 我的邮箱： itgotousa@gmail.com

非常感谢！

**Comment by tsl0922** [comment]
借助 tmux 和 ttyd 配合可以实现只读的屏幕分享：

1. 通过 tmux 启动 shell: `tmux new -A -s ttyd bash`
2. 用 ttyd 分享 shell：`ttyd -R tmux new -A -s ttyd`

这时候所有人打开 ttyd 的网页端看到的就是你想要的效果了。

**Comment by Postgres2016** [comment]
非常感谢！

已经搞定！ 这就是我要的效果！ ttyd能否支持大并发量？同时几百人上千人在线观看？是不是可以采用成熟的nginx之类的作为依托？ 我也有兴趣看看源码，看看能否有些帮助。

**Comment by tsl0922** [comment]
ttyd 最初是给路由器之类的平台做网页终端用的，后来才做的跨平台支持，所以没在大并发方面做过优化，客户端比较多的话可能会出现问题。
