### ISSUE TITLE
attach to current shell

### ISSUE THREAD

**Issue by Postgres2016** [tsl0922/ttyd#159]
使用tmux对很多人来说，门槛太高。

建议加一个attach选项。echo $$ 就可以拿到当前shell的pid

ttyd --attch pid就可以把ttyd放置在后台，同时捕获当前shell。这个对教学非常有帮助。

**Comment by tsl0922** [comment]
不考虑，这不是 ttyd 该解决的问题。捕获一个不是自己启动的进程的输入输出在很多系统上可能需要一些特权，而且用到的接口可能是调试接口。
