### ISSUE TITLE
ttyd has been removed from openwrt package feeds

### ISSUE THREAD

**Issue by s7lx** [tsl0922/ttyd#168]
ttyd has been removed from openwrt package feeds
Maybe it's removed recently . 
Until 18.06.1 , it still be there

**Comment by tsl0922** [comment]
It's sill in the [openwrt/packages](https://github.com/openwrt/packages/tree/master/utils/ttyd) repo, please open issue on that repo or the [openwrt forum](https://forum.openwrt.org/).

**Comment by tsl0922** [comment]
https://github.com/openwrt/packages/issues/8548
