### ISSUE TITLE
http works https does not.

### ISSUE THREAD

**Issue by Zibri** [tsl0922/ttyd#170]
This correctly works:

`./ttyd -p 8129 top
`

This does not. On the webpage it displays "400".

`./ttyd --ssl --ssl-cert /etc/letsencrypt/live/zibri.org/cert.pem --ssl-key /etc/letsencrypt/live/zibri.org/privkey.pem -p 8129 top`

log follows:

> [2019/04/12 14:29:08:0909] NOTICE: ttyd 1.4.2-7ed537a (libwebsockets 3.1.99)
> [2019/04/12 14:29:08:0911] NOTICE: tty configuration:
> [2019/04/12 14:29:08:0912] NOTICE:   start command: top
> [2019/04/12 14:29:08:0913] NOTICE:   close signal: SIGHUP (1)
> [2019/04/12 14:29:08:0913] NOTICE:   terminal type: xterm-256color
> [2019/04/12 14:29:08:0914] NOTICE:   reconnect timeout: 10s
> [2019/04/12 14:29:08:0936] NOTICE:  SSL ciphers: 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4:!HMAC_SHA1:!SHA1:!DHE-RSA-AES128-GCM-SHA256:!DHE-RSA-AES128-SHA256:!AES128-GCM-SH...
> [2019/04/12 14:29:08:0937] NOTICE:  Using SSL mode
> [2019/04/12 14:29:08:0941] ERR: lws_tls_server_vhost_backend_init: SSL_CTX_load_verify_locations unhappy
> [2019/04/12 14:29:08:0946] NOTICE:  SSL ECDH curve 'prime256v1'
> [2019/04/12 14:29:08:0948] NOTICE: created client ssl context for default
> [2019/04/12 14:29:08:0950] NOTICE:    vhost default: cert expiry: 88d
> 
>

**Comment by Zibri** [comment]
I just did a git clone then compiled libwesockets from it's repository.
The released binary works... something goes wrong (incompatible libraries?) when compiling on ubuntu server 18.04.2.

**Comment by tsl0922** [comment]
> ERR: lws_tls_server_vhost_backend_init: SSL_CTX_load_verify_locations unhappy

This can be safely ignored, did you try the https url with a browser?

**Comment by escalade** [comment]
Same issue here, tried with the latest libwebsockets master as well. Just displays "400" (I suppose it's a HTTP 400?).

**Comment by tsl0922** [comment]
@escalade ttyd will return a 400 code if the http request method is not GET.

**Comment by escalade** [comment]
I'm simply entering the address in a browser, which I assume will result in a GET request. Seeing as there is two reports about it here I think there might be an issue. It works fine without SSL enabled.

**Comment by tsl0922** [comment]
libwebsockets may enable http2 on the server side when ssl is on, but ttyd did not support it well.

Fixed on master.
