### ISSUE TITLE
Support for keyed hash authentication

### ISSUE THREAD

**Issue by vbence** [tsl0922/ttyd#171]
The current username-password scheme has the plaintext secret in configuration (visible for `ps` or `kubectl describe`).

An option would be nice to specify an adequately hashed password.

**Comment by Zibri** [comment]
I would like the same thing.
As of now I use this work-around:

ttyd ./dosh

where dosh is:
```
#!/bin/bash
echo -n "Password: "
read -sr p
[ "$(sha256sum <<<$p)" == "6b3a55e0261b0304143f805a24924d0c1c44524821305f31d9277843b8a10f4e  -" ] && ( clear;exec bash -i )
```
(in this example the password is "password")
the has includes the newline so to generate a hash just do:
```
read -r p
sha256sum <<<$p

```

**Comment by tsl0922** [comment]
> -a, --url-arg           Allow client to send command line arguments in URL (eg: http://localhost:7681?arg=foo&arg=bar)

You can always implement a custom authentication method with the url params.

Save the following script as `a.sh`, the run `ttyd -a /test.sh` (https://github.com/tsl0922/ttyd/issues/274#issuecomment-586854996)

```bash
#!/bin/bash
if [ "$#" -lt 1 ] || [ $1 != "secret" ] ; then
      echo "Access denied"
      exit 0
fi
echo "Start session, passed secret correct $1"
/bin/bash
```

**Comment by vbence** [comment]
I see it is possible to roll your own auth solution, but built-in support would be cleaner and arguably more secure (lots of small details can go wrong with authentication).

**Comment by Zibri** [comment]
> I see it is possible to roll your own auth solution, but built-in support would be cleaner and arguably more secure (lots of small details can go wrong with authentication).

I totally agree but in the meanwhile...

**Comment by Zibri** [comment]
@tsl0922 nope.. in my way the password is not exposed by the script.

**Comment by tsl0922** [comment]
With the [Auth Proxy](https://github.com/tsl0922/ttyd/wiki/Auth-Proxy) feature, this can be done via other web servers like apache now.

**Comment by vbence** [comment]
Thanks for the comment but that wont solve the problem when ppl have access to your pod ip. 

The original problem with plaintext password is that ppl with access to ps or kubectl will see it, if I could separate my host from untrusted parties I coul also use plaintext password.

**Comment by pre** [comment]
> Thanks for the comment but that wont solve the problem when ppl have access to your pod ip.
> 

Have apache as a sidecar for ttyd and provide the socket using an emptyDir volume mount. That way you won’t expose ttyd.
