### ISSUE TITLE
[bug] Browser spam refresh does not exit process

### ISSUE THREAD

**Issue by spichtjules** [tsl0922/ttyd#173]
Hello,

I was doing more tests & then i figured out that some commands that are sending "infinite data" can not be killed through CTRL+C on the web terminal

Is this a bug ?

**Comment by spichtjules** [comment]
It appears to break only on OSX not linux

**Comment by tsl0922** [comment]
Can not reproduce on my local machine (macOS 10.14.4, Chrome 74.0.3729.131, ttyd 1.4.4-fc4e06b), which version of ttyd are you use?

**Comment by spichtjules** [comment]
I'm using compiled ttyd version 1.4.4-1232a17,

But i figured out that if i spam the ctrl+c , then it's killing it 20s later anyway !

**But there's another issue** : 

i'm using a script with the command : "trap" to remove a docker container atfer user disconnects. But sometimes it does not exit properly if i spam page refresh on the browser.

`#!/usr/bin/env bash

set -euo pipefail

container=""

cmdline="sleep 3600"

function cleanup() {
    docker kill "${container}" > /dev/null
    docker rm -f "${container}" > /dev/null
}
trap cleanup EXIT

container=$(docker run -d ubuntu sh -c "${cmdline}")

if [[ -z "${container}" ]]; then
	echo "[VM] Failed to obtain container ID"
	exit 1
fi

docker exec -it "${container}" zsh

`
Sometimes the container is still present in `docker ps`command

Is that a known issue ?

**Comment by spichtjules** [comment]
![image](https://user-images.githubusercontent.com/33153894/57162952-18f81180-6df0-11e9-8897-89766bcd6ff6.png)

This is the docker ps output (on the bottom left) when i'm loading it slowly or doing an "exit" on the shell

**Comment by spichtjules** [comment]
Then there is the gif of the docker ps getting populated when i'm spamming the reload in the browser

(sorry for the bad quality)

(the docker ps output is bottom left)

https://giphy.com/gifs/lmpgJkfDNpdYZB5MoO/fullscreen

**Comment by tsl0922** [comment]
I don't think ttyd has the responsibility to end the docker container your script started as daemon. ttyd tries to end process by sending `SIGHUP` signal by default, you can change it to `SIGKILL` if needed.
