### ISSUE TITLE
Retry logic on initial websocket connection

### ISSUE THREAD

**Issue by cicavey** [tsl0922/ttyd#176]
There is auto reconnect logic after initial connection, but there is no retry on the initial connection. There may be environment/firewall issues where the intial connection can time out, have TLS handshake issues (mitm proxy), etc. The initial connection should attempt reconnection at reasonable interval ideally with exponential backoff.

**Comment by tsl0922** [comment]
fd29928a9c65195345e6794c4347c0a884d4e40d
