### ISSUE TITLE
Close ttyd if command returns

### ISSUE THREAD

**Issue by Freshdouble** [tsl0922/ttyd#179]
Is it possible to close ttyd when the executed programm returns?

I want to run ttyd as a interactive connection to a user service which is started by systemd. When the programm crashes or just returns systemd thinks it is still running, because ttyd ist still active.

Is there a simple solution for this problem?

**Comment by tsl0922** [comment]
You may want to try the `--once` option which makes ttyd only serves 1 connection and exit.

ttyd will start a new instance of the program for every new connection, so they won't affect each other.
