### ISSUE TITLE
How to disable 'reconnect'?

### ISSUE THREAD

**Issue by m2acgi** [tsl0922/ttyd#180]
I wanna to excute my script with ttyd, but it excute the script every 10s by default. So, how to disable auto reconnect but when I refresh the web browser ?

**Comment by tsl0922** [comment]
`--reconnect 0`

**Comment by m2acgi** [comment]
```
[root@test-centos7 ~]# ./ttyd_linux.x86_64 --reconnect 0 --readonly ./sample.sh
ttyd_linux.x86_64: invalid reconnect: 0
```

`--reconnect 0` not work in CentOS 7 x86_64.
