### ISSUE TITLE
net::ERR_CONTENT_LENGTH_MISMATCH error when specify the index.html parameter

### ISSUE THREAD

**Issue by shixiaobao17145** [tsl0922/ttyd#188]
If I run ttyd with -I index.html, when I visit localhost:7681, it will hold for a long time and throw this error in the console.

![content-length-error](https://user-images.githubusercontent.com/1640561/59329933-a77e7d80-8d22-11e9-8c83-8b682f7da61f.png)
![content-length](https://user-images.githubusercontent.com/1640561/59329935-a9484100-8d22-11e9-833d-03b74cfae4b2.png)

**Comment by tsl0922** [comment]
Maybe related to #189 , but the fix for it do not work for this issue.

The `lws_serve_http_file` method usage here do not work well with http keepalive.

**Comment by shixiaobao17145** [comment]
> Maybe related to #189 , but the fix for it do not work for this issue.
> 
> The `lws_serve_http_file` method usage here do not work well with http keepalive.

Thanks for replying on this, do we have any idea on how to make it work for --index parameter? 
From my perspective, it's only the auth_token.js request not work properly as the content length incorrect, I'm not good at C++ lang, but I think maybe someone can debug on this line to see if there's any corner case happen here when specified --index parameter: https://github.com/tsl0922/ttyd/blob/master/src/http.c#L94

Thanks again!

**Comment by tsl0922** [comment]
Fixed on master.

**Comment by shixiaobao17145** [comment]
> Fixed on master.

AWESOME！ Could you please update the version number to the latest 1.5.0 to ALPINEBUILD file as we probably want to use it on Docker.  Many thanks!!
