### ISSUE TITLE
How can i pass input into a readonly daemon?

### ISSUE THREAD

**Issue by laggardkernel** [tsl0922/ttyd#190]
Is there any way to pass input into a readonly daemon.

I tried to use netcat and connection succeeded, but the display didn't update the output.

```bash
ttyd -R -c user:passwd nc -l -p 20000 -e "/bin/bash -il"

# connect from local machine
nc 127.0.0.1 20000 -v
```

**Comment by tsl0922** [comment]
I don't think you can do it, ttyd will drop any input if started with readonly option.

**Comment by laggardkernel** [comment]
@tsl0922 So what's the point of the readonly mode. Open a terminal and let people look at the blank screen?

**Comment by tsl0922** [comment]
readonly means user can not write to the pty session, so the output will still be displayed on the screen.

**Comment by laggardkernel** [comment]
I guess it means readonly mode is used for some command output but not for displaying output of an interactive shell? Cause there's no way to pass input into a readonly interactive shell.

**Comment by b0o** [comment]
@tsl0922 I was hoping readonly mode would allow the originating terminal to control the tty, while the web interface would essentially mirror it.

**Comment by tsl0922** [comment]
@b0o you can use tmux to do it, please read the readme:

https://github.com/tsl0922/ttyd#example-usage
