### ISSUE TITLE
Mobile Browser Layout

### ISSUE THREAD

**Issue by BiatuAutMiahn** [tsl0922/ttyd#191]
When using the mobile brownser like chrome on android, the terminal scaling is off, it terminal overflows off screen and you cannot scroll. I think the solution would be to resize the terminal when you tap to type and the screen zooms in. Or handle the term size by the DPI when the page loads.

Thank you

**Comment by tsl0922** [comment]
I didn't test ttyd under mobile browsers, you may want to check this upstream issue: #1101.

**Comment by BiatuAutMiahn** [comment]
This may be a redundant issue, let me test with latest commit

**Comment by BiatuAutMiahn** [comment]
just verified, the screen on my S9+ is 1440x2960, so the terminal starts out with rather small print. It's fine once I tap to type, however xterm basically just zooms in instead of resizing the terminal with a higher DPI

**Comment by BiatuAutMiahn** [comment]
I also notice an issue where, on the desktop browser, if my script prints too many newlines \n, it will make the cursor go offscreen and the only way to fix is to clear screen

**Comment by DUOLabs333** [comment]
The issue was closed on October 11, but the layout still looks wrong on phones.
