### ISSUE TITLE
Implement Escape Codes That Trigger Callback

### ISSUE THREAD

**Issue by BiatuAutMiahn** [tsl0922/ttyd#197]
Such as an escape code that will open a new tab?

[https://github.com/xtermjs/xterm.js/issues/2271](https://github.com/xtermjs/xterm.js/issues/2271)

**Comment by tsl0922** [comment]
I don't understand, what tab? browser or terminal?

**Comment by BiatuAutMiahn** [comment]
Browser

**Comment by BiatuAutMiahn** [comment]
In this instance, I just implemented a feature in my python script that...if a specific argument is passed by ttyd, my script will perform an alternate action. Now if I have the script exit, ttyd will just reconnect after some time causing that action to be run again which can be a problem. If I have the script just drop back to normal mode, and for whatever reason the browser decides to reload that tab (ie: Mobile Browser) That action is run again. 

With that said, having the ability to close the window or browser tab...or navigate to a new url without the argument.

**Comment by tsl0922** [comment]
> Now if I have the script exit, ttyd will just reconnect after some time causing that action to be run again which can be a problem

ttyd won't reconnect if your script exit with zero.

If you really want to implement escape codes that trigger callback,  put  ttyd into an iframe page, and use the iframe's `window.term` to call xterm apis.
