### ISSUE TITLE
Hello,Does the binaries support ipv6?

### ISSUE THREAD

**Issue by flyqieqq** [tsl0922/ttyd#202]
I tried using binaries and added -6 but always showed ipv6 off, I am sure my server has ipv6 address

**Comment by tsl0922** [comment]
No. The libwebsockets library is not compiled with ipv6 support.

**Comment by flyqieqq** [comment]
So how can I compile to get ipv6 support? Thank.

**Comment by flyqieqq** [comment]
So how can I compile to get ipv6 support? Thank.

**Comment by SuperSandro2000** [comment]
> So how can I compile to get ipv6 support? I saw that someone seems to have compiled ipv6. Thank.

Just put it behind a reverse proxy that supports ipv6

**Comment by tsl0922** [comment]
@flyqieqq if the libwebsockets library is compiled with ipv6 support (not enabled by default), then ttyd should works with ipv6 too, please take a look at this commit: 243a9b47faa08ab4967c3722a2765079079f8364.

**Comment by tsl0922** [comment]
Try the binaries below (compiled from master):

[ttyd_master_linux.tar.gz](https://github.com/tsl0922/ttyd/files/3412899/ttyd_master_linux.tar.gz)
