### ISSUE TITLE
execvp fails when combining client-option and check origin

### ISSUE THREAD

**Issue by SuperSandro2000** [tsl0922/ttyd#203]
I am on the latest commit in master (243a9b47faa08ab4967c3722a2765079079f8364).
When I combine ``--client-option 'theme={"background": "black"}'`` and ``--check-origin`` I get a flashing loop of this:

![image](https://user-images.githubusercontent.com/7258858/61694098-193de400-ad31-11e9-9926-039a30020037.png)

I hope this is enough to fix this bug.

BTW how does ``--check-origin`` work? Can I supply it the domain of my reverse proxy to check for?

**Comment by SuperSandro2000** [comment]
Changing the theme arg to ``--client-option='theme={"background": "black"}'`` fixes the problem, too.

I think this needs better error handling and maybe the help should mark where and how you can supply args. Right now it is quite hard to know how and what you can and should supply.

**Comment by tsl0922** [comment]
I've fixed this issue on master(e0745132462b36f3296c67f71f9ce6c198dd6b24), you can use `-t 'theme={"background": "black"}'` on old ttyd versions.

**Comment by tsl0922** [comment]
> BTW how does --check-origin work? Can I supply it the domain of my reverse proxy to check for?

It's a boolean flag. when enabled, ttyd will check if the HTTP `Origin` and `Host` header matches.

**Comment by SuperSandro2000** [comment]
Oh, finally the flag works like it should! Thanks!
Only issue I found is that when I accidentally supply ``--client-option='theme={"background": "black"}'`` ttyd freezes with no output.

**Comment by BennettDixon** [comment]
I have this issue running with different containers as my base image in my dockerfile. I can post more info if requested, but I can confirm switching all instances of `--option value` to `--option=value` fixed my problem as well.
