### ISSUE TITLE
ttyd crashes on fresh termux installation

### ISSUE THREAD

**Issue by ongspxm** [tsl0922/ttyd#214]
![image](https://user-images.githubusercontent.com/1430854/63247834-a2800200-c26e-11e9-8064-9dd4ebccc0ed.png)

it seems like libwebsocket is the one causing the error, but the weird thing is that every time i run it, the erroneous group name seem to differ.

any tips on how i go about fixing this? i tried uninstalling termux already. this is a fresh installation

**Comment by araczkowski** [comment]
I noticed similar problem 
ttyd 1.5.2 (libwebsockets 3.1.0)

in console:
`
**$ ttyd -p 8080 bash**

[2019/08/20 09:03:36:4987] N: ttyd 1.5.2 (libwebsockets 3.1.0)
[2019/08/20 09:03:36:4988] N: tty configuration:
[2019/08/20 09:03:36:4989] N:   start command: bash
[2019/08/20 09:03:36:4989] N:   close signal: SIGHUP (1)
[2019/08/20 09:03:36:4989] N:   terminal type: xterm-256color
Segmentation fault

**logcat**

08-20 09:04:53.607 24411 24411 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4 in tid 24411 (ttyd), pid 24411 (ttyd)
08-20 09:04:53.596 24413 24413 W crash_dump32: type=1400 audit(0.0:645): avc: denied { read write } for path="/dev/pts/2" dev="devpts" ino=5 scontext=u:r:crash_dump:s0:c512,c768 tcontext=u:object_r:untrusted_app_all_devpts:s0:c512,c768 tclass=chr_file permissive=0
08-20 09:04:53.626 24414 24414 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
08-20 09:04:53.627 24414 24414 I crash_dump32: performing dump of process 24411 (target tid = 24411)
08-20 09:04:53.629 24414 24414 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-20 09:04:53.629 24414 24414 F DEBUG   : Build fingerprint: 'xiaomi/tissot/tissot_sprout:9/PKQ1.180917.001/V10.0.11.0.PDHMIXM:user/release-keys'
08-20 09:04:53.629 24414 24414 F DEBUG   : Revision: '0'
08-20 09:04:53.629 24414 24414 F DEBUG   : ABI: 'arm'
08-20 09:04:53.629 24414 24414 F DEBUG   : pid: 24411, tid: 24411, name: ttyd  >>> ttyd <<<
08-20 09:04:53.629 24414 24414 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4
08-20 09:04:53.629 24414 24414 F DEBUG   : Cause: null pointer dereference
08-20 09:04:53.629 24414 24414 F DEBUG   :     r0  f4eba998  r1  00000004  r2  65640073  r3  0000269c
08-20 09:04:53.629 24414 24414 F DEBUG   :     r4  00000000  r5  00000004  r6  f4eba996  r7  f4ec8f18
08-20 09:04:53.629 24414 24414 F DEBUG   :     r8  f4ec8ff8  r9  f4ecb3cc  r10 f501967c  r11 f4853000
08-20 09:04:53.629 24414 24414 F DEBUG   :     ip  00000000  sp  fff93470  lr  f4e31ce5  pc  f4e2b98c
08-20 09:04:53.631 24414 24414 I unwind  : Malformed section header found, ignoring...
08-20 09:04:53.631 24414 24414 F DEBUG   : 
08-20 09:04:53.631 24414 24414 F DEBUG   : backtrace:
08-20 09:04:53.631 24414 24414 F DEBUG   :     00 pc 0001a98c  /system/lib/libc.so (strcmp+132)
08-20 09:04:53.631 24414 24414 F DEBUG   :     01 pc 00020ce1  /system/lib/libc.so (getgrnam_internal(char const*, group_state_t*)+44)
08-20 09:04:53.631 24414 24414 F DEBUG   :     02 pc 00001d67  /data/data/com.termux/files/usr/bin/ttyd
08-20 09:04:53.635 24414 24414 I unwind  : Malformed section header found, ignoring...
08-20 09:04:53.642 24414 24414 E crash_dump32: AM data write failed: Broken pipe
`

**Comment by araczkowski** [comment]
it is related to the libwebsockets 3.2.0
I just compiled version 3.1.0 and it works ok

`
**$ ttyd -p 8080 bash**
[2019/08/20 09:31:33:9255] NOTICE: ttyd 1.5.2 (**libwebsockets 3.1.0**)
[2019/08/20 09:31:33:9257] NOTICE: tty configuration:
[2019/08/20 09:31:33:9257] NOTICE:   start command: bash
[2019/08/20 09:31:33:9258] NOTICE:   close signal: SIGHUP (1)
[2019/08/20 09:31:33:9258] NOTICE:   terminal type: xterm-256color
[2019/08/20 09:31:33:9261] NOTICE: Creating Vhost 'default' port 8080, 2 protocols, IPv6 off
[2019/08/20 09:33:14:3065] NOTICE: HTTP / - 192.168.6.52 (192.168.6.52)
[2019/08/20 09:33:14:3412] NOTICE: HTTP /auth_token.js - 192.168.6.52 (192.168.6.52)
[2019/08/20 09:33:14:3777] NOTICE: WS   /ws - 192.168.6.52 (192.168.6.52), clients: 1
[2019/08/20 09:33:14:6124] NOTICE: started process, pid: 24920

`

**Comment by tsl0922** [comment]
I don't have an android device to test it on termux. Thanks @araczkowski 👍 .

**Comment by hedifezai** [comment]
same thing here. Did you manage to solve it ?
