### ISSUE TITLE
Typing not working in Safari

### ISSUE THREAD

**Issue by shixiaobao17145** [tsl0922/ttyd#215]
It's not working in Safari when you're trying to type commands in the terminal, only `Enter` works.

Here is the environment info:
OS: Mac OSX 
Safari: Version 12.1.1 (14607.2.6.1.1)
ttyd: version 1.5.0

**Comment by tsl0922** [comment]
I don't think it's ttyd's issue if `Enter` works, check your program.

**Comment by shixiaobao17145** [comment]
> I don't think it's ttyd's issue if `Enter` works, check your program.

see: https://github.com/tsl0922/ttyd/issues/82#issuecomment-372600121

This guy said it's possible to happen like so, I'm not sure what's the reason, but it works on other versions of safari, I've tried.
