### ISSUE TITLE
ttyd not work on Edge as it's using TextEncoder

### ISSUE THREAD

**Issue by shixiaobao17145** [tsl0922/ttyd#217]
it's not working in Edge, as TextEncoder is not supported on Edge & IE, https://caniuse.com/#search=textencoder

**Comment by SuperSandro2000** [comment]
Use the new edge beta based on chromium.

**Comment by tsl0922** [comment]
The Polyfill for TextEncoder is removed from ttyd since 1.5.0, ie11/edge is not supported anymore.
