### ISSUE TITLE
X10 mouse support?

### ISSUE THREAD

**Issue by klamonte** [tsl0922/ttyd#218]
Hello, I am trying to use ttyd with [Jexer](https://gitlab.com/klamonte/jexer) .  Mouse clicks are not working, and mouse drags appear to be copy-to-clipboard rather than xterm anyevent/buttonevent tracking.

Is there a flag to enable xterm/X10 mouse support with ttyd?

**Comment by tsl0922** [comment]
This a an upstream issue, I've updated xterm.js on the master branch, it should works now.
