### ISSUE TITLE
Terminate session after a defined time

### ISSUE THREAD

**Issue by ediardo** [tsl0922/ttyd#220]
Hi,

First I want to thank you for creating and maintaining this project.

I have `ttyd` running on small server with very limited resources, creating a new container for each client using the command `ttyd docker run -it --rm ubuntu` and it works great.

However, the session and the container keep running as long as the user does not close the browser (as expected). It'd be very useful if those sessions (and their containers) can be terminated after a fixed period of time, e.g. 5 minutes. Is there any known method to achieve this?

Eddie

**Comment by tsl0922** [comment]
It's possible to implement it outside of ttyd, you can use a shell script to call the docker run command and terminate it in it after a defined time.

**Comment by ediardo** [comment]
Thank you @tsl0922 . I'll share the solution here when its ready.
