### ISSUE TITLE
slow performance problem

### ISSUE THREAD

**Issue by ideal** [tsl0922/ttyd#223]
Start with `sudo ttyd -p 80 bash`.
With libwebsockets 3.2.0, ttyd 1.5.2-fa09895.
In browser with access to localhost, seems that somewhere stucked after typing, with `strace` I found it still poll for POLLIN on network connection fd (here it is 9), and after timeout (1 second here), it begin to send result. Have not figure out it is because of libwebsockets or something else, but I think  it is probably because of it.

![image](https://user-images.githubusercontent.com/261698/64321374-ff134900-cff2-11e9-80ad-e233b257ba62.png)

**Comment by tsl0922** [comment]
libwebsockets 3.2.0 may changed something internally, I didn't test it yet, you may want to use the 3.1.0 version.

**Comment by ideal** [comment]
Please check https://github.com/tsl0922/ttyd/pull/233
