### ISSUE TITLE
ssl does not work for 1.5.2 release

### ISSUE THREAD

**Issue by xunpan** [tsl0922/ttyd#226]
The generated crt/key works for `GoTTY` based on my test (import my own CA.crt in Firefox). So, I think it should not have any issue.

It failed in ttyd for below case:
1. start `ttyd` 1.5.2 version release on a host
`ttyd --ssl --ssl-cert xxx.crt --ssl-key xxx.key top`
2. use `Firefox` and web debug
  - `Firefox` has nothing showed.
  - `Firefox` shows succeed in getting `/` and `auth_token.js`. But `GET` failed for `ws`:
```
请求网址:https://xxx/ws
请求方法:GET
```
3. The `ttyd` log shows:
The log shows:
```
[2019/09/05 23:27:32:6654] WARN: refuse to serve WS client for illegal ws path:
```

cc @tsl0922

**Comment by tsl0922** [comment]
If ttyd can't verify if the websocket request path is `/ws`, it will refuse to serve the websocket connection and close it.

https://github.com/tsl0922/ttyd/blob/1.5.2/src/protocol.c#L256-L259

I can reproduce it on my machine, but not sure if it is a libwebsockets issue, it works on chrome with ssl enabled.  Commenting out the code above will suppress this check,  should make it work on firefox.

**Comment by moralrebuild** [comment]
hit the same issue on openwrt 19.07.1

logread -e ttyd
```
Thu Feb 27 15:06:45 2020 daemon.err ttyd[5331]: [2020/02/27 15:06:45:1447] NOTICE: HTTP /auth_token.js -  ()
Thu Feb 27 15:06:55 2020 daemon.err ttyd[5331]: [2020/02/27 15:06:55:5997] WARN: refuse to serve WS client for illegal ws path:
Thu Feb 27 15:06:55 2020 daemon.err ttyd[5331]: [2020/02/27 15:06:55:6000] WARN: User code denied connection
```

opkg info ttyd
```
Package: ttyd
Version: 1.5.2-1
Depends: libc, libopenssl1.1, libjson-c2, libpthread, libwebsockets-full
Status: install user installed
Architecture: mipsel_24kc
Installed-Time: 1580313935
```

**Comment by ammarfaizi2** [comment]
Same issue here Ubuntu 20.04
```
Jun 05 08:48:16 esteh ttyd[2111]: [2020/06/05 08:48:16:6171] N: HTTP /token - xxx.xxx.xxx.xxx
Jun 05 08:48:34 esteh ttyd[2111]: [2020/06/05 08:48:34:7930] W: refuse to serve WS client for illegal ws path:
Jun 05 08:48:34 esteh ttyd[2111]: [2020/06/05 08:48:34:7931] W: User code denied connection
```

Version info
```
root@esteh:~# ttyd --version
ttyd version 1.6.0-1786570
```

**Comment by mirtouf** [comment]
I confirm the issue on openwrt 19.07.3 with ttyd 1.5.2 and firefox.
chromium-based web browsers are not affected.

**Comment by tsl0922** [comment]
Should be fixed on master now.

Firefox may uses http2 to connect, ttyd will get empty request path with `WSI_TOKEN_GET_URI`, now `WSI_TOKEN_HTTP_COLON_PATH` is also checked if http2 is enabled.
