### ISSUE TITLE
auth_token.js should be injected inside the index.html

### ISSUE THREAD

**Issue by trash-anger** [tsl0922/ttyd#236]
Hi !

I built reverse-proxy to redirect authenticated users to the right ttyd based on their jwt token on a k8s cluster.
But unfortunately, the fact that auth_token.js is not inside the index cause issues...

![image](https://user-images.githubusercontent.com/7171011/65209366-e6307c00-da65-11e9-9095-91328d1d265c.png)

I have no C skills, but would it be possible to serve it directly inside the index rather than beside ?

**Comment by tsl0922** [comment]
Yes, I think so 👍 . It comes from gotty (ttyd was initially ported from gotty).

If you don't use ttyd's basic auth feature(`--credential`), auth_token.js can be ignored safely.

**Comment by tsl0922** [comment]
Fixed on master.
