### ISSUE TITLE
initiate a file download?

### ISSUE THREAD

**Issue by cdr8H** [tsl0922/ttyd#238]
Hi,

is there any chance to have the client browser start a download? f.ex. outputting 

_```
Content-Type:application/x-download
Content-Disposition:attachment;filename=TEST.pdf
$$MY_BINARY_DATA_OUTPUT$$
```_

**Comment by tsl0922** [comment]
If you want to send a file from the server, then yes: install lrzsz and run `sz test.pdf`. otherwise, no.

**Comment by cdr8H** [comment]
Great - that works fine. Thx for your input!
