### ISSUE TITLE
zmodem troubles in 1.5.2

### ISSUE THREAD

**Issue by cdr8H** [tsl0922/ttyd#239]
when using Debian Buster sz command (0.12.21rc), the file will be received by the clients browser (Firefox as well as Chrome), but javascript throws an error:

_(index):1 [ttyd] zmodem consume:  PROTOCOL: Only thing after ZFIN should be “OO” (79,79), not: 99,100,114,64,115,49,58,126,36,32
handleError @ (index):1
consume @ (index):1
onSocketData @ (index):1_

This behaviour occurs inconsistently - sometimes after a fresh browser start, the first zmodem receive trial is successfull, but only the first one per session.

The session hangs because a input typed will stuck here:

`do{t=this._next_subpacket_handler?this._parse_and_consume_subpacket()....`

**Comment by cdr8H** [comment]
follow up ....

the javascript zmodem implementation seems to see the shell prompt sent from ttypd as part of the data transfered. 99,100,114,64,115,49,58,126,36,32 = my bash prompt "cdr@s1~$ "

when setting the bash prompt (PS1) = "OO" everything is fine ;-)  but that is an ugly hack.

The docs for zmodem says:

_Session Cleanup The sender closes the session with a ZFIN header. The receiver acknowledges this with its own ZFIN header. When the sender receives the acknowledging header, it sends two characters, "OO" (Over and Out) and exits to the operating system or application that invoked it. The receiver waits briefly for the "O" characters, then exits whether they were received or not._ 

Better workaround:

```
#!/bin/bash

[ ! -r $1 ] || [ -z "$1" ] && exit 1

sz $1 
echo -en "OO"
```

**Comment by tsl0922** [comment]
Can't reproduce, glad that you resolves it yourself 👍 .
