### ISSUE TITLE
要是能在最顶部加个工具栏，管理ssh 连接，快速连接到某台服务器的功能，那就太棒了

### ISSUE THREAD

**Issue by zhangjingl02** [tsl0922/ttyd#24]
要是能在最顶部加个工具栏，管理ssh 连接，快速连接到某台服务器的功能，那就太棒了

**Comment by tsl0922** [comment]
ttyd 不是 ssh 客户端，它只是转发 tty 到网页上。

你说的功能理论上来说是可以实现的：只需要 ttyd 支持通过网页 URL 参数自定义启动命令，启动命令可以是 `ssh user@host`，这样就通过 ttyd 服务器做跳板连接到另一台机器了。

**Comment by tsl0922** [comment]
可以考虑支持通过 url 接收一个启动命令参数，已创建 issue：#25。

**Comment by zhangjingl02** [comment]
太好了

**Comment by botwinter** [comment]
Hi, I have implemented a similar feature to allow client to specify the command and arguments: https://github.com/botwinter/ttyd.

Example URL is:
http://localhost:7681?command=/bin/login&arg1=-f&arg2=bob

--

您好，我实现了类似的功能，以允许客户端指定命令和参数：https://github.com/botwinter/ttyd

示例url是：
http://localhost:7681?command=/bin/login&arg1=-f&arg2=bob
