### ISSUE TITLE
use with. mainframe

### ISSUE THREAD

**Issue by atrebbi** [tsl0922/ttyd#241]
I'm trying to use ttyd for a mainframe ; the main problem is that the terminal size (rows and cols) should be fixed , no fitting ( or better , a fit that should be and aspect fit changing font size )
I wanted to achieve this with some changes to html / css , but could not find how to do this; there are some standard resolutions to admit (8o or 132 columns, and some related values for rows) but this should be an initial option , without further changes
Any simple way to do or I should modify code ?

**Comment by tsl0922** [comment]
The terminal size can't be changed, it's force resized when window size changes, but font size can be changed via initial option like: `ttyd -t 'fontSize=30' bash`

**Comment by atrebbi** [comment]
i have used --index option at last, and created a custom index.html ; I have noticed that each time I open the page, a different device is used and , as I have configured only 6 devices, after 6 times I get an error; I think that maybe the problem is with signal option, I think I should not close the session but let it expire naturally (so the question is: how to disable the 1, SIGHUP that is sent when I close the page? the -s option is not well documented; btw, this is the page I have created: https://mainframe.3bsoft.com , the error you can seee is the devices have been used (or, better, were not correctly released)

**Comment by tsl0922** [comment]
> how to disable the 1, SIGHUP that is sent when I close the page? 

you can't disable it, it's always sent to cleanup process since a process is created for every request.

**Comment by atrebbi** [comment]
ok, I have found (and fixed):
I called a docker command on shell , it seems that the process on docker was never terminated ;

another question:
on window resize, I change the font size of terminal: I get the container size and calculate a fontSize , but the calc does not seem accurate...

var fontSize = Math.trunc(container.clientWidth * 1.8 / 8.0) / 10.0; 

the terminal is sometimes larger or smaller than the desired viewport

the fontFamily is 'Glass_TTY_VT220', monospaced , 80 column and 32 rows (I had calculated 800x608 for 18.0 fontSize , that is 10 pixel width each character, and scale font )

cfr:
https://mainframe.3bsoft.com
(try and resize browser window, font changes but does not fit precisely)

**Comment by tsl0922** [comment]
> another question:
> on window resize, I change the font size of terminal: I get the container size and calculate a fontSize , but the calc does not seem accurate...

It should be an upstream issue, please report it to https://github.com/xtermjs/xterm.js
