### ISSUE TITLE
'makepkg' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by xeroxstar** [tsl0922/ttyd#242]
**I am getting this error:**

```
C:\Users\user>makepkg <- not working
'makepkg' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\user>pacman <- works
error: no operation specified (use -h for help)
```

I have installed the path in the environment variables on windows in advanced system `"C:\msys64\usr\bin"` and makepkg still not working, maybe i am missing something?

**Comment by xeroxstar** [comment]
I guess i have to run commands with the msys2 console and not with native window console, anyway, when i run this command in my folder `makepkg -s && pacman -U *.pkg.tar.xz` it gives me an error:
`==> ERROR: PKGBUILD does not exist.` What package should i put in my dir folder?

**Comment by tsl0922** [comment]
Yes, it should be run with the msys2 console.

> ERROR: PKGBUILD contains CRLF characters and cannot be sourced

It works on my machine. I can confirm the PKGBUILD files in this repo do not contains CRLF characters, check your local environment.

**Comment by SuperSandro2000** [comment]
You want to turn of autocrlf. See https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings#global-settings-for-line-endings

**Comment by xeroxstar** [comment]
Yes, it's should run in msys console and not on windows console, took me a while to figure out how everything works... anyway, thank :)
