### ISSUE TITLE
Build in Win7 use msys2 get error

### ISSUE THREAD

**Issue by comicer424** [tsl0922/ttyd#244]
![image](https://user-images.githubusercontent.com/16798656/68295114-9f0d5180-00cc-11ea-8895-2d8752808099.png)

how can I fix?

**Comment by SuperSandro2000** [comment]
You are missing libc-dev

**Comment by comicer424** [comment]
how can i get libc-dev in msys2
pacman -F ioctl.h can find it
![image](https://user-images.githubusercontent.com/16798656/68356297-de7b8280-014c-11ea-9712-bf64b4f6f659.png)

**Comment by tsl0922** [comment]
How do you start the terminal? ttyd only compiles with msys2 (based on cygwin), not mingw.

**Comment by comicer424** [comment]
> How do you start the terminal? ttyd only compiles with msys2 (based on cygwin), not mingw.

Thanks I use old version msys2 build win32bit success。
![image](https://user-images.githubusercontent.com/16798656/68368372-e5b58700-0172-11ea-8655-bf6b3a9a73dc.png)

follow the readme 
`pacman -S mingw-w64-i686-cmake
`
no need

and depends is like up image
