### ISSUE TITLE
Build failure with Homebrew on Linux

### ISSUE THREAD

**Issue by dawidd6** [tsl0922/ttyd#248]
Hello there,

I'm trying to build this project for Homebrew on Linux and I'm getting this output:
https://gist.github.com/dawidd6/9d543b0497edf922bc82d65918d8807a

https://github.com/Homebrew/linuxbrew-core/pull/17644

At this point I'm out of ideas how to solve this.

**Comment by tsl0922** [comment]
> /usr/bin/ld: /home/linuxbrew/.linuxbrew/lib/libwebsockets.a(unix-plugins.c.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'

can you verify the installed libwebsockets works?

**Comment by dawidd6** [comment]
Yes, it works, just tested a compilation of simple program with `brew test libwebsockets`.

I think the issue here is that `ld` wants to link against static build of `libwebsockets` which is undesirable, cause we provide the shared library too.

**Comment by tsl0922** [comment]
I have no idea, it works on homebrew and compile/apt-get installed libwebsockets.

The [LIBWEBSOCKETS_LIBRARIES](https://github.com/warmcat/libwebsockets/blob/v3.2.0/cmake/LibwebsocketsConfig.cmake.in#L16) is set to `websockets websockets_shared`, which will make it always link against static lib first, not sure if it matters.

**Comment by dawidd6** [comment]
I think it might be it. Any ideas how to reverse the order without patching sources?

**Comment by dawidd6** [comment]
Fixed the issue with this hack:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 4929624..9dd0ea2 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -33,13 +33,13 @@ set(LIBWEBSOCKETS_MIN_VERSION 1.7.0)
 set(SOURCE_FILES src/server.c src/http.c src/protocol.c src/utils.c)
 
 find_package(OpenSSL REQUIRED)
-find_package(Libwebsockets ${LIBWEBSOCKETS_MIN_VERSION} QUIET)
+#find_package(Libwebsockets ${LIBWEBSOCKETS_MIN_VERSION} QUIET)
 
 find_package(PkgConfig)
 
-if(Libwebsockets_FOUND)
-    set(LIBWEBSOCKETS_INCLUDE_DIR ${LIBWEBSOCKETS_INCLUDE_DIR} ${LIBWEBSOCKETS_INCLUDE_DIRS})
-else() # try to find libwebsockets with pkg-config
+#if(Libwebsockets_FOUND)
+#    set(LIBWEBSOCKETS_INCLUDE_DIR ${LIBWEBSOCKETS_INCLUDE_DIR} ${LIBWEBSOCKETS_INCLUDE_DIRS})
+#else() # try to find libwebsockets with pkg-config
     pkg_check_modules(Libwebsockets REQUIRED libwebsockets>=${LIBWEBSOCKETS_MIN_VERSION})
     find_path(LIBWEBSOCKETS_INCLUDE_DIR libwebsockets.h
             HINTS ${LIBWEBSOCKETS_INCLUDEDIR} ${LIBWEBSOCKETS_INCLUDE_DIRS})
@@ -48,7 +48,7 @@ else() # try to find libwebsockets with pkg-config
     include(FindPackageHandleStandardArgs)
     find_package_handle_standard_args(LIBWEBSOCKETS DEFAULT_MSG LIBWEBSOCKETS_LIBRARIES LIBWEBSOCKETS_INCLUDE_DIR)
     mark_as_advanced(LIBWEBSOCKETS_INCLUDE_DIR LIBWEBSOCKETS_LIBRARIES)
-endif()
+#endif()
 
 pkg_check_modules(PC_JSON-C REQUIRED json-c)
 find_path(JSON-C_INCLUDE_DIR json.h
```
