### ISSUE TITLE
openwrt修改后台管理ip之后无法连接

### ISSUE THREAD

**Issue by alvinxhc** [tsl0922/ttyd#252]
openwrt修改后台管理ip之后无法连接，比如编译的时候使用的是192.168.1.1，刷机使用之后改成192.168.2.1或者其他ip，TTYD终端就会显示无法连接，请教一下要如何解决

**Comment by tsl0922** [comment]
这个没办法，目前 openwrt 上启动的时候应该是监听 ip 而不是网卡的，只能重启 ttyd 或者直接重启路由器。。
