### ISSUE TITLE
Blank lines at the bottom of the terminal

### ISSUE THREAD

**Issue by Akarys42** [tsl0922/ttyd#254]
Hi, I wanted to use TTYD on my server and connect on my iPad. The problem is that the virtual keyboard is in the way, and I can’t scroll down the terminal. Is it possible to add some blank lines at the end, so I can easily scroll it. 

I’m on a RPI 4B and Ubuntu Server ARM

**Comment by tsl0922** [comment]
I tested it on my iPad, it works well.

**Comment by Akarys42** [comment]
Here is what I mean : 
If I run a lot of command (`cat .bash_history` for example), the terminal will look like this : 
![6ECB8568-3640-4C5C-B0B1-6CADCDA102E8](https://user-images.githubusercontent.com/44778521/70797174-3dfc2c00-1da4-11ea-91f3-385c944a02ce.png)

But now if I try to write a new command, the keyboard is in the way : 
![18AA462D-2D58-45E1-82B3-B92EDCA830E3](https://user-images.githubusercontent.com/44778521/70797207-53715600-1da4-11ea-8e11-487b8931c1d9.png)

**Comment by tsl0922** [comment]
It should be an upstream issue, please report to the [xterm.js](https://github.com/xtermjs/xterm.js) project.
