### ISSUE TITLE
custom key shortcut, ctrl+v for paste specifically

### ISSUE THREAD

**Issue by xhebox** [tsl0922/ttyd#258]
I'd like to see an option to use ctrl+v for paste. It's not so hard to modify that html file though.

Or even further, give a chance to load an external js file, which can access the xterm.js instance. Such that, customization can be done by this js file, most of the time.

**Comment by tsl0922** [comment]
I'm not going to add such functionality, you can always edit the frontend code under the `html` folder and build your own version of ttyd.
