### ISSUE TITLE
Fit ttyd terminal to size of containing element

### ISSUE THREAD

**Issue by ccp-codex** [tsl0922/ttyd#259]
I'd like fit a terminal with a fixed 80x24 size to a containing element on a web-page and allow the user to resize the terminal font using ctrl-+/ctrl-- along with other features.

It seems there's an xterm.js addon that provides the fitting feature but I'm uncertain of how I would process to modify ttyd to achieve this effect. Would I need to custom build ttyd, modifying xtermjs with the fitting addon and updating the default index.html or is there a quicker route to success?

Thanks in advance for any help / guidance you can provide. 

https://www.npmjs.com/package/xterm-addon-fit

**Comment by tsl0922** [comment]
Yes you need a custom build.

ttyd resizes the terminal on window resizing, the code that call the xterm fit addon:

https://github.com/tsl0922/ttyd/blob/master/html/src/components/terminal/index.tsx#L109

Add your logic and compile it, then use it with the `--index` option, or build your own version of ttyd with the modified index.html.
