### ISSUE TITLE
CORS Support for HTTP OPTIONS

### ISSUE THREAD

**Issue by FossilBlade** [tsl0922/ttyd#261]
Hi, 

I really like this project (Thanks a ton for creating this) and have been using it for sometime by directly accessing it from the browser.

However when trying to access it thru angular via httpclient, its always giving access denied. I have investigated and found that the HTTP OPTIONS request method is also under authentication and it fails for Chrome's Pre-Flight request, as this request doesn't sent the authorization header which has been passed to the GET request. 

**Can you please remove authentication for HTTP OPTIONS request and respond back with a HTTP Status code of 200 and a Allow header indicating the operations that are permitted on this resource. eg: Allow: HEAD,GET,OPTIONS**

 The [CORS spec] (https://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0) which says "for a cross-origin request with preflight … make a preflight request … Exclude user credentials".
 
I would have done a PR myself but i am not well versed with C.

Screenshot of the Chrome Tools:
![image](https://user-images.githubusercontent.com/32032862/72134283-7feeb100-33e8-11ea-819d-057211861c9c.png)

Screenshot of Curl:
![image](https://user-images.githubusercontent.com/32032862/72134475-14f1aa00-33e9-11ea-9614-d33132052a9d.png)

**Comment by tsl0922** [comment]
I don't think this is a feature that ttyd should implement, can't get your use case.

Anyway, you can always add the CORS header via nginx proxy.
