### ISSUE TITLE
Passing HTTP args to Docker via 'ttyd docker' command  (is it possible?)

### ISSUE THREAD

**Issue by sahuguet** [tsl0922/ttyd#265]
Hi,

big fan of the tool. Here is a question I have.

I am trying to have a web front-end for a bunch of users.
And I want each user will have their own "personalized" Docker, eithera different image or the same image but initialized differently.

With the `ttyd docker`, you can spawn the same image for each user.
Is there a way to spawn a different image (e.g. based on url params or HTTP header) and/or a way of passing extra parameters to the docker?

Arnaud

**Comment by tsl0922** [comment]
It's possible, the `--url-arg` option should work for you, replace the docker command with a shell script to call it (and handle the command line arguments from url args).
