### ISSUE TITLE
is ttyd the right tool for my remote managment scenario, when SSH is block on my machine

### ISSUE THREAD

**Issue by PackElend** [tsl0922/ttyd#267]
Hello,
it took me some time to find apps to enable me to share a shell in a browser.

Me and friend managing some simple VPSs that shall be managed from a central management server to simplify workflow.
There are cases that we still need a shell and allowing us to share this session would be extremely helpful. 
In addition, when I'm at work, SSH is blocked so it quite challenging to manage them. 

So is ttyd the tool to get around this?

The architecture is close to this one:
![image](https://user-images.githubusercontent.com/3542031/73609424-c4c3cd00-45cd-11ea-80bc-7e0027a60fb2.png)

thank you for answering my humble question which answer might be obvious but due to my endless searching I cannot see the woods for the trees.

Stefan

**Comment by tsl0922** [comment]
I don't know, it's up to your requirements and usage. BTW, I don't use ttyd on production environment that open to the internet (for security concerns).
