### ISSUE TITLE
Nginx reverse proxy 

### ISSUE THREAD

**Issue by MrksHfmn** [tsl0922/ttyd#268]
can I use ttyd over a Nginx reverse proxy? If I proxy the request to the the running port I only get a black screen. LocalIP:Port works.

**Comment by fbartels** [comment]
Yes, works like a charm here.

My location block is:

```
        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass http://xx.xx.xx.xx:7681;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
```

**Comment by MrksHfmn** [comment]
Thank you. I will try

**Comment by fbartels** [comment]
Based on your first reply where you said it was working I would say that ttyd probably works in the root of a domain, but not in a subfolder.

**Comment by tsl0922** [comment]
```nginx
location ~ ^/ttyd(.*)$ {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass http://127.0.0.1:7681/$1;
}
```

It should works with the above code, except the basic auth.

**Comment by giohappy** [comment]
@tsl0922 I'm curious to know if the "except the basic auth" sentence means that with basic it wouldn't work or if you simplify removed it from your snippet for simplicity.

**Comment by tsl0922** [comment]
@giohappy https://github.com/tsl0922/ttyd/wiki/Nginx-reverse-proxy

**Comment by giohappy** [comment]
Yes, I know it, my question was about basic auth. Anyway I'll do a test myself :wink:

**Comment by flexponsive** [comment]
On nginx/1.14.0 (ubuntu-18.04), I was not able to pass parameters to the terminal. with the example configuration, i.e. ``http://127.0.0.1/ttyd/?arg=test``

This can be fixed in two ways: Either include the query string in the `proxy_pass` line explicitly: `proxy_pass http://127.0.0.1:7681/$1?$query_string;`

or to not use regexp matching for the location, and then the query string appears to be passed through the reverse proxy:

```
location /ttyd {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass http://127.0.0.1:7681/;
}
```
