### ISSUE TITLE
libwebsockets-dev dependencies include half of the other dependencies

### ISSUE THREAD

**Issue by SuperSandro2000** [tsl0922/ttyd#270]
**Describe the solution you'd like**
The readme suggests ````sudo apt-get install cmake g++ pkg-config git libwebsockets-dev libjson-c-dev zlib1g-dev libssl-dev libuv1-dev```` but ````sudo apt-get install -qy cmake g++ git pkg-config libjson-c-dev libwebsockets-dev```` would be enough.

**Describe alternatives you've considered**
Moving the extra dependencies to the libwebsockets-dev compile section.

**Additional context**
See https://packages.ubuntu.com/eoan/libwebsockets-dev and https://packages.debian.org/buster/libwebsockets-dev

**Comment by tsl0922** [comment]
ef38d28913bfefbcfed92e34f7bc10fb42368efe
