### ISSUE TITLE
建议修改 NGINX 的 Location 匹配规则

### ISSUE THREAD

**Issue by GallopingKylin** [tsl0922/ttyd#271]
按照 Usage 配置好 NGINX 以后在浏览器控制台发现有个 auth_token.js 请求失效，经排查问题在于浏览器访问的是 www.domain.com/auth_token.js 而不是 www.domain.com/ttyd/auth_token.js

建议将匹配规则修改成 location ~* ^/ttyd/(.*)$ 即可通过访问 www.domain.com/ttyd/ 找到该文件

**Comment by tsl0922** [comment]
你需要使用最新版本的 ttyd，新版本没有 auth_token.js 了，旧版本不支持代理到子路径。

**Comment by tsl0922** [comment]
如果没有代理到子路径的需求，所有版本都支持这么代理：

```nginx
location / {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass http://127.0.0.1:7681;
}
```
