### ISSUE TITLE
A bunch of scripts and configs to securely expose a shell in the browser

### ISSUE THREAD

**Issue by leshniak** [tsl0922/ttyd#272]
Hi!

Firstly, I want to thank you for your amazing work. It wouldn't be possible without your effort.

I've made a bunch of scripts and configs to securely expose user's shell in the browser (at least as much as I can for password authentication). You can add it to related projects or reuse something.

[https://github.com/leshniak/httpsh](https://github.com/leshniak/httpsh)

Thanks.

**Comment by tsl0922** [comment]
Thanks for sharing it, added to the README's Example Usage section.
