### ISSUE TITLE
Support cookie for authenctication

### ISSUE THREAD

**Issue by npateriya** [tsl0922/ttyd#274]
**Is your feature request related to a problem? Please describe.**
We want to iframe ttyd xterm in in application. iframing application works fine when authetication is disabled. When authentication is enable, it not possible to set Autorization header to support basic authentication. 
So if we want to iframe ttyd term only option is stat ttyd without cred. 

**Describe the solution you'd like**
Add support for accepting credential using cookie. Cookie could provide base 64 encoded credential as value. 
We are still using 1.5.X, so created prototype to support cookie based auth with 1.5.x forked branch.  
https://github.com/npateriya/ttyd/commit/ba92ac39a5a6968ff2894bf23a9a6fe9b2345c4f

**Describe alternatives you've considered**
Tried various alternative to pass Autz header in iframe but its not possible without some major hack.   

**Additional context**
If this agreed approach, please let me know, I can also try create PR with latest/major in a weeks time (Coding C after long break so code probably little rusty).

**Comment by tsl0922** [comment]
Using a reverse proxy like nginx to pass the `Authorization` header should also works.

**Comment by npateriya** [comment]
Thank you @tsl0922 for quick response & this great project. 

Our scenario is little complex, may not be able to provide all details in this context but summary is: 

- We deploy kubernetes pods(with ttyd)  for large number of users and each users pod is exposed via nginx-ingress. Unique credential is set for each pods/container.   

- Given above setup we are limited to standard nginx ingress capabilities. 

- We could let nginx handle authentication using external auth-url but that would leave pods with ttyd open within cluster. We ideally want both http & WS connection of ttyd to be e2e authenticated, which is enabled when cred are set on  ttyd process itself. 

We will explore proxy handling auth, if we can't support it directly on ttyd process (Desired).

**Comment by tsl0922** [comment]
How about url argument/token based auth? you can write a custom start command/script and check the auth token in it.

>  -a, --url-arg           Allow client to send command line arguments in URL (eg: http://localhost:7681?arg=foo&arg=bar)

**Comment by npateriya** [comment]
Are you suggesting something like this? 
```
ttyd -a /test.sh
```
>>test.sh 
```
#!/bin/bash
if [ "$#" -lt 1 ] || [ $1 != "secret" ] ; then
      echo "Access denied"
      while true; do sleep infinity; done
fi
echo "Start session, passed secret correct $1"
/bin/bash
```
This allow access : http://localhost:7681/?arg=secret 

But one part I am not sure what should be behavior if arg does not match secret. 
Added sleep infinity for now.

**Comment by tsl0922** [comment]
> But one part I am not sure what should be behavior if arg does not match secret.
Added sleep infinity for now.

`echo "Access denied" && exit 1` ? It will close the underlying websocket connection.

**Comment by npateriya** [comment]
>> echo "Access denied" && exit 1 ? It will close the underlying websocket connection.

 I tried that first but when opens url in browser, I noticed infinite loop of exit &  attempt to reconnect. 
```
[2020/02/17 07:50:48:1766] N: WS closed from 172.17.0.1, clients: 0
[2020/02/17 07:50:48:2902] N: HTTP /token - 172.17.0.1
[2020/02/17 07:50:48:2954] N: WS   /ws - 172.17.0.1, clients: 1
[2020/02/17 07:50:48:3047] N: started process, pid: 108
[2020/02/17 07:50:48:3096] E: read_cb: EIO
[2020/02/17 07:50:48:3097] N: process exited with code 1, pid: 108
[2020/02/17 07:50:48:3100] N: WS closed from 172.17.0.1, clients: 0
[2020/02/17 07:50:48:4198] N: HTTP /token - 172.17.0.1
[2020/02/17 07:50:48:4242] N: WS   /ws - 172.17.0.1, clients: 1
[2020/02/17 07:50:48:4322] N: started process, pid: 109
[2020/02/17 07:50:48:4359] E: read_cb: EIO
[2020/02/17 07:50:48:4360] N: process exited with code 1, pid: 109
[2020/02/17 07:50:48:4363] N: WS closed from 172.17.0.1, clients: 0
[2020/02/17 07:50:48:5669] N: HTTP /token - 172.17.0.1
[2020/02/17 07:50:48:5717] N: WS   /ws - 172.17.0.1, clients: 1
[2020/02/17 07:50:48:5817] N: started process, pid: 110
[2020/02/17 07:50:48:5856] E: read_cb: EIO
```

**Comment by tsl0922** [comment]
sorry, `exit 0` should work, the reconnect logic can not be disabled for now.

**Comment by npateriya** [comment]
```exit 0``` works better. 
Thank you @tsl0922 for quick help & keep up good work. 

We are planning to use it as part of bigger project, let me know if you want references on project using ttyd.

**Comment by tsl0922** [comment]
> let me know if you want references on project using ttyd.

Feel free to edit the wiki page to add your project:

https://github.com/tsl0922/ttyd/wiki

**Comment by AlessioScarlet** [comment]
> EIO

getting the same error

**Comment by AlessioScarlet** [comment]
> 
> 
> > > echo "Access denied" && exit 1 ? It will close the underlying websocket connection.
> 
> I tried that first but when opens url in browser, I noticed infinite loop of exit & attempt to reconnect.
> 
> ```
> [2020/02/17 07:50:48:1766] N: WS closed from 172.17.0.1, clients: 0
> [2020/02/17 07:50:48:2902] N: HTTP /token - 172.17.0.1
> [2020/02/17 07:50:48:2954] N: WS   /ws - 172.17.0.1, clients: 1
> [2020/02/17 07:50:48:3047] N: started process, pid: 108
> [2020/02/17 07:50:48:3096] E: read_cb: EIO
> [2020/02/17 07:50:48:3097] N: process exited with code 1, pid: 108
> [2020/02/17 07:50:48:3100] N: WS closed from 172.17.0.1, clients: 0
> [2020/02/17 07:50:48:4198] N: HTTP /token - 172.17.0.1
> [2020/02/17 07:50:48:4242] N: WS   /ws - 172.17.0.1, clients: 1
> [2020/02/17 07:50:48:4322] N: started process, pid: 109
> [2020/02/17 07:50:48:4359] E: read_cb: EIO
> [2020/02/17 07:50:48:4360] N: process exited with code 1, pid: 109
> [2020/02/17 07:50:48:4363] N: WS closed from 172.17.0.1, clients: 0
> [2020/02/17 07:50:48:5669] N: HTTP /token - 172.17.0.1
> [2020/02/17 07:50:48:5717] N: WS   /ws - 172.17.0.1, clients: 1
> [2020/02/17 07:50:48:5817] N: started process, pid: 110
> [2020/02/17 07:50:48:5856] E: read_cb: EIO
> ```

getting the same error

**Comment by AHPanna** [comment]
> Are you suggesting something like this?
> 
> ```
> ttyd -a /test.sh
> ```
> 
> > > test.sh
> 
> ```
> #!/bin/bash
> if [ "$#" -lt 1 ] || [ $1 != "secret" ] ; then
>       echo "Access denied"
>       while true; do sleep infinity; done
> fi
> echo "Start session, passed secret correct $1"
> /bin/bash
> ```
> 
> This allow access : http://localhost:7681/?arg=secret
> 
> But one part I am not sure what should be behavior if arg does not match secret.
> Added sleep infinity for now.

add with this :  ttyd -d -a /test.sh

**Comment by tsl0922** [comment]
https://github.com/tsl0922/ttyd/wiki/Auth-Proxy
