### ISSUE TITLE
Support hashed password as credential

### ISSUE THREAD

**Issue by Zibri** [tsl0922/ttyd#277]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
./ttyd -z username:5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8

**Describe alternatives you've considered**
No alternatives except implementing the function myself.

**Additional context**
It would be very useful in some scenarios where the batch file is visible but not modifiable.

**Comment by tsl0922** [comment]
Duplicate of #171
