### ISSUE TITLE
Static compilation

### ISSUE THREAD

**Issue by Zibri** [tsl0922/ttyd#283]
It would be nice to have a static compilation under linux without cross compiling..

**Comment by tsl0922** [comment]
https://github.com/tsl0922/ttyd/blob/master/.github/workflows/release.yml

**Comment by Zibri** [comment]
yes.. I saw that already.. but it uses a huge script and docker image..
I just wish to know how to compile it statically from a normal x86 linux machine (ubuntu)
with the usual gcc/make/configure etc

**Comment by tsl0922** [comment]
Take a look at `scripts/cross-build.sh`, and search for the `static` keyword.

You won't want to build the static version with usual gcc,  the static binary linked with glibc is huge.

**Comment by tsl0922** [comment]
BTW: you can get the static version of ttyd for every commit from the ci artifacts, for example:

https://github.com/tsl0922/ttyd/actions/runs/54403251
