### ISSUE TITLE
[1.6.0] linux binary file without the -b option

### ISSUE THREAD

**Issue by sagerenn** [tsl0922/ttyd#285]
**Describe the bug**
I need to use ttyd with a subpath. I downloaded the new version, but cannot see the option --base-path to support using behind a reverse proxy.

**Screenshots**
![image](https://user-images.githubusercontent.com/49195270/77220240-ae34ef00-6b03-11ea-9018-4828e4e11cb2.png)

**Environment:**
 - OS: Linux_64

**Additional context**

**Comment by tsl0922** [comment]
It's added after the 1.6.0 release, if you want a binary with this feature, download from the latest ci artifacts:

https://github.com/tsl0922/ttyd/actions/runs/55551711
