### ISSUE TITLE
Some process fail to print output and hanging when ttyd is running in gVisor.

### ISSUE THREAD

**Issue by Leemoonsoo** [tsl0922/ttyd#286]
**Describe the bug**
[gVisor](https://github.com/google/gvisor) is a user-space kernel. gVisor is particularly useful when running untrusted code on containers, in the environment such as Docker, Kubernetes. For example [GKE use it](https://cloud.google.com/kubernetes-engine/sandbox) to sandbox workload on Kubernetes.

However, when ttyd is running inside gVisor, some command fails to print output or fails to exit.
Those commands are working normally inside gVisor if it runs without ttyd.

**To Reproduce**
1. run 'ttyd bash' inside [gVisor enabled container](https://gvisor.dev/docs/user_guide/quick_start/docker/).
2. connect ttyd on your browser. You'll get a bash shell on your browser.
3. Test following commands on the browser
  - `tty -v` : Okay
  - `tty -h`  : Process hanging
  - `kubectl config` : Okay
  - `kubectl config get-contexts` : Process hanging
  (you can get `kubectl` [here](https://storage.googleapis.com/kubernetes-release/release/v1.17.3/bin/linux/amd64/kubectl))

**Expected behavior**
  - `tty -h` and `kubectl config get-contexts` print output and exit process correctly.

**Screenshots**
Like following screenshot, running some command (in this example, running `ttyd -h`) on gVisor does not finish the process.
![image](https://user-images.githubusercontent.com/1540981/77256663-e1bf6880-6c2c-11ea-823c-5768d834bcba.png)

**Environment:**
 - OS: macOS 10.15.1
 - Browser: Chrome 80.0.3987.132, Safari 13.0.3

**Additional context**
I can provide a remote environment that have this problem.

**Comment by tsl0922** [comment]
https://gvisor.dev/docs/user_guide/compatibility/linux/amd64/ says:

> gVisor does not support all syscalls and some syscalls may have a partial implementation.

I don't think it is related to ttyd, it should be gVisor's compatibility issue.
