### ISSUE TITLE
Suburl / subdirectory does not work

### ISSUE THREAD

**Issue by onny** [tsl0922/ttyd#289]
Hey,
I'm using the latest version and also tried git master. Thank you for implementing suburl support. Unfortunately it doesn't work for me yet.
```
ttyd -b "/ttyd" bash
ttyd --base-path "/ttyd" bash
```
But I only get 404 on http://playground.pi:7681/ttyd :,(

**Comment by tsl0922** [comment]
Try: `-b /ttyd/`

**Comment by tsl0922** [comment]
It should be a bug, I'll take a look on it. The feature is contributed by @dmbasso (#281).

**Comment by onny** [comment]
> -b /ttyd/

Good guess but doesn't work :,(

**Comment by dmbasso** [comment]
Hi @onny, just to be clear, you tried accessing the url with a trailing slash, correct? There is a difference between http://playground.pi:7681/ttyd and http://playground.pi:7681/ttyd/
I didn't implement a redirect from the first to the second because I wanted my patch to be as least intrusive as possible. But I think having the redirect would provide a better user experience.

**Comment by onny** [comment]
> Hi @onny, just to be clear, you tried accessing the url with a trailing slash, correct? There is a difference between http://playground.pi:7681/ttyd and http://playground.pi:7681/ttyd/
> I didn't implement a redirect from the first to the second because I wanted my patch to be as least intrusive as possible. But I think having the redirect would provide a better user experience.
```
onny@playground ~ [1]> ttyd -v
ttyd version 1.6.0-b4bcd0b
onny@playground ~> ttyd -b "/ttyd/" bash &
onny@playground ~> curl http://localhost:7681/ttyd
<html><head><meta charset=utf-8 http-equiv="Content-Language" content="en"/><link rel="stylesheet" type="text/css" href="/error.css"/></head><body><h1>404</h1></body></html>⏎                                                   onny@playground ~> curl http://localhost:7681/ttyd/
<html><head><meta charset=utf-8 http-equiv="Content-Language" content="en"/><link rel="stylesheet" type="text/css" href="/error.css"/></head><body><h1>404</h1></body></html>⏎   
```
Doesn't work in both cases :(

**Comment by dmbasso** [comment]
@onny try the combination `ttyd -b /ttyd bash` and `curl http://localhost:7681/ttyd/`.

**Comment by onny** [comment]
strange this works, thanks :)

**Comment by dmbasso** [comment]
@tsl0922 perhaps we should automatically strip the trailing slashes from the -b option, and also add a redirection endpoint (i.e. url without the trailing slash). If you're ok with that, I can submit another PR.

**Comment by tsl0922** [comment]
> @tsl0922 perhaps we should automatically strip the trailing slashes from the -b option, and also add a redirection endpoint (i.e. url without the trailing slash). If you're ok with that, I can submit another PR.

welcome

**Comment by dmbasso** [comment]
@onny you should be able to use your original combination (`ttyd -b "/ttyd/" bash` and accessing `http://localhost:7681/ttyd`) successfully now, starting with revision 398bebf0.
