### ISSUE TITLE
different sessions with different users.

### ISSUE THREAD

**Issue by singhania** [tsl0922/ttyd#290]
**Is your feature request related to a problem? Please describe.**
Currently while starting web server we can provide uid and gid and terminal will start with that.
Problem with this is each session will start with same user because of which a multi tenant system can't work.

**Describe the solution you'd like**
As I understood, with every new session a new terminal process is created.Idea to take uid/user and group information from api and initiate terminal with that user.

I have recently started using it so have less/no idea if this is already existing as from documentation I couldn't find out the same.

**Comment by tsl0922** [comment]
Do you men different system users? I don't think it's a feature that ttyd should implements, you may try solutions like [httpsh](https://github.com/leshniak/httpsh) which usesinvoke ssh to open a new session.
