### ISSUE TITLE
Add a switch to disable "Leave site?" alert

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [tsl0922/ttyd#294]
**Is your feature request related to a problem? Please describe.**
I'd like to disable alert that prevents closing terminal immediately.

**Describe the solution you'd like**
Add a commandline switch to ttyd, eg. `--disable-leave-alert`

**Additional context**
This is the alert in question:
![image](https://user-images.githubusercontent.com/3395918/77736239-4c491d80-700c-11ea-9895-bb2e98415688.png)

**Comment by bbilas** [comment]
That's related to the beforeunload event located in `html/src/components/terminal/index.tsx`. Is there any easy way to control it from the C sources? If so I can take a look on it.

**Comment by tsl0922** [comment]
Take a look at the `--client-option` argument and `SET_PREFERENCES` command.

**Comment by bbilas** [comment]
@tsl0922 I guess that if it's feasible to change it via the above option you won't be interested to have this as a separate cmd arg?

**Comment by tsl0922** [comment]
Added support via 260778aff2c2067494bc0d3a33e0f410500d732d, usage:

```bash
ttyd -t disableLeaveAlert=true bash
```

**Comment by mateuszkwiatkowski** [comment]
Thank you!
