### ISSUE TITLE
how to 

### ISSUE THREAD

**Issue by rinaldi6109** [tsl0922/ttyd#296]
(Houston, we have a newbie)
I have installed ttyd on my router. I launch it with the command: `ttyd ash`. It works but every time I open the browser, point to my_router_ip:7681 and then close the browser, I need to launch it again. Is it possible to make it running continuously? 
Thank you.

**Comment by tsl0922** [comment]
You can use tmux or screen, there is a tmux example on the wikii: 

https://github.com/tsl0922/ttyd/wiki/Example-Usage
