### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [tsl0922/ttyd#3]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html) ⇒ [tty_server_new](https://github.com/tsl0922/ttyd/blob/0a981bae6617aefd6e526a6e9ab9667840a28ec8/server.c#L79)
- [pthread_mutex_lock](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html) ⇒ [callback_tty](https://github.com/tsl0922/ttyd/blob/0a981bae6617aefd6e526a6e9ab9667840a28ec8/protocol.c#L172)

**Comment by tsl0922** [comment]
Thanks! I've added `NULL` check for `malloc` at [utils.c](https://github.com/tsl0922/ttyd/blob/master/utils.c#L29).

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by tsl0922** [comment]
Yes, will do later. Would you mind sending a PR for this? That will be much appreciate.

**Comment by elfring** [comment]
Would it be safer to keep this issue open then until the remaining update candidates will be improved?
* How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for static code analysis") also for your software?
* Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?

  How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by tsl0922** [comment]
I have plan for that, but no done yet, since this project is at pretty early stage at this time.

**Comment by elfring** [comment]
How much will the programming language selection influence software development challenges in the evolving applications you care about?
