### ISSUE TITLE
老大能不能支持源码设置user和password，进web了再输一次用户名和密码很麻烦

### ISSUE THREAD

**Issue by willisworley** [tsl0922/ttyd#307]
Describe your problem or question here.
直接同管理员密码，不要二次输入了

**Comment by tsl0922** [comment]
不知道你在说什么，请仔细描述下你怎么使用的，和遇到的问题。

**Comment by willisworley** [comment]
> 不知道你在说什么，请仔细描述下你怎么使用的，和遇到的问题。

就是我进入web192.168.1.1控制台要输入一遍root和管理员密码，再点击ttyd，又要一次。

能不能合二为一

**Comment by tsl0922** [comment]
你说的是路由器上吧，ttyd 是个独立的程序，目前是无法复用路由器网页的登陆态的。
