### ISSUE TITLE
Customizing Webfonts

### ISSUE THREAD

**Issue by AGhost-7** [tsl0922/ttyd#31]
First of all, great project. I've been trying to find something like this for a while now.

I'm trying to use this project to create remote development environments. I already have docker images which I can use for development environments, so all I had to do was add ttyd to one of my images.

My issue at the moment is that I'm using customized fonts (for vim airline and powerline) which normally can be set from the terminal's options. I'd just need some way to set the font as well as load webfonts into the client.

p.s.: This is what it looks so far.

https://github.com/AGhost-7/nodejs-online

**Comment by tsl0922** [comment]
ttyd bundles a inlined `index.html` to it's executable file, no other external dependencies, You can modify and build your own `index.html` and rebuild ttyd if you want, [see the instructions](https://github.com/tsl0922/ttyd/tree/master/html).

I'd like to add an option for using an external `index.html` or html root for this, but no deadline, I'm a little busy recently.

**Comment by AGhost-7** [comment]
That's is what I did - I forked the project for now but I feel this is more of a temporary solution.

I'm afraid that `C` is not something that I've very good at.

**Comment by foxundermoon** [comment]
+1

**Comment by tsl0922** [comment]
Added the `--index` option for this (c9ffa8a8d7d21ca3114b3bcd49fd8d4624723185).

 Be aware that only external `index.html` file is supported, not html root.

**Comment by AGhost-7** [comment]
While I appreciate the feature which was added, its currently easier to just fork and use the gulp build in ttyd to customize the terminal instead of using the new `--index` option. If I use the `--index` option which was added I need to provide my own build script to generate the one html file.

What I am looking for is something closer to what you'd see in a regular terminal - more along the lines of being able to set terminal profiles.

**Comment by tsl0922** [comment]
I don't think recompile `index.html` is needed if you only want to change something like font-family, since your can add your own css block to override any existed class.

**Comment by athrunsun** [comment]
@tsl0922 Which element should we set font-family upon? Is it a canvas element?

**Comment by tsl0922** [comment]
Great! This feature wasn't well documented, there is similar issues I've answered before (like #122).

**Comment by Zibri** [comment]
hmm no, tls0922: you should put an option for background/foreground color without the need to write a css or modify the index.html

**Comment by tsl0922** [comment]
Hi, @Zibri you can custom the full color scheme with `-t, --client-option`. For example, to change the background/foreground:

```
ttyd -t 'theme={"foreground":"green","background":"cyan"}' bash
```
The code above only override the foreground/background color, you can get a full list of the predefined colors [here](https://github.com/tsl0922/ttyd/blob/master/html/js/app.js#L255).

**Comment by Zibri** [comment]
> ```shell
> -t fontSize=16 -t fontFamily="'IBM Plex Mono Medium', 'Noto Sans CJK SC'"
> ```

I gave it another go today... and I still have a problem:
even though I used: --terminal-type xterm-256color
in linux I see the correct terminal type but there is no color.
why is that?
I tried both /bin/login both /bash -i -l

**Comment by metorm** [comment]
Folks, I had built a forked version that has embedded nerd font. You can also replace your font.

https://github.com/metorm/ttyd-nerd-font

https://www.weiran.ink/oss/ttyd-with-nerd-font.html
