### ISSUE TITLE
Enable SSL/TLS by Default

### ISSUE THREAD

**Issue by oxr463** [tsl0922/ttyd#322]
I think it would be appropriate if `ttyd` tried using SSL/TLS by default, and then if that fails, fall-back to HTTP with a warning stating that the network traffic is unencrypted.

This would require automatic generation of an SSL/TLS certificate, per https://github.com/tsl0922/ttyd/wiki/SSL-Usage. Alternatively, it would be nice if we could offload this process to `certbot` to use a Let's Encrypt certificate.

**Comment by hholst80** [comment]
A common workaround is to use SSH tunneling if you need encryption on local networks. TLS certificate management is a PITA in development environments.

**Comment by oxr463** [comment]
> A common workaround is to use SSH tunneling if you need encryption on local networks. TLS certificate management is a PITA in development environments.

I'll have to try that out. Still, it was my goal to use Let's Ecrypt to automate the process so that it would be trivial to use SSL/TLS.

**Comment by hholst80** [comment]
Re Let's Encrypt. At very least that would require you to have access to a public domain name and/or public internet facing web server.

**Comment by oxr463** [comment]
> Re Let's Encrypt. At very least that would require you to have access to a public domain name and/or public internet facing web server.

I'm using afraid.org for dynamic DNS, and certbot has a built in web server.

**Comment by pre** [comment]
I don't agree about the default. In a reasonable environment you could expect that the SSL is terminated by an ingress which is in front of the ttyd service. Hence, even though ttyd is not using SSL, the traffic is still encrypted. 

Displaying a warning would require an option to turn off such a warning (since it's misleading when SSL is terminated before ttyd).
