### ISSUE TITLE
Listen on file socket

### ISSUE THREAD

**Issue by sw-double** [tsl0922/ttyd#33]
Is it possible to listen on socket rather than network port?

**Comment by tsl0922** [comment]
Yes, it's possible. It can be simply done by passing a flag to libwebsockets, but this requires libwebsockets to be compiled with unix socket support, which may not enabled by default.

**Comment by tsl0922** [comment]
Fixed by de75490d3ec594b42478d92d135ef12cb1fdb735

If you got `libwebsockets is not compiled with UNIX domain socket support` error, make sure libwebsockets is compiled with `-DLWS_UNIX_SOCK` cmake flag.
