### ISSUE TITLE
Is it possible to change the theme on the fly?

### ISSUE THREAD

**Issue by jakerobb** [tsl0922/ttyd#341]
I am writing an Electron app that embeds ttyd in an iframe. My app has light mode and dark mode, and we're soon adding the ability to honor the system dark mode. As such, it's possible that the app's look and feel will change while ttyd is displayed, and so I'd like to be able to toggle ttyd between two themes on the fly. I don't want to restart the ttyd process when this happens because it would lose the shell session. 

Is this possible? I've seen #195, and I've successfully defined the two themes I want to switch between. Just need a way to pass the info along to the running ttyd.

Alternatively, a way to specify two themes such that ttyd could use CSS prefers-color-scheme to select between them would also be sufficient.

**Comment by tsl0922** [comment]
It's possible, but not recommended. Since you are writing an Electron  app, consider using [node-pty](https://github.com/microsoft/node-pty) and [xterm.js](https://github.com/xtermjs/xterm.js) directly?

**Comment by jakerobb** [comment]
Thanks, will do!
