### ISSUE TITLE
ttyd-1.6.0 fails to build on Fedora 32+

### ISSUE THREAD

**Issue by itamarjp** [tsl0922/ttyd#344]
**Describe the bug**

ttyd-1.6.0 fails to build on Fedora 32+

detailed logs here ->
https://koji.fedoraproject.org/koji/taskinfo?taskID=44219492

direct link ->

https://kojipkgs.fedoraproject.org//work/tasks/9498/44219498/build.log

**Comment by tsl0922** [comment]
similar issue #319, should not be related with ttyd.

**Comment by itamarjp** [comment]
I found this.

https://libwebsockets.org/pipermail/libwebsockets/2017-December/003585.html

then I recompiled libwebsockets passing the flowing option to cmake

    -D LWS_WITHOUT_EXTENSIONS=OFF \

after that ttyd compiled fine, then this issue seems to be related on some features enabled or not in libwebsockets.

**Comment by tsl0922** [comment]
79acf9e896c8da91997dade70d0d2a0440d138fd should should fix this issue, but it's not released yet. 

I think it should be fixed on libwebsockets's side, `lws_extension_callback_pm_deflate` is not called directly from ttyd, libwebsockets should ignore the `extensions` field if it's not compiled with extensions support.

**Comment by itamarjp** [comment]
ttyd is now in Fedora, 

https://koji.fedoraproject.org/koji/packageinfo?packageID=31255
