### ISSUE TITLE
send init command to terminal

### ISSUE THREAD

**Issue by comarius** [tsl0922/ttyd#351]
I am opening the teminal in a iframe
From the parent page JScript I can access the xterm-  textarea.
I tried to chnage the value but the command does not get send.
I would like to send an initial command to the shell right after I have the prompt.
Which term JAVA script function I can use to do that on the HTML element terminal-*.

Thank you

**Comment by tsl0922** [comment]
> -a, --url-arg           Allow client to send command line arguments in URL (eg: http://localhost:7681?arg=foo&arg=bar)

run ttyd with the `--url-arg` option and a shell script as start command, then you can receive the url params via command line arguments in the script.

**Comment by comarius** [comment]
Thank you. I figure it out form the source code mean while.
