### ISSUE TITLE
ttyd version 1.2.1  浏览器多次刷新之后 无法再次链接

### ISSUE THREAD

**Issue by bhzhu203** [tsl0922/ttyd#36]
ttyd version 1.2.1  浏览器多次刷新之后 无法再次链接，如果刚打开的初期疯狂刷新浏览器tty页面，会导致所有窗口都打不开，然后用其他浏览器也连接不进去，一直转圈。只有结束掉子进程才会恢复

**Comment by tsl0922** [comment]
这是已知问题，目前 ttyd 创建子进程的时候是异步的，但退出子进程的时候不是。

**Comment by tsl0922** [comment]
你可以尝试下最新 master 分支的代码，启动的时候添加 `-s SIGKILL` 参数强制子进程退出，这样应该可以缓解一下这个问题。

**Comment by bhzhu203** [comment]
问题解决！
