### ISSUE TITLE
ttyd-1.6.0 link error on openwrt 19.07 when use glibc

### ISSUE THREAD

**Issue by topeqin** [tsl0922/ttyd#361]
Describe the bug
ttyd-1.6.0 fails to build on openwrt 19.07 when use glibc

To Reproduce
1. git clone https://git.openwrt.org/openwrt/openwrt.git
2. ./scripts/feeds update -a; ./scripts/feeds install ttyd
3. make menuconfig ; enable CONFIG_PACKAGE_luci-app-ttyd=y  CONFIG_LIBC_USE_GLIBC=y
   or use the attachment ttyd_openwrt_1907.config directly.
4. make package/ttyd/{clean,compile} V=s

Actually no matter the ARCH or targets ath79 bcm53xx ipq806x all meet same error once enable ttdy and using glibc

Screenshots
![ttyd-1 6 0_failed_screenshot](https://user-images.githubusercontent.com/9261785/82547743-cb7e4c00-9b8c-11ea-94b1-d72aba186ebf.jpg)
[ttyd-1.6.0_failed.log](https://github.com/tsl0922/ttyd/files/4661780/ttyd-1.6.0_failed.log)

Environment:
 - OS: [ubuntu [16.04]]

**Comment by topeqin** [comment]
should pass the TARGET_LDFLAGS += -ldl to cmake.  This one already was verified in my side and ttyd can work well on real hardware board.

Thanks
QG

**Comment by tsl0922** [comment]
Thanks for sharing it, closing as it should be fixed on openwrt's side.

**Comment by topeqin** [comment]
hello Shuanglei

Would you mind tell me why need fix in openwrt side not package side?
thanks a lot

Thanks
Qin Guang
