### ISSUE TITLE
How to use the Authorization header

### ISSUE THREAD

**Issue by jkinred** [tsl0922/ttyd#364]
In #274 there is a reference to having a reverse proxy pass the "Authorization" header. Can you clarify how that works and how `ttyd` verifies that header? I couldn't find any reference in the source code.

> Using a reverse proxy like nginx to pass the `Authorization` header should also work.
>
> _Originally posted by @tsl0922 in https://github.com/tsl0922/ttyd/issues/274#issuecomment-586787163_

**Comment by tsl0922** [comment]
```nginx
proxy_set_header Authorization "Basic dXNlcjpwYXNz"
```

To get the basic auth value from user and pass, run `echo -n "user:pass" | base64`.
