### ISSUE TITLE
can not use lrzsz

### ISSUE THREAD

**Issue by targetoyes** [tsl0922/ttyd#37]
When inputting rz/sz in commandline, terminal will be stuck. Is it possible for author to create a similar function to realize it?

**Comment by tsl0922** [comment]
I'm wondering the usefulness of implementing it on the browser side, see the previous discussion: https://github.com/sourcelair/xterm.js/issues/279

**Comment by FGasper** [comment]
https://www.npmjs.com/package/zmodem.js

I’ve made an ALPHA release of zmodem.js. Give it a whirl, and let me know how it works for you.
