### ISSUE TITLE
Make install errors

### ISSUE THREAD

**Issue by askanton71** [tsl0922/ttyd#375]
After running  _root@user:~/ttyd/build# make_   results errors:

root@user:~/ttyd/build# make
[ 16%] Building C object CMakeFiles/ttyd.dir/src/http.c.o
/root/ttyd/src/http.c: In function 'callback_http':
/root/ttyd/src/http.c:155:45: error: 'HTTP_STATUS_FOUND' undeclared (first use in this function)
         if (lws_add_http_header_status(wsi, HTTP_STATUS_FOUND, &p, end) ||
                                             ^
/root/ttyd/src/http.c:155:45: note: each undeclared identifier is reported only once for each function it appears in
CMakeFiles/ttyd.dir/build.make:86: recipe for target 'CMakeFiles/ttyd.dir/src/http.c.o' failed
make[2]: *** [CMakeFiles/ttyd.dir/src/http.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ttyd.dir/all' failed
make[1]: *** [CMakeFiles/ttyd.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tsl0922** [comment]
Check you libwebsockets installation, HTTP_STATUS_FOUND is defined in libwebsockets.

**Comment by askanton71** [comment]
Seems ok
apt-get install -y libwebsockets-devReading package lists... Done
Building dependency tree       
Reading state information... Done
libwebsockets-dev is already the newest version (1.7.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by askanton71** [comment]
> Check you libwebsockets installation, HTTP_STATUS_FOUND is defined in libwebsockets.

**Comment by askanton71** [comment]
> Check you libwebsockets installation, HTTP_STATUS_FOUND is defined in libwebsockets.

Seems ok
apt-get install -y libwebsockets-devReading package lists... Done
Building dependency tree
Reading state information... Done
libwebsockets-dev is already the newest version (1.7.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by tsl0922** [comment]
Should be fixed on master now, HTTP_STATUS_FOUND was introduced since lws 2.0
