### ISSUE TITLE
Dockerfile with parameters

### ISSUE THREAD

**Issue by jgrubio** [tsl0922/ttyd#378]
Hi,

I am trying to build ttyd in docker with parameters, such as black background or a specific user, but I am unable.

Right now I raise it like this. The CMD of my Dockerfile is:

`CMD ["ttyd", "bash"]
`
I am not able to make it work
Thank you.

**Comment by pre** [comment]
If you build on top of https://github.com/tsl0922/ttyd/blob/master/Dockerfile , try this:

Dockerfile:
```
[..]
ENTRYPOINT ["/sbin/tini", "--"]

CMD ["/ttyd-cmd"]
```

/ttyd-cmd:
```
#!/usr/bin/env bash

exec ttyd -t "cursorBlink=true" -a -c "user:pass" -- /ws-cmd
```

/ws-cmd:
```
#!/usr/bin/env bash

echo "Hello World"
echo "Args: "
echo $* 

# do what you want with $1, $2 etc
exec bash 
```

**Comment by jgrubio** [comment]
All was perfect  @pre 

Thanks for your help!

**Comment by anjorinjnr** [comment]
I have a similar need but I don't understand the  /ttyd-cmd and /ws-cmd. Where do those go?

I am starting the terminal using a dockerfile but I would like to setup the container to use https. Any idea how to provide the ssl settings in the docker file?

**Comment by pre** [comment]
> I have a similar need but I don't understand the /ttyd-cmd and /ws-cmd. Where do those go?

in this example above, 
* `ws-cmd` is the wrapper executed by `ttyd`
* `ttyd-cmd` executes `ttyd`
* `ttyd-cmd` is executed as the default command by the container entrypoint. 


> I am starting the terminal using a dockerfile but I would like to setup the container to use https. Any idea how to provide the ssl settings in the docker file?

I recommend that you use an external service to terminate ssl, such as nginx,  in front of ttyd.

**Comment by anjorinjnr** [comment]
Thanks for the quick reply. I tried setting up but I am getting this error

`Error code: SSL_ERROR_RX_RECORD_TOO_LONG`

My config looks like this (copied from [here](https://github.com/tsl0922/ttyd/wiki/Let's-Encrypt#nginx-reverse-proxy))

```
server {
    server_name <my domain>;

    # the following section is relevant if you've generated SSL certificates via Let's Encrypt - which you should have >:(
    listen 443 ssl;
    ssl_certificate           /etc/letsencrypt/live/<my domain>/fullchain.pem;
    ssl_certificate_key       /etc/letsencrypt/live/<my domain>/privkey.pem;
    ssl_trusted_certificate   /etc/letsencrypt/live/<my domain>/chain.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://127.0.0.1:$remote_port/;  # default ttyd port, notice the https prefix
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        # needed for websocket
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}

# redirect http requests to https
server {
    if ($host = <my domain>) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name <my domain>;
    return 404;
}
```
A bit more info on my setup.

I have a server at say server.domain.com

This server has some api as `server.domain.com:5000`. The server spins up ttyd docker instances at unique port.

So without https, I can do `http://server.domain.com:<unique-port>` to access the ttyd terminal at that port.

What I want to do is have these routes work on https
`https://server.domain.com:5000 `and
`https://server.domain.com:<unique-port>`

The let's encrypt certs are already installed on server.domain.com.

Thanks for your help!

**Comment by anjorinjnr** [comment]
Thanks @pre. Was able to setup nginx.
