### ISSUE TITLE
About Tab key input with ttyd.

### ISSUE THREAD

**Issue by github718** [tsl0922/ttyd#392]
To install ttyd, I created ttyd from the source by referring to "Install on Linux" on the top page, and confirmed the command input and operation.
I used the linked source.
https://github.com/tsl0922/ttyd/archive/1.6.1.tar.gz

I was able to connect from Googlechrome without any problems.

However, the following message is output on the page when the tab key is input to output candidates when entering the command.
[tabkeyinput_log.txt](https://github.com/tsl0922/ttyd/files/4856266/tabkeyinput_log.txt)

I would like to use the tab key to get suggestions.
How do i do it?

**Comment by tsl0922** [comment]
Remove the `-x` argument to `bash`, for example:

```
ttyd -p 8080 bash
```

**Comment by github718** [comment]
Thank you for your reply to tsl0922.
It is solved.
Thank you very much.
