### ISSUE TITLE
How to Execute shell when connecting.

### ISSUE THREAD

**Issue by github718** [tsl0922/ttyd#395]
As the title says.
When you connect with ttyd, the terminal input screen is displayed.
But can I auto-execute a specific command (shell execution) when connecting to a ttyd server?

**Comment by tianyuanhao** [comment]
Try `expect`.

```tcl
#!/usr/bin/expect
set timeout -1
spawn bash
expect "$ "
send "echo hello\r"
interact
```

**Comment by github718** [comment]
Thank you for your reply. tianyuanhao.
I'm sorry for a beginner.
I don't know how to work with ttyd.
How can I automatically execute this "expect" when accessing ttyd?

**Comment by tianyuanhao** [comment]
@github718 Assuming this file is named `hello.exp`, make sure that `hello.exp` is executable.

```sh
ttyd ./hello.exp
```

You can modify "echo hello" to the command you want to execute.

**Comment by github718** [comment]
@tianyuanhao 
I'm Done!
Thank you Very much!
