### ISSUE TITLE
Additional example usages to wiki

### ISSUE THREAD

**Issue by it-is-wednesday** [tsl0922/ttyd#397]
Hey :) I've noticed your wiki is open for anyone to edit, but I'd rather not mess with anyone's project without their permission, so here are my proposed additions to [this page](https://github.com/tsl0922/ttyd/wiki/Example-Usage): 

https://gist.github.com/it-is-wednesday/39b7999f34940ce3e97606e29eb07d91

(uploaded as a gist so you'll have an easier time to copy-paste, if you liked it :wink:)

Love your work :heart:

**Comment by tsl0922** [comment]
Thanks 👍 

It's intended to be a community wiki, feel free to add it yourself.

**Comment by it-is-wednesday** [comment]
Did so :100:
