### ISSUE TITLE
Function Keys Not working (F1 to F5)

### ISSUE THREAD

**Issue by jayaruvan** [tsl0922/ttyd#399]
I have an application which uses function keys (F1 to F12). I tried ttyd via Chrome and F5 to F12 keys are working properly, not the F1 to F5 in vt100 terminal. 

How can I get this to work?  
ttyd over chrome shows different keycodes. Is there any way i can remap keycodes with ttyd?

**Comment by jayaruvan** [comment]
bump

**Comment by jayaruvan** [comment]
bump

**Comment by tsl0922** [comment]
Can't reproduce. I tried `htop` on linux and press F1-F5 on chrome, it works like a charm.
