### ISSUE TITLE
HTOP显示问题

### ISSUE THREAD

**Issue by wwqgtxx** [tsl0922/ttyd#40]
在Chrome56下显示错位
![image](https://cloud.githubusercontent.com/assets/582584/23147333/1775d8a0-f819-11e6-9a45-1d411df5c2f1.png)
![image](https://cloud.githubusercontent.com/assets/582584/23147350/462d2964-f819-11e6-9475-28767974c3f2.png)
![image](https://cloud.githubusercontent.com/assets/582584/23147369/5e94fdc4-f819-11e6-9f28-24f54209aad9.png)

```
Google Chrome	56.0.2924.87 (正式版本) m （64 位）
修订版本	0e9a9a6f3676ae439b78cd9b3f62b4193c3ac7d5-refs/branch-heads/2924@{#895}
操作系统	Windows 
JavaScript	V8 5.6.326.50
Flash	24.0.0.221 C:\Users\Administrator\AppData\Local\Google\Chrome\User Data\PepperFlash\24.0.0.221\pepflashplayer.dll
用户代理	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
命令行	"C:\Users\Administrator\AppData\Local\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end
```
在chrome53下也是同样错位
![image](https://cloud.githubusercontent.com/assets/582584/23147462/08d19b1c-f81a-11e6-98ec-6ca91b78239c.png)
![image](https://cloud.githubusercontent.com/assets/582584/23147466/133e18be-f81a-11e6-90fc-3a9e1dde067f.png)

在firefox下显示一切正常
![image](https://cloud.githubusercontent.com/assets/582584/23147391/824724a4-f819-11e6-9168-cb061fd0a1a3.png)
![image](https://cloud.githubusercontent.com/assets/582584/23147417/ae908578-f819-11e6-9f8d-003e6cce6309.png)

在IE11下也正常
![image](https://cloud.githubusercontent.com/assets/582584/23147437/e20e3cb0-f819-11e6-9652-f43ca5308613.png)

**Comment by wwqgtxx** [comment]
然而在ubuntu下的chromium55下一切正常
![image](https://cloud.githubusercontent.com/assets/582584/23147663/a651519c-f81b-11e6-8ce9-66860fcd1f5e.png)
![image](https://cloud.githubusercontent.com/assets/582584/23147672/adea35c2-f81b-11e6-9aec-5c7bcf3239e4.png)
![image](https://cloud.githubusercontent.com/assets/582584/23147680/bb9199a4-f81b-11e6-9964-84571d310484.png)

**Comment by tsl0922** [comment]
OK，等我找到 windows 环境测试一下。

**Comment by tsl0922** [comment]
确定是字体（font-family）设置问题，已在 master 分支修复。

**Comment by wwqgtxx** [comment]
恩已经确定正常了
