### ISSUE TITLE
Documentation: Make it clear and explicit in the README which arm binary version to download

### ISSUE THREAD

**Issue by m040601** [tsl0922/ttyd#417]
Thank you so much for your work in this tool !

Like many others in the last years,
I also can attest that ttyd works perfectly in the many
various arm architectures, armv5 armv6 v7 etc.

They match various popular devices like the various Raspberry models, Pi2 Pi3 PiZero.

The release page, listing the precompiled binaries, https://github.com/tsl0922/ttyd/releases, however only list 3 different arm types.

> ttyd_linux.aarch64
> ttyd_linux.arm
> ttyd_linux.armhf

This maybe sufficient though, as one can, for example use the binary "arm"  or "armhf" in some of the other armvXXX. And of course aarch64 is only for Raspberry 64 bit versions.

But which  one exactly is the information missing.

 It would help a lot if you could simply add a few lines in the README page at least, helping arm users choose the correct version.

I understand that it might be  hard to you , to  maintain binaries for all many different ARM versions by default.And that you might not want to make the file list in the releases page too long.

But could you add this information to the README page ?
Something like

> ....use the 'arm' XYZ version if you're not sure...
or
> ... use the 'armv XYZ in the Raspberry Pi zero ....

Thanks in advance

**Comment by tsl0922** [comment]
If you run `file ttyd_linux.arm`:

```
ttyd_linux.arm: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, stripped
```

The arm version is built against armv5 ABI, which should works on v6/v7, since they are backward compatible.

**Comment by m040601** [comment]
`If you run file ...
`
yes, that's what I had to do before using ttyd and opening this issue.

`The arm version is built against armv5 ABI, which should works on v6/v7`
yes, thats also what I discovered you choose to do, after spending some time browsing the issues.


Is it too much to ask to writes this in the README page ? It will save others the time I spent.

**Comment by tsl0922** [comment]
If you'd like to open a PR for it, I'll be happy to merge. Or you can share your experience on the wiki, it's public editable.
