### ISSUE TITLE
Programs that do not immediately output cause the session to close prematurely

### ISSUE THREAD

**Issue by a1291762** [tsl0922/ttyd#418]
**Describe the bug**
ttyd receives periodic LWS_CALLBACK_SERVER_WRITEABLE events after the connection starts. If the process that ttyd spawns does not write something before this happens, the code incorrectly assumes that an error occurred.

    // read error or client exited, close connection
      if (proc->status == 0 || proc->pty_len == 0) {
        lws_close_reason(wsi, LWS_CLOSE_STATUS_NORMAL, NULL, 0);
        return 1;

**To Reproduce**
1. Run ttyd with a program that does not write output immediately (eg. picocom -q /dev/ttyS1)
2. Point the browser at ttyd

**Expected behavior**
The session starts and runs as normal (ie. waits for data from the program or input from the user)

**Environment:**
 - OS: Linux (embedded distro based on Yocto)
 - Browser: Firefox

**Additional context**
Setting pty_len to a value other than 0 during initialization, ttyd correctly waits for the program to output something. I created the attached patch that solves the problem for me.

[Support-programs-that-do-not-immediately-write.txt](https://github.com/tsl0922/ttyd/files/4979369/Support-programs-that-do-not-immediately-write.txt)

**Comment by tsl0922** [comment]
Yes, It's an issue 👍   

PRs are welcomed.

**Comment by tsl0922** [comment]
Should be fixed by f9d23de0fed1cf9bf5b57ecf14017ac494c69691
