### ISSUE TITLE
长时间运行出现ERROR：pthread_create

### ISSUE THREAD

**Issue by wwqgtxx** [tsl0922/ttyd#42]
之前运行一切正常，然后过了一个晚上就无法建立连接了，看了一下后台日志，都是`ERROR：pthread_create`
![image](https://cloud.githubusercontent.com/assets/582584/23238287/2b420a78-f99c-11e6-86f4-67a739f4efc8.png)

**Comment by tsl0922** [comment]
pthread_create 出错了，这里没有 log 出返回值所以也不是很好判断原因，已经在代码里添加更详细的 log，你更新到最新的 master，如果下次再遇到这种情况更好通过日志判断问题些。

**Comment by tsl0922** [comment]
无法重现，先关闭了，如果再遇到请在这里接着反馈。
