### ISSUE TITLE
SSL mode use WSS

### ISSUE THREAD

**Issue by vegalou** [tsl0922/ttyd#422]
http mode works correctly. in http mode, browser allow WS:// connection to ttyd daemon.

SSL-Reverse proxy could cover SSL security via NGINX or APACHE, 

If in SSL mode, browser connection to ttyd daemon should use WSS instead of WS.

`Only Firefox block the WS connection for security concern(?), works functionaly in OPERA & CHROME.`

**Comment by tsl0922** [comment]
https://github.com/tsl0922/ttyd/blob/master/html/src/components/app.tsx#L11-L13

It should already use wss, any reproduce steps?

**Comment by vegalou** [comment]
`tsl0922`, Thanks for your reply. 

Open browser in debug mode, the URL in **https://** but the network protocol is in **http://** request
and the socket open to WS://

ver: 1.61 linux (x64) binary download.

I will manual compile from SOURCE later.

Thanks again!!

**Comment by tsl0922** [comment]
There's already an issue about SSL on Firefox (#226), I just fixed it on master.

Could you check if it works for you?

**Comment by vegalou** [comment]
@tsl0922 , thanks for your reply.
I'd compile source manually yesterday, in server.h needs `uv.h` not found.
Followed the MD needs more luck and google. (Ubuntu 14.04)

Regards.

**Comment by tsl0922** [comment]
You can download a prebuilt binary from the ci:

https://github.com/tsl0922/ttyd/actions/runs/185849726

**Comment by tsl0922** [comment]
or, take a look at: https://github.com/tsl0922/ttyd/blob/master/.github/workflows/backend.yml#L18

**Comment by vegalou** [comment]
THANKS! @tsl0922

**Comment by nguarracino** [comment]
@tsl0922 Do you have plans for a release containing this fix? I am using the arm build but it looks like the CI cross builds do not include SSL support?
