### ISSUE TITLE
Possible to change the default alt key functionality?

### ISSUE THREAD

**Issue by dschartman** [tsl0922/ttyd#423]
Alt seems to start up a capture mode.  Is it possible to turn this off?  I use the alt key for a lot of short cuts.  Thank you.

**Comment by tsl0922** [comment]
what is "capture mode"? It's possible to change key functionality, but not exposed with any option on ttyd. you may wan't to read the [xterm.js document](https://xtermjs.org/docs/api/terminal/classes/terminal/#attachcustomkeyeventhandler).

**Comment by dschartman** [comment]
Whenever you press alt, the cursor changes to a crosshair that allows you to drag and select text to copy.  Thank you for the response.  I'll dig into xterm.
