### ISSUE TITLE
-t titleFixed=value gives unexpected results for certain strings

### ISSUE THREAD

**Issue by spurin** [tsl0922/ttyd#425]
Hi,

Firstly, thanks for your efforts with ttyd, it's amazing 👍 

I've been trying out the -t titleFixed options, as per the recent pull request context.  It's working well but, I noticed a couple of times when using the hostname as a title that the output wasn't as expected, some examples -

-t titleFixed=12e31b9d8fc2      (Results in a scientific notation in the title, specifically 1.2e+32)
-t titleFixed=0a283a15eace     (Results in the value 0, in the title)

Hope this helps

- James

**Comment by tsl0922** [comment]
for `-t key=value` option, the value will be [parsed](https://github.com/tsl0922/ttyd/blob/master/src/server.c#L429) as a json object with [json-c](http://json-c.github.io/json-c/). 

The value you passed may be treated as hex digit by json-c. using `-t titleFixed='"12e31b9d8fc2"'` should work.

**Comment by spurin** [comment]
Thanks, closing issue
