### ISSUE TITLE
Option to turn off of overlay message for screen size

### ISSUE THREAD

**Issue by infinyte7** [tsl0922/ttyd#446]
**Is your feature request related to a problem? Please describe.**

I have implemented ttyd in termux to be used inside AnkiDroid in iframe but every time get overlay message of screen size. 

**Describe the solution you'd like**
Option like ```-t disableOverlayMessage``` 

**Describe alternatives you've considered**
No alternative.

**Additional context**
![](https://github.com/infinyte7/Anki-Custom-Card-Layout/blob/master/images/demo_example_3.gif?raw=true)

**Comment by tsl0922** [comment]
Added support on master(7e0f8061cbf88cbe819805dfe58cf81105eddf6c), usage:

```bash
ttyd -t disableResizeOverlay=true bash
```

**Comment by infinyte7** [comment]
Thanks

**Comment by psgganesh** [comment]
This -t disableResizeOverlay=true does not seem to work even when run with -t option nor on the browser with http://localhost:7681/?fontSize=24&disableLeaveAlert=true&rendererType=canvas&disableResizeOverlay=true&theme={%22background%22:%20%22green%22}
