### ISSUE TITLE
error: 'struct lws_context_creation_info' has no member named 'ws_ping_pong_interval'

### ISSUE THREAD

**Issue by itamarjp** [tsl0922/ttyd#475]
Fails to build 

https://kojipkgs.fedoraproject.org//work/tasks/7375/51317375/build.log

CMakeFiles/ttyd.dir/src/utils.c.o -c /builddir/build/BUILD/ttyd-1.6.1/src/utils.c
[ 83%] Building C object CMakeFiles/ttyd.dir/src/http.c.o
[ 83%] Building C object CMakeFiles/ttyd.dir/src/protocol.c.o
/usr/bin/gcc -DTTYD_VERSION=\"1.6.1\" -I/usr/include/json-c -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -D_GNU_SOURCE -std=gnu99 -o CMakeFiles/ttyd.dir/src/terminal.c.o -c /builddir/build/BUILD/ttyd-1.6.1/src/terminal.c
/usr/bin/gcc -DTTYD_VERSION=\"1.6.1\" -I/usr/include/json-c -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -D_GNU_SOURCE -std=gnu99 -o CMakeFiles/ttyd.dir/src/protocol.c.o -c /builddir/build/BUILD/ttyd-1.6.1/src/protocol.c
/usr/bin/gcc -DTTYD_VERSION=\"1.6.1\" -I/usr/include/json-c -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -D_GNU_SOURCE -std=gnu99 -o CMakeFiles/ttyd.dir/src/http.c.o -c /builddir/build/BUILD/ttyd-1.6.1/src/http.c
/builddir/build/BUILD/ttyd-1.6.1/src/server.c: In function 'main':
/builddir/build/BUILD/ttyd-1.6.1/src/server.c:453:7: error: 'struct lws_context_creation_info' has no member named 'ws_ping_pong_interval'
  453 |   info.ws_ping_pong_interval = 5;
      |       ^
gmake[2]: *** [CMakeFiles/ttyd.dir/build.make:85: CMakeFiles/ttyd.dir/src/server.c.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: Leaving directory '/builddir/build/BUILD/ttyd-1.6.1/x86_64-redhat-linux-gnu'
gmake[1]: Leaving directory '/builddir/build/BUILD/ttyd-1.6.1/x86_64-redhat-linux-gnu'
gmake[1]: *** [CMakeFiles/Makefile2:98: CMakeFiles/ttyd.dir/all] Error 2
gmake: *** [Makefile:152: all] Error 2
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.AqLG9Z (%build)
    Bad exit status from /var/tmp/rpm-tmp.AqLG9Z (%build)
Child return code was: 1

**Comment by tsl0922** [comment]
It's already fixed on master, but not released yet (see also #452).
