### ISSUE TITLE
Prevent ttyd from restarting the program on exit

### ISSUE THREAD

**Issue by joehakimrahme** [tsl0922/ttyd#478]
Hi, I'm using ttyd to launch `/bin/bash` inside a container. When exiting bash (either by entering `exit` or `C-d`), ttyd automatically clears the terminal and relaunch bash.

How can I make it so that bash doesn't restart and the screen output remains untouched?

Here's the command I use:
```
ttyd -p 8080 bash
```

More info:

```
[root@0494e00e4ad4 app]# ttyd --version
ttyd version 1.6.0
```

Installed form the Fedora32 package:

```[root@0494e00e4ad4 app]# dnf list installed | grep ttyd
ttyd.x86_64                        1.6.0-1.fc32                     @updates      ```

**Comment by africanzoe** [comment]
I have the same problem/request.

**Comment by tsl0922** [comment]
possible, but it's hardcoded:

https://github.com/tsl0922/ttyd/blob/master/html/src/components/terminal/index.tsx#L203

**Comment by tsl0922** [comment]
Added a client option (on master) to disable it, usage: `ttyd -t disableReconnect=true bash`.
