### ISSUE TITLE
Integrate TTYD with simple Web based editors/IDE like Monaco-editor? [Help]

### ISSUE THREAD

**Issue by r3ver53r** [tsl0922/ttyd#482]
Can someone help give pointers on how can we integrate TTYD with web based coding editors like Monaco editors for any computer language say Python? 

Is it something that can be explored via --index flag?

**Comment by tsl0922** [comment]
You may want to try [node-pty](https://github.com/Microsoft/node-pty) + [xterm.js](https://github.com/xtermjs/xterm.js) like what vscode did.

**Comment by r3ver53r** [comment]
Hi @tsl0922 , Do you mean integrating [Monaco editor](https://github.com/Microsoft/monaco-editor) with node-pty + xterm.js (and TTYD can not be re-used)?

**Comment by tsl0922** [comment]
If you want to custom the server side logic, I would not recommend using ttyd, since the code is C based.

see also #341

**Comment by r3ver53r** [comment]
Got it. Thnaks @tsl0922
