### ISSUE TITLE
ppa using outdated libwebsockets

### ISSUE THREAD

**Issue by breeswish** [tsl0922/ttyd#49]
binary in PPA is using an outdated libwebsockets so that `setgid` is not called before `setuid` and a privilege drop may fail:

https://github.com/warmcat/libwebsockets/commit/0a9bd7e9714bf9c59b9321791f5471ee31aeb8d4

**Comment by tsl0922** [comment]
You may wan't to compile it yourself, the PPA is just for convenience, so it uses the `libwebsockets` package from official ubuntu repository.

**Comment by breeswish** [comment]
Thanks
