### ISSUE TITLE
Release upcoming?

### ISSUE THREAD

**Issue by nguarracino** [tsl0922/ttyd#490]
I'm looking for a build with the fix for https://github.com/tsl0922/ttyd/issues/226

Tried the CI builds but it appears they do not include SSL support. Is there a release planned any time soon?

**Comment by raphaelvigee** [comment]
+1

**Comment by thannaske** [comment]
Is this project dead?

**Comment by tsl0922** [comment]
https://github.com/tsl0922/ttyd/releases/tag/1.6.2
