### ISSUE TITLE
Is there a way to import the frontend as a component in react app

### ISSUE THREAD

**Issue by SabariVig** [tsl0922/ttyd#492]
Is there a way to import the frontend as a component in react app, 
I tried but i get some webpack errors

**Comment by tsl0922** [comment]
the frontend is based on [preact](https://preactjs.com/), which has a [compatibility layer](https://github.com/preactjs/preact-compat) for react, I don't know if react has one for preact.

**Comment by SabariVig** [comment]
is it possible that you could publish built version this package to npm and then it would be possible?

**Comment by tsl0922** [comment]
Nope. The frontend is not intended to be a react library: 

1. it's based on preact, I won't port it to react
2. I don't have time to maintain 2 version of the frontend
