### ISSUE TITLE
too many dependencies

### ISSUE THREAD

**Issue by tylerlong** [tsl0922/ttyd#5]
https://ruby-china.org/topics/31081

> 找了一下类似的程序，发现了 Wetty 和 GoTTY，但是 Wetty 需要 node 运行环境， GoTTY 编译后的二进制文件太大，多数路由器的 flash 都比较小，不适合集成到路由器固件里。

![image](https://cloud.githubusercontent.com/assets/733544/18613801/6f39c068-7db4-11e6-86d2-75ab7969a2e0.png)

加上这些依赖，应该比GoTTY不小啊。

**Comment by tsl0922** [comment]
你截图里很多的依赖都是编译时需要的，真正运行时不需要那么多的，C 的 runtime 系统都有，而且编译出来的二进制文件也会小很多。
