### ISSUE TITLE
Client is automatically reconnected after typing `exit`

### ISSUE THREAD

**Issue by breeswish** [tsl0922/ttyd#50]
By typing `exit`, the client should go into a "never connect again" state and should prevent it from reconnecting..

**Comment by Aydonl** [comment]
Using arg *--once* , By typing **exit**, the client automatically reconnect ,and close client the server never exit too...

**Comment by tsl0922** [comment]
@Aydonl this is a known bug which has been fixed by 35c97df863f6eff64796359703e42a5125bb147a on master

**Comment by Aydonl** [comment]
Oh,Thanks for your reply. I'm going to build and have a try... @tsl0922
