### ISSUE TITLE
unrecognized option '--reconnect'

### ISSUE THREAD

**Issue by nnocetti** [tsl0922/ttyd#503]
Reconnect option not working.

root@7713654067ef:/app/src# ttyd -p 5000 -a --reconnect 0 --readonly pytest
ttyd: unrecognized option '--reconnect'

**Comment by brianredbeard** [comment]
As you're trying to set it to `0` (disabling re-connect as per #180) there is nothing you should need to configure.  This option was removed in 0fc275f3a3251f1839a2e59d04011f6a4e41541c ([diff-b3356305](https://github.com/tsl0922/ttyd/commit/0fc275f3a3251f1839a2e59d04011f6a4e41541c#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L83.)).

**Comment by tsl0922** [comment]
The old reconnect option is replaced with exponential backoff now, unfortunately it can't be disabled now.
