### ISSUE TITLE
100% cpu usage when running in background

### ISSUE THREAD

**Issue by cdr8H** [tsl0922/ttyd#504]
**ttyd without any IO is eating 100% of cpu**

running in background: ttyd -u 1000 -c my_user:my_password -p **** /bin/bash >/var/log/my_log 2>&1 &

not reproducible - sometimes happen also when the client is idle (no IO) ...

**Log Output:**           
<img width="680" alt="ttyd" src="https://user-images.githubusercontent.com/6630333/95642753-bc9c2580-0aaa-11eb-8534-3ff67fbe1aef.png">

ttyd 1.6.1-fc037fe (libwebsockets 2.0.3)
tty configuration:
  credential: **************
  start command: /bin/bash
  close signal: SIGHUP (1)
  terminal type: xterm-256color
Initial logging level 7
Libwebsockets version: 2.0.3 unknown-build-hash
IPV6 not compiled in
libev support compiled in but disabled
libuv support compiled in and enabled
 Threads: 1 each 1024 fds
 mem: platform fd map:  4096 bytes
 Compiled with OpenSSL support
 SSL disabled: no LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
Creating Vhost 'default' port ****, 2 protocols
 Listening on port ****
 mem: per-conn:          600 bytes + protocol rx buf
 canonical_hostname = s1
Set privs to user '*****'
 Listening on port: *****
 Using foreign event loop...
lws_protocol_init
HTTP / - 192.168.100.110
HTTP /token - 192.168.100.110
WS   /ws - 192.168.100.110, clients: 1
started process, pid: 8975

**Environment:**
 - OS: Debian stretch 9.13
 - Browser: [Firefox 81.0 Win64]

**Comment by tsl0922** [comment]
Can't reproduce, feel free to reopen if you can reproduce it.
