### ISSUE TITLE
ttyd automatically closes connection in HTTPS mode

### ISSUE THREAD

**Issue by Stovent** [tsl0922/ttyd#514]
**Describe the bug**
After connecting in HTTPS, the connection closes itself automatically.
This only happens in HTTPS. HTTP works fine.
The certificate is a self-signed certificate generated with openSSL.
Build is compiled from master branch.
Without the --once option, the connection regulary closes but the page automatically reloads and creates a new connection.

**To Reproduce**
1. Start ttyd with SSL parameters : ``ttyd -o -S -C cert.pem -K key.pem sh``
2. Open the shell in your brower ``https://localhost:7681``
3. After a few seconds, the socket will close itself automatically.

**Screenshots**
See in the picture, I did not typed anything in the browser except the enter key and the connection closes itself.
![image](https://user-images.githubusercontent.com/23307724/97184367-1d13ae00-179f-11eb-8f78-e2170f10cbb8.png)

**Environment:**
 - OS: Ubuntu 20.04.1
 - Browser: Firefox 82.0 64-bit

**Comment by tsl0922** [comment]
> exiting due to the --once option

Remove `-o` and try again.
