### ISSUE TITLE
Terminal User Directory

### ISSUE THREAD

**Issue by capriciousduck** [tsl0922/ttyd#517]
Describe your problem or question here.

By default the root user directory is set to "/". Every time I had to use "cd /root" to go to root folder. How do I fix this?

**Comment by tsl0922** [comment]
You can `cd` to `/root` first before running ttyd, or if you're using the docker image: add `-w /root` to `docker run`.

**Comment by capriciousduck** [comment]
Is it not possible to specify it in the dockerfile itself? Because I run this app on Heroku, it is not possible to pass that argument.

**Comment by tsl0922** [comment]
It's possible, just specify [WORKDIR](https://docs.docker.com/engine/reference/builder/#workdir) in dockerfile.

**Comment by capriciousduck** [comment]
All right. Will check.

**Comment by capriciousduck** [comment]
Thanks. It worked. Closing the issue now.
