### ISSUE TITLE
Add LibreSSL support

### ISSUE THREAD

**Issue by WSLUser** [tsl0922/ttyd#524]
**Is your feature request related to a problem? Please describe.**
In the README, it shows this project uses OpenSSL. I'd like to see other SSL options be supported as well. For me particularly, I'd like to see [LibreSSL](https://github.com/libressl-portable/portable) support, which is a more secure forked version of OpenSSL.
**Describe the solution you'd like**
Use LibreSSL instead of OpenSSL
**Describe alternatives you've considered**
Attempt to link to LibreSSL and fix any incompatibilities as OpenSSL is not completely interchangeable with LibreSSL.
**Additional context**

**Comment by tsl0922** [comment]
PRs are welcomed. It should be pretty easy to add LibreSSL support, since libwebsockets already had support for it.

**Comment by WSLUser** [comment]
Not sure how helpful it might be but here's the link to the PR that switched win32-openssh from OpenSSL to LibreSSL: https://github.com/PowerShell/openssh-portable/pull/166/files. Maybe someone can get some inspiration from it.

**Comment by tsl0922** [comment]
Since libressl is forked from openssl, ttyd uses few openssl apis directly, it should not be incompatible with libressl, so this issue is mainly upstream aware, you may want to open issue on libwebsockets side if it do not works.

FYI: I've tried to build the latest version of libwebsockets with libressl, but it fails.

```
[ 28%] Building C object lib/CMakeFiles/websockets.dir/tls/openssl/openssl-server.c.o
/opt/build/x86_64-linux-musl/libwebsockets-4.1.6/lib/tls/openssl/openssl-server.c: In function ‘lws_tls_server_vhost_backend_init’:
/opt/build/x86_64-linux-musl/libwebsockets-4.1.6/lib/tls/openssl/openssl-server.c:511:3: error: implicit declaration of function ‘SSL_CTX_set_ciphersuites’; did you mean ‘SSL_CTX_set_cipher_list’? [-Werror=implicit-function-declaration]
  511 |   SSL_CTX_set_ciphersuites(vhost->tls.ssl_ctx,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
      |   SSL_CTX_set_cipher_list
cc1: all warnings being treated as errors
```

**Comment by WSLUser** [comment]
So you should be able to provide a LibreSSL release if you've updated your dependency to v4.2 or later for libwebsocket. Noticed you added Windows support, which is awesome. Could you set up using libressl by default to remove the contact CVE exposure and fall back to openssl on for systems that don't have libressl installed? (Enhancment would be to provide warning to install libressl and offer some script command to switch the backend.)
