### ISSUE TITLE
Quick question regarding modding

### ISSUE THREAD

**Issue by CatSandwich** [tsl0922/ttyd#534]
Hey there, I'm trying to mod ttyd to add a custom xterm addon but changing the typescript code doesn't seem to do anything. How do I get ttyd to run my forked instance rather than the default?

I know there's an option to set a custom index so it might be something related to that, but some guidance would be appreciated.

Thanks in advance.

**Comment by CatSandwich** [comment]
I did a bit more research and I see that the .js file generates html.h which serves the webpage. I guess that makes my question how do I modify the webpage that creates (Probably just change the typescript code) and how do I then run it to build html.h?

**Comment by CatSandwich** [comment]
I see now the instructions are in the html folder. I'll leave this issue open for now but I may solve it and close in in the next few hours.

**Comment by pawansingh00** [comment]
@CatSandwich sorry to bother you.
I am having the similar needs and your issue and comments helped in understanding that -- html.h is what is being used and how to generate it.

But even after doing this its still taking deafult build.

Do I need to change any git branch / tag somewhere like -- **CMakeLists.txt**

Appreciate your help.
