### ISSUE TITLE
Latest Chrome Requires SAN field in SSL certificate

### ISSUE THREAD

**Issue by breeswish** [tsl0922/ttyd#54]
It would be better to update the openssl commands in README to conform this change. Otherwise generated certificate will not be accepted by latest Google Chrome.

**Comment by tsl0922** [comment]
Thanks, I didn't test this. Can you give me more details, or open a PR for this?

**Comment by breeswish** [comment]
Maybe you could refer to this blog post: https://alexanderzeitler.com/articles/Fixing-Chrome-missing_subjectAltName-selfsigned-cert-openssl/

Also there are some advice of generating fully from command line (no additional file required): https://security.stackexchange.com/questions/74345/provide-subjectaltname-to-openssl-directly-on-command-line

**Comment by tsl0922** [comment]
References:

- https://www.chromestatus.com/feature/4981025180483584
- https://groups.google.com/a/chromium.org/forum/#!topic/security-dev/IGT2fLJrAeo

I'll update the README soon.
