### ISSUE TITLE
Seems to ignore -u and -g

### ISSUE THREAD

**Issue by fancsali** [tsl0922/ttyd#540]
**Describe the bug**
Running `ttyd` seems to ignore `-u` and `-g`.

**To Reproduce**
Built from source (0abce05) on Raspbian witout any issues. However running:

```
sudo ttyd -i lo -u nobody -g nogroup login -h TTYD
```

Will still run as root:

```
$ ps aux | egrep 'ttyd'
root      3929  0.0  0.3   9948  3136 pts/0    S+   18:00   0:00 sudo ttyd -i lo -u nobody -g nogroup login -h TTYD
root      3934  0.1  0.3   7464  3376 pts/0    S+   18:00   0:00 ttyd -i lo -u nobody -g nogroup login -h TTYD
pi        3961  0.0  0.0   7348   488 pts/1    S+   18:01   0:00 grep -E --color=auto ttyd
```

**Expected behavior**
Well, I'd expect the binary to drop privileges.

**Environment:**
 - OS: Raspbian/RaspberryOS 10.6
 - Browser: -

**Additional context**
As a sidenote: not sure how this should be ran to be both secure, and let it run `login`.

**Comment by tsl0922** [comment]
Hi, you should give an **id** to them.
