### ISSUE TITLE
Ignores rendererType

### ISSUE THREAD

**Issue by fancsali** [tsl0922/ttyd#541]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot 2020-11-13 at 19 20 31](https://user-images.githubusercontent.com/1670136/99112327-652b3100-25e5-11eb-9fc3-a68d007924db.png)

**Environment:**
 - OS: Raspbian/RaspberryOS 10.6
 - Browser: TorBrowser 10.0.4 (based on Mozilla Firefox 78.4.0esr) (64-bit)

**Comment by tsl0922** [comment]
I don't use TorBrowser, and it's not been officially supported by [xterm.js](https://github.com/xtermjs/xterm.js#browser-support).

To check if webgl is used on the context, call `.getContext('webgl2')` on the canvas element, it will return a `WebGL2RenderingContext `.
