### ISSUE TITLE
Question in UNIX domain socket support

### ISSUE THREAD

**Issue by simonsmh** [tsl0922/ttyd#55]
我在使用此程序时，想选用unix socket，但是使用时报
`libwebsockets is not compiled with UNIX domain socket support`
我已经在编译时启用Unix support.
```
git clone https://anonscm.debian.org/git/collab-maint/libwebsockets.git -b debian-v2.0-stable
cd libwebsockets
git fetch
git reset --hard origin/debian-v2.0-stable
sed -i 's/-DLWS_WITH_LIBUV=ON/-DLWS_WITH_LIBUV=ON -DLWS_IPV6=ON -DLWS_UNIX_SOCK=ON -DLWS_WITH_HTTP2=ON/g' debian/rules
dpkg-buildpackage -b -uc -us

**Comment by simonsmh** [comment]
此外Debian version没有跟进到1.3.2

**Comment by tsl0922** [comment]
这个提示是编译时就生成了的，如果 ttyd 编译时使用的 libwebsockets 没有开启 UNIX domain socket 支持，即使运行时的 libwebsockets 库是支持的也不行。

**Comment by simonsmh** [comment]
debiancn提供了重新打包的的libwebsockets，编译时可以换用。

**Comment by simonsmh** [comment]
如果我想在使用Unix socket时不想监听端口，我该怎么做？

**Comment by tsl0922** [comment]
目前无法禁止，这应该算是 bug，我本不打算让两者共存。

**Comment by simonsmh** [comment]
好吧，希望能尽快修复🤣

Shuanglei Tao <notifications@github.com>于2017年4月29日周六 09:12写道：

**Comment by tsl0922** [comment]
@simonsmh 你测试过吗？我刚在 linux 下测试了下，貌似没这个问题，只要开启了 unix sock 就不会再监听 tcp 端口了。

**Comment by simonsmh** [comment]
socks路径到底是`-i`还是`-p`啊
`-i`确实会监听默认端口
刚刚测试了一下`-p`倒是正常的

**Comment by tsl0922** [comment]
是 `-i` 呀，`-p` 只能接收整数。

**Comment by simonsmh** [comment]
哦哦哦 是我sock路径后面多加了个s

**Comment by tsl0922** [comment]
unix socket 扩展名只能用 `.sock` 或者 `.socket`，目前是这么识别的。

**Comment by simonsmh** [comment]
好的，现在知道了
其实还是希望有更多的错误提示之类的（
