### ISSUE TITLE
SSL options missing on 1.6.2

### ISSUE THREAD

**Issue by thannaske** [tsl0922/ttyd#558]
**Describe the bug**
SSL options are missing

**To Reproduce**
1. Download version 1.6.2
2. Execute `ttyd --help`
3. SSL-related options like `-S` are missing and not working

**Expected behavior**
The options should be there.

**Screenshots**
Kind of:
```root@bastion:/opt/ttyd# diff ttyd-1.6.2 ttyd-1.6.1
7c7
<     1.6.2-a109730
---
>     1.6.1-079aa68
26d25
<     -P, --ping-interval     Websocket ping interval(sec) (default: 300)
27a27,30
>     -S, --ssl               Enable SSL
>     -C, --ssl-cert          SSL certificate file path
>     -K, --ssl-key           SSL key file path
>     -A, --ssl-ca            SSL CA file path for client certificate verification
```

**Environment:**
Ubuntu 18.04 (amd64 build)

**Comment by tsl0922** [comment]
SSL is not built by default on release artifacts now, to reduce the binary size.

You can always build it using the same script (`scripts/cross-build.sh`) with `WITH_SSL=true` env.
