### ISSUE TITLE
Typing rendering issue with powershell command

### ISSUE THREAD

**Issue by dmilov** [tsl0922/ttyd#562]
I'm running release 1.6.2. 
Running `bash` command has no issues.
![image](https://user-images.githubusercontent.com/10736688/102357660-3d9a0080-3fb7-11eb-8f2d-925468f78d6b.png)

Running `powershell ` command displays the previous characters on every new character typing.
![image](https://user-images.githubusercontent.com/10736688/102357595-29ee9a00-3fb7-11eb-95ea-c202138ca813.png)

Is there a setting I can play with to make it work for PowerShell? I suppose is a latency issue somehow. I'm running ttyd in a container behind a proxy.

**Comment by ravermeister** [comment]
I think I've seen a [Client option](https://xtermjs.org/docs/api/terminal/interfaces/iterminaloptions/#optional-windowsmode) for Windows terminals, you Could try to set it see [windowsMode](https://xtermjs.org/docs/api/terminal/interfaces/iterminaloptions/#optional-windowsmode)

so minimal startup would be:   
`ttyd -t 'windowsMode=true' powershell.exe`

**Comment by dmilov** [comment]
thanks for the suggestion, it doesn't work though. The weirdest thing is if I run `bash` command and then in the browser start PowerShell from bash it works fine. If I start `powershell` command with ttyd I reproduce it.

**Comment by ravermeister** [comment]
hmm so does this work? `ttyd bash -c 'powershell' `

**Comment by dmilov** [comment]
no, this doesn't work. Only if I run `ttyd bash` then in the browser I start `powershell` from bash, which doesn't solve my use-case because I want to start powershell with some parameters and have it in the browser. 

I tested the `gotty` tool which is working fine in the same setup. It has other issues though. `ttyd` is the right tool for me but have to figure out how to make it work in this setup.

**Comment by ravermeister** [comment]
did you try to create a shell script with `bash -c "/full/path/to/powershell args"` and execute this script in ttyd?

**Comment by dmilov** [comment]
I did.

**Comment by dmilov** [comment]
I managed to reproduce the same building it from code into a docker container. 
Docker file is
```
FROM ubuntu:18.04
RUN apt-get update && apt-get install -y autoconf automake curl cmake git libtool make \
    && git clone --depth=1 https://github.com/tsl0922/ttyd.git /ttyd \
    && cd /ttyd && env BUILD_TARGET=x86_64 WITH_SSL=true ./scripts/cross-build.sh

FROM photon:3.0

RUN tdnf install powershell -y

COPY --from=0 /ttyd/build/ttyd /usr/bin/ttyd

ADD https://github.com/krallin/tini/releases/download/v0.18.0/tini /sbin/tini
RUN chmod +x /sbin/tini

EXPOSE 8086
WORKDIR /root

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["ttyd", "-p", "8086", "pwsh"]
```

I run the container with
```bash
 docker run -p 8086:8086 ttyd
```
and test on the same machine.

If I replace 'pwsh' with 'bash' in the Dockerfile it works.

**Comment by dmilov** [comment]
When base OS is Ubuntu there is no issue. This is some corner case. If somebody can give some suggestion what could be the reason.

**Comment by dmilov** [comment]
`-T linux` option solves the problem. Thanks to @dcasota
