### ISSUE TITLE
close or refresh webpage trigger crash through nginx proxy

### ISSUE THREAD

**Issue by flashlab** [tsl0922/ttyd#563]
**Describe the bug**
Start ttyd.x86_64(1.6.2) under Ubuntu 18.04.4 through 'ttyd -p 8080 bash', config nginx(1.14.0) following the wiki instruction.
Then open with Chrome or Edge, If I close or refresh the page, the log says:
```
WS closed from 127.0.0.1, clients: 0
killing process 26637 with signal: 1 (SIGHUP)
process killed with signal 1 (SIGHUP), pid: 26637
Segmentation fault
```
**To Reproduce**
1. Go to 'https://domains.org/ttyd'
2. Click on 'refresh' or close tab
3. Crash

**Expected behavior**
No crash after hard refresh or close.

**Screenshots**

**Environment:**
 - OS: Ubuntu 18.04.4
 - Browser: Any

**Additional context**
I've did some test and excluded the relation to https or subdomain. If use IP to access ttyd, the issue disappeared.

**Comment by ravermeister** [comment]
Seems #557 ist describing the same thing and finally lead to #491

**Comment by tsl0922** [comment]
Should be fixed on master now (5650606674bb98d5f65aebf84f834a9c0913287c).

**Comment by tsl0922** [comment]
@flashlab @ravermeister can you check if the binary from this ci build works? thanks

https://github.com/tsl0922/ttyd/actions/runs/446529650

**Comment by flashlab** [comment]
@tsl0922 It has been solved following the link you provide :grinning:
:+1::+1:

**Comment by ravermeister** [comment]
@tsl0922 confirmed, I tested the `ttyd.aarch64` and it is working perfectly well thanks!
