### ISSUE TITLE
Connection Closed overlay doesn't automatically disappear

### ISSUE THREAD

**Issue by dmartin** [tsl0922/ttyd#564]
**Describe the bug**
The "Connection Closed" overlay message doesn't disappear after automatically reconnecting, unless it is replaced by another message, such as the resize message or the "Copy" icon.

This is most noticeable when the resize message is disabled (`-t disableResizeOverlay=true`).

**To Reproduce**
1. Start ttyd with some command that will exit and close the connection and `-t disableResizeOverlay=true`
1. "Connection Closed" is displayed
1. Web terminal automatically reconnects
1. Message is not cleared until another event (like copy/paste) occurs

**Expected behavior**
Message automatically disappears like the resize message.

**Screenshots**
N/A

**Environment:**
 - OS: macOS 11.0.2
 - Browser: Chrome 87.0.4280.88

**Additional context**
N/A

**Comment by tsl0922** [comment]
fixed on master.
