### ISSUE TITLE
Provide arm Docker Container (arm64/v8)

### ISSUE THREAD

**Issue by dtcooper** [tsl0922/ttyd#577]
**Is your feature request related to a problem? Please describe.**

Hi there, now that Docker is available for Apple's M1 chipset, a native container that runs on `linux/arm64/v8` would be fantastic! Thanks for considering it.

**Describe the solution you'd like**
Provide above container @ https://hub.docker.com/r/tsl0922/ttyd

**Describe alternatives you've considered**
* Using non-native amd64
* Building it from the provided Dockerfile

**Comment by tsl0922** [comment]
PRs are welcomed, If it can be built on CI or using docker automated build.

**Comment by dtcooper** [comment]
I'll give it a stab. I was hoping it was easy because I don't know how to do it! :tongue

**Comment by odidev** [comment]
@tsl0922,
I have built the docker image of ttyd for arm64 platform by implementing these [changes ](https://github.com/odidev/ttyd/commit/2badbdcda3a4da46b13f94cc11d5ad0fde12968c)in the code.

I have done below updates to Dockerfile and scripts/cross-build.sh files for the development of arm64 compatible docker images:

- **Dockerfile** : Updated the tini image as well as the BUILD_TARGET value for adding the arm64 support..
- **scripts/cross-build.sh**: Updated the musl binary download link and created the soft links for  ar and ranlib binary.

Can you please suggest which CI we can use for building, testing and pushing images? IMO, it's better to use travis-ci as it has the support for arm64 architecture.
Can you please check the [changes ](https://github.com/odidev/ttyd/commit/2badbdcda3a4da46b13f94cc11d5ad0fde12968c)and let me know your opinion on them?

If agreed, I will raise the PR after testing this package in CI.

**Comment by tsl0922** [comment]
@odidev Thanks for your work, tut I prefer to use actions to do it, with docker buildx.

https://github.com/docker/build-push-action#multi-platform-image

**Comment by odidev** [comment]
@tsl0922 Thanks for the suggestion, I had build the [docker image](https://hub.docker.com/repository/docker/odidev/ttyd/tags?page=1&ordering=last_updated) of ttyd for both (amd64 and arm64) architecture using the buildx method by implementing these changes in the [release.yml](https://github.com/odidev/ttyd/blob/arm_support/.github/workflows/release.yml#L10-#L37).

Can you please check the[ docker image](https://hub.docker.com/repository/docker/odidev/ttyd/tags?page=1&ordering=last_updated) and let me know your opinion on them?

If everything's seems fine, then I will raise the PR.

**Comment by tsl0922** [comment]
@odidev I've made it myself, please check this commit e5fb0598dbb059dd5e52775a2a74aa540d01eb19.  ttyd is still been built via the cross toolchain, because it's faster.

@dtcooper can you test if the arm64 image on docker hub works?

**Comment by dtcooper** [comment]
Yay! Thank you so much. Both the latest arm64 and amd64 (with qemu emulation) run great on my Apple M1 , albeit the latter is of course slower. I consider this closed. :)
