### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by SlaSerX** [tsl0922/ttyd#58]
Err http://ppa.launchpad.net jessie/main i386 Packages
  404  Not Found
Ign http://ppa.launchpad.net jessie/main Translation-en
Ign http://rpms.litespeedtech.com jessie/main Translation-en
Fetched 10.6 kB in 4s (2471 B/s)            
W: Failed to fetch http://ppa.launchpad.net/tsl0922/ttyd-dev/ubuntu/dists/jessie/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by tsl0922** [comment]
This ppa only works for ubuntu 16.04 and later. You need to compile it from source for debian, and the `libwebsockets-dev` package is too old on jessie, so it needs to be compiled from source too.

**Comment by SlaSerX** [comment]
Ok thx :)
