### ISSUE TITLE
[Feature] Static binary releases

### ISSUE THREAD

**Issue by frol** [tsl0922/ttyd#59]
I just want to propose to provide static binary releases. There are some use-cases when you only want to share a session once, and currently, I resort to gotty since go produces portable binaries by design. ttyd has better support for unicode from my experience and this is why I would love to use ttyd...

P.S. It might be worth to consider musl libc instead of glibc for static compilation.

**Comment by tsl0922** [comment]
I definitely want to do this, but didn't find a good way to support all the platforms.

**Comment by frol** [comment]
Have you bumped into any issues when you just specify `-static` flag to the linker?

**Comment by tsl0922** [comment]
Yes, tried it before. musl libc maybe a good idea, glibc is too big for static linking.

**Comment by tsl0922** [comment]
Just let you know that I've successfully built a static binary with musl libc, but the build process is very complicate.

Try it: [ttyd.zip](https://github.com/tsl0922/ttyd/files/1075306/ttyd.zip)

**Comment by frol** [comment]
@tsl0922 It works on my Arch Linux and Ubuntu 16.04 systems! Super!

**Comment by tsl0922** [comment]
Released [1.3.3](https://github.com/tsl0922/ttyd/releases/tag/1.3.3) with static binary.
