### ISSUE TITLE
Compile error on Ubuntu 14.04

### ISSUE THREAD

**Issue by hubugui** [tsl0922/ttyd#6]
>sudo apt-get install cmake g++ pkg-config git vim-common libwebsockets-dev libjson-c-dev libssl-dev
git clone https://github.com/tsl0922/ttyd.git
cd ttyd && mkdir build && cd build
cmake ..
make

execute above command and notify fatal error:

>In file included from ttyd/src/server.c:1:0:
ttyd/src/server.h:1:24: fatal error: lws_config.h: No such file or directory
 #include "lws_config.h"

I already downloaded libwebsockets source code and install to fix this compile error.

Please update README.md

**Comment by tsl0922** [comment]
Thanks for reporting, I'll add a check for this.

`lws_config.h` is generated by cmake, old versions of libwebsockets may not compiled with cmake.

**Comment by tsl0922** [comment]
Added version minimum check for libwebsockets with cmake, and note on the README.
