### ISSUE TITLE
Programmatically sending input from the client

### ISSUE THREAD

**Issue by dpage-edb** [tsl0922/ttyd#620]
Hi

How can I programmatically send input from the client? Doing something like:

term.writeln('ls -al');

will write the text to the terminal, but it doesn't send it to the server (even when hitting return afterwards).

Thanks!

**Comment by tsl0922** [comment]
You can access the javascript [Terminal](https://xtermjs.org/docs/api/terminal/classes/terminal/) object via `window.term`.

**Comment by dpage-edb** [comment]
Thanks for the quick reply. My issue is not how to access the Terminal object; that seems to work fine - the problem is that using term.write() displays the text on the terminal UI, but never sends it to the server.

For example, in the screenshot below, I first sent the "select version()" command using the Javascript console. That never gets sent to the server. If I then type the same command into the terminal window, it works fine and I get the version info I expect.

<img width="1035" alt="Screenshot 2021-03-03 at 12 22 46" src="https://user-images.githubusercontent.com/60707224/109805335-3a5bfb80-7c1b-11eb-89f0-67c89f22a6d5.png">

**Comment by tsl0922** [comment]
example code to send `ls` to the terminal:

```
var script = document.createElement('script');
script.src = 'https://unpkg.com/keysim@latest/dist/keysim.js';
script.onload = function() {
	var input = document.querySelector('textarea');
	var keyboard = Keysim.Keyboard.US_ENGLISH;
	keyboard.dispatchEventsForInput("ls", input);
	keyboard.dispatchEventsForAction("enter", input);
};
document.body.appendChild(script);
```

**Comment by dpage-edb** [comment]
Yes, that works. Thanks!
