### ISSUE TITLE
Option to reconnect without refreshing

### ISSUE THREAD

**Issue by dmartin** [tsl0922/ttyd#628]
**Is your feature request related to a problem? Please describe.**
If I use ttyd to run a process and it exits successfully, `Connection Closed` is displayed and the window must be refreshed to run it again.

**Describe the solution you'd like**
The ability to reconnect on-demand after the connection has been closed, via pressing Enter (preferably) or clicking a link, possibly as a client option so that it's opt-in.

**Describe alternatives you've considered**
I can force ttyd to reconnect by exiting the underlying process with a non-zero exit code, but then ttyd has to maintain that new connection when the user may not have actually been interested in reconnecting.

**Additional context**
For example, a similar feature in `wetty.js`:

https://user-images.githubusercontent.com/1657652/110994084-1a1ff100-832d-11eb-9407-768b6231fb7f.mp4

**Comment by tsl0922** [comment]
press enter to reconnect is supported on master now, if you start ttyd with `-t disableReconnect=true`.
