### ISSUE TITLE
SSL_ERROR_RX_CERTIFICATE_REQUIRED_ALERT

### ISSUE THREAD

**Issue by doverride** [tsl0922/ttyd#632]
When i connect to a ttyd instance:
```
root@OpenWrt:~# cat /proc/6141/cmdline
/usr/bin/ttyd-ipppoe-wan-m3-6-S-C/etc/acme/openwrt.defensec.test/fullchain.cer-K/etc/acme/openwrt.defensec.test/openwrt.defensec.test.keyruncon-tsandbox.subj--tmux-2-S/tmp/tmux-sandboxattach-c/tmp/tmp-tsandbox
```
Using Firefox  i get a blank page.

firefox debugger say's SSL_ERROR_RX_CERTIFICATE_REQUIRED_ALERT but as you can see I have not specified a 'cert-ca' so why would firefox think it needs to provide a client cerificate?

**To Reproduce**
Try to use ttyd in openwrt with ssl and letsencrypt

**Expected behavior**
I expect working ssl

**Environment:**
 - OpenWrt master
 - Firefox 86

**Comment by doverride** [comment]
is this related?

https://github.com/tsl0922/ttyd/commit/0b146b750c5c1e88a1bf52fe9e61e1256017c82e

**Comment by tsl0922** [comment]
Maybe, try a tagged [release](https://github.com/tsl0922/ttyd/releases/latest) ?

**Comment by doverride** [comment]
well, yes 1.6.3 is in openwrt master and that is what i am using  but https://github.com/tsl0922/ttyd/commit/0b146b750c5c1e88a1bf52fe9e61e1256017c82e is from 7 day's ago

**Comment by doverride** [comment]
So yes .... i tried https://github.com/tsl0922/ttyd/commit/0b146b750c5c1e88a1bf52fe9e61e1256017c82e and that "fixes" it. Pretty important fix i would argue. can tag 1.6.4?

**Comment by doverride** [comment]
So just to be clear here. This functionality has never worked until 7 day's ago.

I have to clue why the wiki suggests something that has never worked, and why it was put there in the first place without confirming that it even works

**Comment by doverride** [comment]
Anyway closing, and it is fixed

**Comment by tsl0922** [comment]
I will tag a new release within this month, a lot of changes was made on master, still need some time to test.
