### ISSUE TITLE
linking

### ISSUE THREAD

**Issue by fpalfpal** [tsl0922/ttyd#634]
**Describe the bug**
linking on centos  fails, requires -lwebsockets option

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - CentOS Linux release 7.3.1611 (Core) 

**Additional context**

**Comment by tsl0922** [comment]
It compiles on [fedora](https://src.fedoraproject.org/rpms/ttyd/raw/f32/f/ttyd.spec).

This should not happen, please provide the full compile log.

**Comment by fpalfpal** [comment]
# cmake ..
-- The C compiler identification is GNU 4.8.5
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Found Git: /bin/git (found version "1.8.3.1")
-- Found LIBUV: /usr/lib64/libuv.so 
-- Found JSON-C: /usr/include/json-c 
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- Found Libwebsockets: /usr/lib64/libwebsockets.so 
-- Looking for LWS_OPENSSL_SUPPORT
-- Looking for LWS_OPENSSL_SUPPORT - found
-- Looking for LWS_WITH_MBEDTLS
-- Looking for LWS_WITH_MBEDTLS - not found
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2k")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fpal/ttyd/build
# make
Scanning dependencies of target ttyd
Building C object CMakeFiles/ttyd.dir/src/utils.c.o
Building C object CMakeFiles/ttyd.dir/src/pty.c.o
Building C object CMakeFiles/ttyd.dir/src/protocol.c.o
Building C object CMakeFiles/ttyd.dir/src/http.c.o
Building C object CMakeFiles/ttyd.dir/src/server.c.o
Linking C executable ttyd
CMakeFiles/ttyd.dir/src/protocol.c.o: In function `send_initial_message':
protocol.c:(.text+0xdb): undefined reference to `lws_write'
CMakeFiles/ttyd.dir/src/protocol.c.o: In function `check_host_origin':
protocol.c:(.text+0x1dc): undefined reference to `lws_hdr_copy'
protocol.c:(.text+0x21d): undefined reference to `lws_parse_uri'
protocol.c:(.text+0x2bd): undefined reference to `lws_hdr_copy'
CMakeFiles/ttyd.dir/src/protocol.c.o: In function `process_read_cb':
protocol.c:(.text+0x37d): undefined reference to `lws_callback_on_writable'
CMakeFiles/ttyd.dir/src/protocol.c.o: In function `process_exit_cb':
protocol.c:(.text+0x3d7): undefined reference to `_lws_log'
protocol.c:(.text+0x3fe): undefined reference to `_lws_log'
protocol.c:(.text+0x432): undefined reference to `lws_callback_on_writable'
CMakeFiles/ttyd.dir/src/protocol.c.o: In function `spawn_process':
protocol.c:(.text+0x5d8): undefined reference to `_lws_log'
protocol.c:(.text+0x607): undefined reference to `_lws_log'
protocol.c:(.text+0x629): undefined reference to `lws_callback_on_writable'
CMakeFiles/ttyd.dir/src/protocol.c.o: In function `wsi_output':
protocol.c:(.text+0x6c7): undefined reference to `lws_write'
protocol.c:(.text+0x6e3): undefined reference to `_lws_log'
CMakeFiles/ttyd.dir/src/protocol.c.o: In function `callback_tty':
protocol.c:(.text+0x77f): undefined reference to `_lws_log'
protocol.c:(.text+0x7c2): undefined reference to `_lws_log'
protocol.c:(.text+0x7ed): undefined reference to `lws_hdr_copy'
protocol.c:(.text+0x834): undefined reference to `_lws_log'
protocol.c:(.text+0x877): undefined reference to `_lws_log'
protocol.c:(.text+0x9a3): undefined reference to `lws_hdr_copy_fragment'
protocol.c:(.text+0x9d0): undefined reference to `lws_get_network_wsi'
protocol.c:(.text+0x9e0): undefined reference to `lws_get_peer_simple'
protocol.c:(.text+0xa16): undefined reference to `_lws_log'
protocol.c:(.text+0xa91): undefined reference to `_lws_log'
protocol.c:(.text+0xaaf): undefined reference to `lws_close_reason'
protocol.c:(.text+0xad9): undefined reference to `lws_callback_on_writable'
protocol.c:(.text+0xb11): undefined reference to `lws_close_reason'
protocol.c:(.text+0xcbf): undefined reference to `_lws_log'
protocol.c:(.text+0xcd8): undefined reference to `lws_remaining_packet_payload'
protocol.c:(.text+0xcec): undefined reference to `lws_is_final_fragment'
protocol.c:(.text+0xdc6): undefined reference to `_lws_log'
protocol.c:(.text+0xf58): undefined reference to `_lws_log'
protocol.c:(.text+0xf91): undefined reference to `lws_close_reason'
protocol.c:(.text+0xff6): undefined reference to `_lws_log'
protocol.c:(.text+0x107d): undefined reference to `_lws_log'
protocol.c:(.text+0x112c): undefined reference to `_lws_log'
protocol.c:(.text+0x117b): undefined reference to `_lws_log'
protocol.c:(.text+0x1191): undefined reference to `lws_cancel_service'
CMakeFiles/ttyd.dir/src/http.c.o: In function `check_auth':
http.c:(.text+0x4f): undefined reference to `lws_hdr_copy'
http.c:(.text+0x14e): undefined reference to `lws_add_http_header_status'
http.c:(.text+0x185): undefined reference to `lws_add_http_header_by_token'
http.c:(.text+0x1ab): undefined reference to `lws_add_http_header_content_length'
http.c:(.text+0x1cc): undefined reference to `lws_finalize_http_header'
http.c:(.text+0x20d): undefined reference to `lws_write'
http.c:(.text+0x267): undefined reference to `lws_callback_on_writable'
CMakeFiles/ttyd.dir/src/http.c.o: In function `accept_gzip':
http.c:(.text+0x2a0): undefined reference to `lws_hdr_copy'
CMakeFiles/ttyd.dir/src/http.c.o: In function `access_log':
http.c:(.text+0x474): undefined reference to `lws_get_network_wsi'
http.c:(.text+0x488): undefined reference to `lws_get_peer_simple'
http.c:(.text+0x4aa): undefined reference to `_lws_log'
CMakeFiles/ttyd.dir/src/http.c.o: In function `callback_http':
http.c:(.text+0x638): undefined reference to `lws_add_http_header_status'
http.c:(.text+0x66f): undefined reference to `lws_add_http_header_by_token'
http.c:(.text+0x695): undefined reference to `lws_add_http_header_content_length'
http.c:(.text+0x6b6): undefined reference to `lws_finalize_http_header'
http.c:(.text+0x6f7): undefined reference to `lws_write'
http.c:(.text+0x756): undefined reference to `lws_callback_on_writable'
http.c:(.text+0x798): undefined reference to `lws_add_http_header_status'
http.c:(.text+0x7dd): undefined reference to `lws_add_http_header_by_token'
http.c:(.text+0x804): undefined reference to `lws_add_http_header_content_length'
http.c:(.text+0x825): undefined reference to `lws_finalize_http_header'
http.c:(.text+0x866): undefined reference to `lws_write'
http.c:(.text+0x8ac): undefined reference to `lws_return_http_status'
http.c:(.text+0x8f2): undefined reference to `lws_serve_http_file'
http.c:(.text+0x910): undefined reference to `lws_http_transaction_completed'
http.c:(.text+0x95c): undefined reference to `lws_add_http_header_status'
http.c:(.text+0x98e): undefined reference to `lws_add_http_header_by_token'
http.c:(.text+0x9de): undefined reference to `lws_add_http_header_by_token'
http.c:(.text+0xa37): undefined reference to `lws_add_http_header_content_length'
http.c:(.text+0xa58): undefined reference to `lws_finalize_http_header'
http.c:(.text+0xa99): undefined reference to `lws_write'
http.c:(.text+0xaf0): undefined reference to `lws_callback_on_writable'
http.c:(.text+0xb33): undefined reference to `lws_get_peer_write_allowance'
http.c:(.text+0xb4b): undefined reference to `lws_callback_on_writable'
http.c:(.text+0xc3c): undefined reference to `lws_write'
http.c:(.text+0xc66): undefined reference to `lws_send_pipe_choked'
http.c:(.text+0xcbc): undefined reference to `lws_callback_on_writable'
http.c:(.text+0xd4b): undefined reference to `_lws_log'
http.c:(.text+0xd6a): undefined reference to `lws_http_transaction_completed'
CMakeFiles/ttyd.dir/src/server.c.o: In function `signal_cb':
server.c:(.text+0x472): undefined reference to `_lws_log'
server.c:(.text+0x4b4): undefined reference to `lws_cancel_service'
server.c:(.text+0x4de): undefined reference to `_lws_log'
CMakeFiles/ttyd.dir/src/server.c.o: In function `main':
server.c:(.text+0xfe2): undefined reference to `lws_set_log_level'
server.c:(.text+0x1131): undefined reference to `_lws_log'
server.c:(.text+0x1145): undefined reference to `_lws_log'
server.c:(.text+0x1177): undefined reference to `_lws_log'
server.c:(.text+0x1199): undefined reference to `_lws_log'
server.c:(.text+0x11c4): undefined reference to `_lws_log'
CMakeFiles/ttyd.dir/src/server.c.o:server.c:(.text+0x11e8): more undefined references to `_lws_log' follow
CMakeFiles/ttyd.dir/src/server.c.o: In function `main':
server.c:(.text+0x13b3): undefined reference to `lws_create_context'
server.c:(.text+0x13da): undefined reference to `_lws_log'
server.c:(.text+0x13fd): undefined reference to `lws_create_vhost'
server.c:(.text+0x141c): undefined reference to `_lws_log'
server.c:(.text+0x1432): undefined reference to `lws_get_vhost_listen_port'
server.c:(.text+0x144e): undefined reference to `_lws_log'
server.c:(.text+0x1552): undefined reference to `lws_service'
server.c:(.text+0x15a0): undefined reference to `lws_context_destroy'
collect2: error: ld returned 1 exit status
make[2]: *** [ttyd] Error 1
make[1]: *** [CMakeFiles/ttyd.dir/all] Error 2
make: *** [all] Error 2
# exit

**Comment by tsl0922** [comment]
check if `libwebsockets-devel` is installed on your system

**Comment by fpalfpal** [comment]
# rpm -qi libwebsockets-devel
Name        : libwebsockets-devel
Version     : 3.0.1
Release     : 2.el7
Architecture: x86_64
Install Date: 2021. márc. 24., szerda, 15.34.04 CET
Group       : Unspecified
Size        : 553085
License     : LGPLv2 and Public Domain and BSD and MIT and zlib
Signature   : RSA/SHA256, 2019. jan.  7., hétfő, 16.37.16 CET, Key ID 6a2faea2352c64e5
Source RPM  : libwebsockets-3.0.1-2.el7.src.rpm
Build Date  : 2019. jan.  7., hétfő, 16.00.57 CET
Build Host  : buildhw-08.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://libwebsockets.org
Bug URL     : https://bugz.fedoraproject.org/libwebsockets
Summary     : Headers for developing programs that will use libwebsockets
Description :
This package contains the header files needed for developing
libwebsockets applications.

**Comment by fpalfpal** [comment]
/bin/gcc -D_GNU_SOURCE -Wvla -std=gnu99    CMakeFiles/ttyd.dir/src/utils.c.o CMakeFiles/ttyd.dir/src/pty.c.o CMakeFiles/ttyd.dir/src/protocol.c.o CMakeFiles/ttyd.dir/src/http.c.o CMakeFiles/ttyd.dir/src/server.c.o  -o ttyd -rdynamic -lz -ljson-c -luv -lssl -lcrypto -lutil

CMakeFiles/ttyd.dir/src/protocol.c.o: In function `send_initial_message':
protocol.c:(.text+0xdb): undefined reference to `lws_write'
CMakeFiles/ttyd.dir/src/protocol.c.o: In function `check_host_origin':
protocol.c:(.text+0x1dc): undefined reference to `lws_hdr_copy'
protocol.c:(.text+0x21d): undefined reference to `lws_parse_uri'
protocol.c:(.text+0x2bd): undefined reference to `lws_hdr_copy'
CMakeFiles/ttyd.dir/src/protocol.c.o: In function `process_read_cb':
protocol.c:(.text+0x37d): undefined reference to `lws_callback_on_writable'
CMakeFiles/ttyd.dir/src/protocol.c.o: In function `process_exit_cb':
protocol.c:(.text+0x3d7): undefined reference to `_lws_log'
protocol.c:(.text+0x3fe): undefined reference to `_lws_log'
protocol.c:(.text+0x432): undefined reference to `lws_callback_on_writable'
CMakeFiles/ttyd.dir/src/protocol.c.o: In function `spawn_process':
protocol.c:(.text+0x5d8): undefined reference to `_lws_log'
protocol.c:(.text+0x607): undefined reference to `_lws_log'
...

**But this works:**
/bin/gcc -D_GNU_SOURCE -Wvla -std=gnu99    CMakeFiles/ttyd.dir/src/utils.c.o CMakeFiles/ttyd.dir/src/pty.c.o CMakeFiles/ttyd.dir/src/protocol.c.o CMakeFiles/ttyd.dir/src/http.c.o CMakeFiles/ttyd.dir/src/server.c.o  -o ttyd -rdynamic -lz -ljson-c -luv -lssl -lcrypto -lutil **-lwebsockets**

**Comment by tsl0922** [comment]
Reproduced it on `centos:7` docker image, try the patch below:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ae5915e..b48d4d1 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -58,10 +58,8 @@ if(NOT Libwebsockets_FOUND) # for libwebsockets-dev on ubuntu 16.04
     find_library(LIBWEBSOCKETS_LIBRARY NAMES websockets)
     find_package_handle_standard_args(Libwebsockets REQUIRED_VARS LIBWEBSOCKETS_LIBRARY LIBWEBSOCKETS_INCLUDE_DIR)
     mark_as_advanced(LIBWEBSOCKETS_INCLUDE_DIR LIBWEBSOCKETS_LIBRARY)
-    if(Libwebsockets_FOUND)
-        SET(LIBWEBSOCKETS_INCLUDE_DIRS "${LIBWEBSOCKETS_INCLUDE_DIR}")
-        SET(LIBWEBSOCKETS_LIBRARIES "${LIBWEBSOCKETS_LIBRARY}")
-    endif()
+    SET(LIBWEBSOCKETS_INCLUDE_DIRS "${LIBWEBSOCKETS_INCLUDE_DIR}")
+    SET(LIBWEBSOCKETS_LIBRARIES "${LIBWEBSOCKETS_LIBRARY}")
 endif()

 set(INCLUDE_DIRS ${ZLIB_INCLUDE_DIR} ${LIBWEBSOCKETS_INCLUDE_DIRS} ${JSON-C_INCLUDE_DIRS} ${LIBUV_INCLUDE_DIRS})
```

don't know why the `Libwebsockets_FOUND` variable is not updated, remove the `if` block should be ok.

**Comment by tsl0922** [comment]
should be fixed on master now

**Comment by fpalfpal** [comment]
It's OK with this correction.
Thanks!

**Comment by peterwillcn** [comment]
Ubuntu 20.04 
apt install libwebsockets-dev
```
protocol.c:(.text+0xe2): undefined reference to `_lws_log'
/home/openwrt/master/openwrt/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/11.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: protocol.c:(.text+0xfe): undefined reference to `lws_callback_on_writable'
/home/openwrt/master/openwrt/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/11.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: CMakeFiles/ttyd.dir/src/protocol.c.o: in function `send_initial_message':
protocol.c:(.text+0x1b4): undefined reference to `lws_write'
/home/openwrt/master/openwrt/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/11.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: CMakeFiles/ttyd.dir/src/protocol.c.o: in function `child_cb':
protocol.c:(.text+0x2ae): undefined reference to `_lws_log'
/home/openwrt/master/openwrt/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/11.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: protocol.c:(.text+0x2f9): undefined reference to `_lws_log'
/home/openwrt/master/openwrt/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/11.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: CMakeFiles/ttyd.dir/src/protocol.c.o: in function `callback_tty':
protocol.c:(.text+0x3f3): undefined reference to `_lws_log'
/home/openwrt/master/openwrt/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/11.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: protocol.c:(.text+0xea3): undefined reference to `lws_cancel_service'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:54: /home/openwrt/master/openwrt/build_dir/target-x86_64_musl/ttyd-1.6.3/.built] Error 1
make[3]: Leaving directory '/home/openwrt/master/openwrt/package/feeds/utils/ttyd'
time: package/feeds/utils/ttyd/compile#0.10#0.03#0.12
    ERROR: package/feeds/utils/ttyd failed to build.
make[2]: *** [package/Makefile:116: package/feeds/utils/ttyd/compile] Error 1
make[2]: Leaving directory '/home/openwrt/master/openwrt'
make[1]: *** [package/Makefile:110: /home/openwrt/master/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/openwrt/master/openwrt'
make: *** [/home/openwrt/master/openwrt/include/toplevel.mk:230: world] Error 2
```
