### ISSUE TITLE
Not setting overflow-y: scroll on div.xterm-viewport for use with tmux

### ISSUE THREAD

**Issue by eMPee584** [tsl0922/ttyd#636]
There's a scrollbar shown on the right side by default. Using tmux makes that obsolete.. any sensible way to suppress it? Sorry for cutting my research short, maybe others would also like to have a config option for this..

**Comment by tsl0922** [comment]
The `overflow-y: scroll` comes from [xterm.js](https://github.com/xtermjs/xterm.js). 

It's not a blocking issue for user, so I won't make the change in ttyd. You can change it yourself and rebuild ttyd, or use browser extensions to inject css to webpage.

**Comment by eMPee584** [comment]
Mh ok.. but where is the source that gets compiled in 🤔

**Comment by nlvw** [comment]
@eMPee584 if you enable mouse mode in tmux it will prevent the scroll back in xterm.js and only use the tmux built in scroll back.  The only downside to this is the selection copy to clipboard doesn't seem to be working in xterm.js when using tmux mouse mode.  You can work around this by using the 'shift' override when selecting text.

**Comment by tsl0922** [comment]
> Mh ok.. but where is the source that gets compiled in 🤔

https://github.com/tsl0922/ttyd/tree/main/html
