### ISSUE TITLE
Low privileged initial user access via ttyd (Windows)

### ISSUE THREAD

**Issue by stonjik** [tsl0922/ttyd#644]
Describe your problem or question here.
Hey, is there any way that i can connect to a Windows-based machine with a low privileged user(not an admin) via ttyd? In Linux i can specify sid and gid but i could not find the relative feature for windows, is it even possible?

**Comment by tsl0922** [comment]
It's not supported by libwebsockets.

https://github.com/warmcat/libwebsockets/blob/52733e481ad42599553e3a0e6877c9aadf1eb8ca/lib/plat/windows/windows-init.c#L33
