### ISSUE TITLE
Scroll size

### ISSUE THREAD

**Issue by snez** [tsl0922/ttyd#646]
**Is your feature request related to a problem? Please describe.**
We use ttyd to start and monitor test suites on a remote C.I. server. It would be very useful if we could increase the default scroll size. xterm seems to support this by setting the scrollback parameter.

**Describe the solution you'd like**
ttyd --scroll 10000 would work

**Describe alternatives you've considered**
No alternatives are available

**Additional context**
None

**Comment by tsl0922** [comment]
try `ttyd -t scrollback=10000`, take a look at [Client Options](https://github.com/tsl0922/ttyd/wiki/Client-Options)

**Comment by snez** [comment]
@tsl0922 thanks for the pointer, this capability doesn't seem to be very clear in the docs
