### ISSUE TITLE
macport 2.6.4 cannot install ttyd

### ISSUE THREAD

**Issue by prasantjalan** [tsl0922/ttyd#651]
**Describe the bug**
Unable to install ttyd with macport 2.6.4.
ttyd 1.4.2 fails to 

**To Reproduce**
1. update macports to 2.6.4
2. sudo port install ttyd

**Expected behavior**
ttyd should successfully install

**Environment:**
 - OS: [e.g. macOS 10.15.5 Catalina]
 - MacBook Pro (Retina, 15-inch, Mid 2015)
 - Xcode 12.4

**Additional context**
- While building (before installing) it gives the error
: :info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_net_ttyd/ttyd/work/ttyd-1.4.2/src/server.c:399:10: error: no member named 'ws_ping_pong_interval' in 'struct lws_context_creation_info'
- log file attached here
[main.log](https://github.com/tsl0922/ttyd/files/6362321/main.log)

**Comment by tsl0922** [comment]
You may use a newer libwebsockes with old version of ttyd. 

It should be fixed on 1.6.2 or later (#475),  report it to macport's maintainers to update the portfile.

**Comment by prasantjalan** [comment]
Thanks. I had filed a bug there as well. [macport-62734](https://trac.macports.org/ticket/62734).
