### ISSUE TITLE
Problems with disconnects

### ISSUE THREAD

**Issue by DanKGooGLy** [tsl0922/ttyd#664]
**Describe the bug**
I know that #663 was already brought up, but ttyd seems to disconnect frequently if I leave it alone for 20 seconds or more, and sometimes even when I'm actively using it. It also used to automatically reload the page whenever I'd log out of my shell, but now it just freezes at "Connection Lost".

**To Reproduce**
1. Leave shell for about 15-30 seconds or run `exit` or `logout`
2. Disconnects

**Expected behavior**
1. Shell should remain connected for a while after I leave it on

1. Run `exit` or `logout`
2. Brings you back to to login page

**Screenshots**

**Environment:**
 - OS: ChromeOS  90.0.4430.100 (64-bit), Void Linux, Arch Linux
 - Browser: Chrome 90.0.4430.100, Firefox 84

![image](https://user-images.githubusercontent.com/34890978/117066235-7c2a2080-acf6-11eb-967e-222cd6716461.png)
https://user-images.githubusercontent.com/34890978/117066844-42a5e500-acf7-11eb-9313-4d2a0cbf4eef.mp4

**Additional context**
Add any other context about the problem here

**Comment by tsl0922** [comment]
If you disabled reconnect, It will freeze at "Connection Closed" until you refresh the page, it was by design. I've added a `press enter to reconnect` on master (#628), you may want to try it.

> disconnect frequently if I leave it alone for 20 seconds or more

Is ttyd behind a proxy? check if #519 works for you (specify an interval <20).

**Comment by DanKGooGLy** [comment]
I forgot to mention this, but I can't get on the master branch because debian's libwebsockets is very outdated and other methods of getting it don't work.

**Comment by DanKGooGLy** [comment]
Could you by chance build a new release based on master within your free time? Or are releases only every major update?

**Comment by DanKGooGLy** [comment]
Actually, the websocket ping interval seems to have fixed everything except for the reload. Thanks!
