### ISSUE TITLE
Automate user login

### ISSUE THREAD

**Issue by dasb44** [tsl0922/ttyd#68]
你好作者，我想问一下用sudo ./ttyd login 怎么实现automatic user login，我想要用javascript自动填login and password for different user，然后login to the terminal.

**Comment by tsl0922** [comment]
你可使用 `--credential` 开启 HTTP Basic Auth，再用 js 通过它验证用户名密码。`login` 命令不太适合自动化登陆，因为它有交互。

**Comment by dasb44** [comment]
我希望不同的用户用不同的用户名和密码来login, --credential只能设置一个用户名和密码，所以我想用 system accounts 来login

**Comment by tsl0922** [comment]
不支持。

ttyd 的定位就是个简单的小工具，如果无法满足你的要求，你可以自己 fork 项目改代码。

dasb44 <notifications@github.com>于2017年8月13日 周日01:46写道：
