### ISSUE TITLE
Poor font rendering on Firefox

### ISSUE THREAD

**Issue by fpom** [tsl0922/ttyd#685]
I'm using ttyd in a project for my students (FYI see https://github.com/fpom/cow) and it's default font renders very poorly on Firefox while it is perfectly readable under Chrome. See the two screenshots below.

Firefox:
![Screenshot from 2021-05-25 12-09-43](https://user-images.githubusercontent.com/4525552/119481086-9d5cba80-bd52-11eb-84e4-668643816e0f.png)

Chrome:
![Screenshot from 2021-05-25 12-11-01](https://user-images.githubusercontent.com/4525552/119481090-9df55100-bd52-11eb-9fa0-589652596a4f.png)

My current workaround is to increase font size so the problem is less disturbing but it's still there.
I'm running Linux with Firefox 88.0.1 and Chrome 86.0.4240.183.
I've tried to change Firefox font setting but it did not help.

Thanks in advance for any help!

**Comment by r-schmidt** [comment]
Could it be that you have some add-on installed in Firefox that you don't have in Chrome?
It looks pretty much like what a colleague of mine experienced recently. Some add-on (privacy badger or something like it) was causing it. Either after an update of the add-on or Firefox itself. He didn't have that issue until a few weeks ago. And there was no change in ttyd on the server he was accessing.

So try disabling add-ons until you find the culprit.

**Comment by fpom** [comment]
Indeed, I've disabled add-blockers and it works fine now!
Thanks a lot!
