### ISSUE TITLE
Termux ttyd not display any char

### ISSUE THREAD

**Issue by QGB** [tsl0922/ttyd#687]
![image](https://user-images.githubusercontent.com/8005654/119925314-caee7180-bfa7-11eb-9fdb-ea6e8e568ccf.png)

`> ttyd tmux at`
keyboard input in `http://192.168.43.34:7681` is ok . but not display

**Comment by QGB** [comment]
ttyd version & server info
![image](https://user-images.githubusercontent.com/8005654/120049345-3e49bf00-c04c-11eb-9498-a892ef92f0b4.png)

**Comment by QGB** [comment]
ttyd server log:
![image](https://user-images.githubusercontent.com/8005654/120065025-d9b94f00-c0a1-11eb-9c8b-f4b9245bfc7f.png)

**Comment by hedifezai** [comment]
Same thing here :'(

**Comment by DavidPu** [comment]
I worked around this issue by switching back to old ttyd and libwebsocket.so:
$ ./ttyd --version
ttyd version 1.6.0
$ md5sum  /data/data/com.termux/files/usr/lib/libwebsockets*
cf22181147d2a5c4154592e534668b52  /data/data/com.termux/files/usr/lib/libwebsockets-evlib_uv.so
3a61666d3c7313a49876d1dc57c33caa  /data/data/com.termux/files/usr/lib/libwebsockets.so

**Comment by tsl0922** [comment]
It does not seems to be ttyd's issue.

I don't have a android phone to test it, so you may wan't to open the issue on termux repo.
