### ISSUE TITLE
How to create/put the window into an iframe

### ISSUE THREAD

**Issue by prayritkhanna** [tsl0922/ttyd#691]
Hello, 

I am trying to make the canvas into an iframe in the window to host multiple connections on one page that can be viewed at once. I'm wondering how to make ttyd into an iframe versus a canvas on the browser. 

Hope to hear from you soon. 

Thank you,
P.

**Comment by tsl0922** [comment]
Just do it, I don't think there're something will prevent putting ttyd window into an iframe.
