### ISSUE TITLE
homebrew update before installing

### ISSUE THREAD

**Issue by fangxian** [tsl0922/ttyd#7]
We would better to update homebrew before we install ttyd, otherwise we might fail in installing libwebsockets.
This is the error message:
Last 15 lines from /Users/yufangxian/Library/Logs/Homebrew/ttyd/01.cmake:

CMake Error at /usr/local/lib/cmake/libwebsockets/LibwebsocketsConfig.cmake:13 (include):
  include could not find load file:

/usr/local/lib/cmake/libwebsockets/LibwebsocketsTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:9 (find_package)

-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'json-c'
--   Found json-c, version 0.12
-- Found JSON-C: /usr/local/lib/libjson-c.dylib  
-- Configuring incomplete, errors occurred!
See also "/tmp/ttyd20160927-84356-bgeecl/ttyd-1.0.0/CMakeFiles/CMakeOutput.log".

After I update homebrew, ttyd can be installed successfully.

**Comment by tsl0922** [comment]
I'm submitting ttyd to the official homebrew repo (https://github.com/Homebrew/homebrew-core/pull/5310), after homebrew bottles for ttyd is created, you may not need to compile it locally.

**Comment by tsl0922** [comment]
Close as ttyd has been added to the official homebrew repo.
