### ISSUE TITLE
Send a message to parent window

### ISSUE THREAD

**Issue by pawansingh00** [tsl0922/ttyd#724]
Hi,

I am rendering **ttyd** terminal inside an **iframe**.
Once the terminal is loaded, I want to send a **postMessage** to the parent window.

I tried adding this in **template.html** -- 

```
<script type="text/javascript">
    window.parent && window.parent.postMessage({type : 'ttyd', action: 'ttydLoaded'},'*');
    console.log("Initialized terminal.");
</script>

```
but after building this code is getting removed and its not working.

If there is any way of injecting such code without modifying, it will be much appreciated.

Any help is much appreciated.

**Comment by tsl0922** [comment]
you need to edit the html [source](https://github.com/tsl0922/ttyd/tree/main/html) yourself and rebuild it, then recompile ttyd. or if you don't want to recompile ttyd, start ttyd with `--index` to the location of recompiled html.

**Comment by pawansingh00** [comment]
Thanks @tsl0922, had figured it out, missed on closing the issue.
Thanks again.

**Comment by zjy365** [comment]
@pawansingh00  hello, I would like to know how you solved this problem
