### ISSUE TITLE
Unsafe handling of forkpty() failure in pty_spawn()

### ISSUE THREAD

**Issue by patrakov** [tsl0922/ttyd#737]
Please look into the pty_spawn() function in src/pty.c.

```
int pty_spawn(pty_process *process, pty_read_cb read_cb, pty_exit_cb exit_cb) {
  /* ... */
  pid = forkpty(&master, NULL, NULL, &size);
  if (pid < 0) {
    status = -errno;
    goto error;
  } else if (pid == 0) {
    setsid();
    int ret = execvp(process->argv[0], process->argv);
    if (ret < 0) {
      perror("execvp failed\n");
      _exit(-errno);
    }
  }
  /* ... */
error:
  close(master);
  uv_kill(pid, SIGKILL);
  waitpid(pid, NULL, 0);
  return status;
}
```

If forkpty() fails, then it returns pid < 0 (actually, according to "man 2 fork", it is -1), and the error handling code does a "goto error". After the "error:" label, pid is still negative, and this negative argument (-1) is propagated to uv_kill(), which is a thin wrapper around kill() on Linux. Which means that kill() is eventually called with the first argument set to -1, and all processes except init are killed. So I'd suggest protecting uv_kill() and waitpid() with a check that pid is positive.

**Comment by patrakov** [comment]
Also, if forkpty() fails, an attempt to close(master) would mean closing some random fd with the number coming from uninitialized memory. So, just a "return status" would likely be a proper way to handle this error.

**Comment by tsl0922** [comment]
Fixed on master, Thanks 👍
