### ISSUE TITLE
changing theme colors or settings overwrites them all.

### ISSUE THREAD

**Issue by Zibri** [tsl0922/ttyd#743]
if I just want to change one setting in the current theme, ttyd overwrites the whole theme object.
while it should ADD/change the selected parameter.

there should be an option to change just one parameter withour having to set them all.
if you do: ttyd -t 'theme={"background": "green"}' bash
and then you inquire the theme variable just contains the background, losing all other settings.

**Comment by tsl0922** [comment]
Fixed on main (723ae966939527e8db35f27fb69bac0e02860099).
