### ISSUE TITLE
CLI input logging for ttyd

### ISSUE THREAD

**Issue by amsnek** [tsl0922/ttyd#744]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
logging of all CLI commands that are entered via ttyd (maybe already possible with some socat magic?)
(optional) all input/output

**Describe alternatives you've considered**
none yet

**Comment by tsl0922** [comment]
It's possible, but I would recommend using tools like [ttyrec](https://github.com/mjording/ttyrec).

**Comment by amsnek** [comment]
hmm ttyrec i didnt know. I am currently tricksing around with logger/bashrc and looking into tmux (which i will need anyways to multiplex so that multiple users can see the same input/output)
-> will look into ttyrec as well, thanks!

will close the request, if native logging ever should come, that would be neat too but i understand if other tools would be considered more suitable for that
