### ISSUE TITLE
rendererType argument ignored

### ISSUE THREAD

**Issue by only-cliches** [tsl0922/ttyd#777]
**Describe the bug**
Regardless of what you pass into the `rendererType` client argument, the WebGL renderer is used.

**To Reproduce**
1. I run this command to start ttyd: `ttyd -t rendererType=dom zsh`. (this should disable webGL rendering)
2. I visit `http://localhost:7681/`
3. The console prints `[ttyd] WebGL renderer enabled` which only happens when the WebGL rendering path is used: https://github.com/tsl0922/ttyd/blob/d7440fbaf8fafc0cfcf17581dc4f21ee684a88eb/html/src/components/terminal/index.tsx#L226

<img width="501" alt="Screen Shot 2021-09-22 at 5 30 13 PM" src="https://user-images.githubusercontent.com/14365337/134439247-cb46548d-cc0b-4c54-8af8-39f330b21b59.png">

**Expected behavior**
ttyd should not load the WebGL path when the `dom` value is used for the `rendererType` property.

**Environment:**
 - OS: macOS 11.6
 - Browser: Behavior happens in Firefox, Chrome and Safari.

**Additional context**
This is especially problematic because the new version of Safari (released yesterday) doesn't render xtermjs correctly when using WebGL.  https://github.com/xtermjs/xterm.js/issues/3357

The best interim solution would be to disable the WebGL renderer entirely, but that's not possible with this bug in place.

**Comment by only-cliches** [comment]
PR has been submitted to resolve the issue: https://github.com/tsl0922/ttyd/pull/778

**Comment by tsl0922** [comment]
Thanks, fixed on main
