### ISSUE TITLE
TTYD crashes, ERR: send PONG

### ISSUE THREAD

**Issue by snkasi** [tsl0922/ttyd#78]
![1](https://user-images.githubusercontent.com/17872382/33108811-19ec0efa-cf79-11e7-9113-27de32cfafc2.jpg)
![screen](https://user-images.githubusercontent.com/17872382/33108812-1a36b6da-cf79-11e7-9861-afb0dc9f3e17.jpg)

hi
I used ttyd to run a python script, but it crashed randomly
plz help me to solve this problem
tks :)

**Comment by snkasi** [comment]
Ubuntu 14.04.5 & Python 2.7.6 & ttyd 1.3.3

**Comment by alex-chan** [comment]
I have similar problem
shell:
```
process exited with code 256
```

web:
```
WConnection Closed
execvp: No such file or directory
```

**Comment by alex-chan** [comment]
But I type `ttyd login` , it's OK

**Comment by tsl0922** [comment]
#76 Contains changes which may solve this problem, I'll upgrade the ppa package with the latest version of libwebsockets instead of the very outdated one provided by ubuntu.

**Comment by snkasi** [comment]
it is OK now, 3Q
