### ISSUE TITLE
New release with header auth?

### ISSUE THREAD

**Issue by torjue** [tsl0922/ttyd#784]
I see there's been done a lot of good work on header authentication since the last release in January. Is it possible to push out a new release, as building from source isn't always ideal?

**Comment by torjue** [comment]
Any hope getting a new release? The iOS15 Webgl bug is also critical for many, I think. @tsl0922: Seems like you're the only one running the release actions. Any possibility hitting the button?

**Comment by tsl0922** [comment]
not now, there're still some known issues not resolved.

FYI: you can always download a latest binary from the actions build artifacts.

**Comment by ibz** [comment]
Was about to post the same. Thanks for the explanation. Looking forward though.

**Comment by AddisonG** [comment]
I'm so sad that the latest release is still on webpack 4.

I feel like I'm promoting terrible practices by pinning the version that we use to a hash, rather than to a version number, but it's the only choice at the moment.

Hoping that there's a release scheduled soon!

**Comment by tsl0922** [comment]
Released [1.7.0](https://github.com/tsl0922/ttyd/releases/tag/1.7.0)
