### ISSUE TITLE
Alt-. (yank-last-arg) should insert the previous command's last argument at the cursor

### ISSUE THREAD

**Issue by verhovsky** [tsl0922/ttyd#791]
**Describe the bug**
In bash, pressing alt+. (period) puts the previous command's last argument at your cursor. It ttyd it types a "»" symbol.

Maybe there are other [readline shortcuts](https://www.gnu.org/software/bash/manual/html_node/Bindable-Readline-Commands.html) not supported, but this is the one I use all the time and noticed.

**Expected behavior**
Alt-. should insert the previous command's last argument at the cursor position.

**Screenshots**

Bash:

<img width="381" alt="Screen Shot 2021-10-08 at 8 41 49 AM" src="https://user-images.githubusercontent.com/5687998/136576623-df918f6a-678c-4666-a301-580c6bb06faa.png">

ttyd:

<img width="232" alt="Screen Shot 2021-10-08 at 8 40 00 AM" src="https://user-images.githubusercontent.com/5687998/136576485-0945ba4e-6eff-455c-9547-fca02c58ba5b.png">

**Environment:**
 - OS: macOS 11.6
 - Browser: Chrome 94.0.4606.71

**Comment by tsl0922** [comment]
The `yank-last-arg` feature do not work on my mac with system terminal running bash.

then I tested it on a windows wsl2 terminal (linux) which supports `yank-last-arg`, ttyd started from this terminal works too.

**Comment by tsl0922** [comment]
> May be worth adding to the docs/wiki.

You may add it yourself, the wiki is publicly editable.
