### ISSUE TITLE
cursorStyle rendering issue

### ISSUE THREAD

**Issue by spurin** [tsl0922/ttyd#793]
Hi @tsl0922,

Currently in the process of upgrading the ttyd binaries that my project uses to address the Safari 15 renderType issue.  Am using ttyd as the static binaries take from https://github.com/tsl0922/ttyd/actions/runs/1270284445

When I connect, the cursorStyle looks like the following -

![image](https://user-images.githubusercontent.com/850464/136712942-0a1af3ba-7ead-4352-8cd9-0539570f7b7f.png)

The cursorStyle continues to look like this indefinitely.  If however, I click off the tab and click back, it changes to the block style that would be expected -

![image](https://user-images.githubusercontent.com/850464/136712985-f69207e8-8a68-47d4-a910-69d0b4053421.png)

Any ideas how this can be made consistent as per the second image?  I've tried ```-t cursorStyle block``` without success.

I notice the same behaviour in Chrome 94.0.4606.71 (Mac Mini M1) and Safari 15 (which works as expected now, albeit with this cursor issue).

Many thanks and as always, appreciate ttyd :-)

**Comment by spurin** [comment]
This issue is only seen with the rendertype of dom, if this is removed it functions as expected (albeit, Safari 15 is broken)

**Comment by tsl0922** [comment]
Should be upstream issue, please check if it is reproducible on [xterm.js](https://github.com/xtermjs/xterm.js) demo and report it to upstream.
