### ISSUE TITLE
Browser's Hot key Block

### ISSUE THREAD

**Issue by mission-young** [tsl0922/ttyd#82]
I use vim,but some hotkey meets problems,like ctrl ww.

**Comment by tsl0922** [comment]
Can not reproduce, which version are you use?

**Comment by tsl0922** [comment]
Close as not reproducible, key event handling should be related to [xterm.js](https://github.com/xtermjs/xterm.js).

**Comment by s7lx** [comment]
我这边1.2.1有这个问题，在用 vim 时候按esc 有时候是无效的。
safari 没发现，主要在 chrome 下遇到

**Comment by s7lx** [comment]
发现是和 chrome 下的插件 vimium 冲突了。禁用就没问题了。但 safari 下依然有概率只认回车

**Comment by shixiaobao17145** [comment]
> 我这边1.2.1有这个问题，在用 vim 时候按esc 有时候是无效的。
> safari 没发现，主要在 chrome 下遇到。但 safari 下有概率只认回车

你说的有概念只认回车是什么情况？因为我这边也有遇到类似的情况
