### ISSUE TITLE
Keep-alive not working without -P argument

### ISSUE THREAD

**Issue by cfraenkel** [tsl0922/ttyd#822]
It seems that the ping packets are not being sent unless I specify a value using -P (verified using zap proxy as chrome does not show ping frames).
I tested both with and without ` -P` and only saw the ping pong frames when I added e.g. `-P 20`

Could this be because `info.retry_and_idle_policy`  is only set if -P is specified?

https://github.com/tsl0922/ttyd/blob/bff3a617e6989a656626b71b8a1eff8c1718fb8a/src/server.c#L437-L448

**Comment by tsl0922** [comment]
Should be fixed on master now (b37ea9f27430ba38cd13182caedc1c812ae4ca16).
