### ISSUE TITLE
你好，screen -dmS ttyd ttyd -p 4200 bash -x 没有认证啊。

### ISSUE THREAD

**Issue by a1093773736** [tsl0922/ttyd#84]
screen -dmS ttyd ttyd -p 4200 bash -x 
使用命令后直接进入，无须登录很危险，看了说明，加了-c username:password不行啊。

**Comment by tsl0922** [comment]
Try: `ttyd login`.

**Comment by a1093773736** [comment]
谢谢，这问题解决，不过不能直接root啊。
