### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by znyrpavithra** [tsl0922/ttyd#841]
every time, ttyd backend connection cuts, this error occurs and crashes the whole site.
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typescript-tailwindcss-nextjs-starter@1.0.0 dev: `next dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the typescript-tailwindcss-nextjs-starter@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by tsl0922** [comment]
Please use the issue template.
