### ISSUE TITLE
title not updating

### ISSUE THREAD

**Issue by realies** [tsl0922/ttyd#85]
When running a command, bash changes the title of the terminal. This does not happen with `ttyd` although I can see client-side code that handles page title updates. Could this be due to misconfiguration?

**Comment by tsl0922** [comment]
This is not supported yet, the title is hardcoded with `hostname` currently.

**Comment by tsl0922** [comment]
Should be fixed by 2087fc6efe82c335ecf096321802f0237e9c8e98.
