### ISSUE TITLE
Unstable text area width

### ISSUE THREAD

**Issue by duck-rh** [tsl0922/ttyd#853]
**Describe the bug**
I made a demo for a little application called LDAPWalker and the title is displayed using `toilet` (figlet-like). On my widescreen I can see the whole title on one line normally but half the time the text area seems reduced in width and the title is wrapped.

**To Reproduce**
1. open https://ldapwalker-demo.duckcorp.org/

**Expected behavior**
The text should use the available width on my widescreen with my browser on fullscreen.

**Screenshots**
![20211223-005641_screenshot](https://user-images.githubusercontent.com/19259504/147121877-b3528c11-2597-47df-ab4f-c55ef3a14671.png)
![20211223-005711_screenshot](https://user-images.githubusercontent.com/19259504/147121883-f5bf875e-e2b4-46fa-a61b-a1ea50c94d61.png)

**Environment:**
 - OS: Debian unstable
 - Browser:Firefox 95.0.1-1
 - ttyd: 1.6.3-3~bpo11+1

**Additional context**
When opening the application the overlay size displays `322*64` in both cases. It looks like a race condition.

**Comment by tsl0922** [comment]
I've tested it on https://ldapwalker-demo.duckcorp.org/ , it works fine.

The terminal width is correct. If you echo a very long line, it can use the full browser width.

**Comment by duck-rh** [comment]
@tsl0922 I'm sorry but it still can be reproduced. Just reload the page et as I said sometimes it's working and sometimes not.

**Comment by duck-rh** [comment]
I made some screenshots to show you.

![20230619-203508_screenshot](https://github.com/tsl0922/ttyd/assets/19259504/b3c14ada-190e-4607-a0f1-abe6b249fe0f)
![20230619-203514_screenshot](https://github.com/tsl0922/ttyd/assets/19259504/e4ba0c57-8579-45bf-a9fd-51f70c8050af)

**Comment by tsl0922** [comment]
Did you try if the latest 1.7.3 version works? 1.6.3 version is know to have this issue (race condition).
