### ISSUE TITLE
Current stable?

### ISSUE THREAD

**Issue by ilovezfs** [tsl0922/ttyd#88]
https://github.com/tsl0922/ttyd/releases shows 1.3.3 and 1.4.0

https://github.com/tsl0922/ttyd/releases/latest points to 1.3.3

**Comment by tsl0922** [comment]
Yes it is, published now.

**Comment by ilovezfs** [comment]
Thanks @tsl0922! Voilà: https://github.com/Homebrew/homebrew-core/pull/22991
