### ISSUE TITLE
build for Android failed due to unable to find library -lutil

### ISSUE THREAD

**Issue by leleliu008** [tsl0922/ttyd#881]
There is no `libutil` in Android's libc.

relevant code: [CMakeLists.txt#L76](https://github.com/tsl0922/ttyd/blob/main/CMakeLists.txt#L76)

may be following code is better:

```cmake
find_library(LIBUTIL util)
if (LIBUTIL)                      
     list(APPEND LINK_LIBS util)
endif()
```

**Comment by tsl0922** [comment]
It's on main now(b31ac86a27e058c3b1c6d9cf0cf9f25d9ce9ce4f)
