### ISSUE TITLE
why I can't use esc ?

### ISSUE THREAD

**Issue by Ruest** [tsl0922/ttyd#882]
I use vim to edit file , but can not return normal mode by using Esc.
It seems like Esc was captured by browser.

Is there a solution?

**Comment by ciberado** [comment]
Check that no extension/addon on your browser is messing up with your keybinding. In my case, it was SakaKeys (https://addons.mozilla.org/en-US/firefox/addon/saka-key/) what was capturing ESC and I needed to add a rule to avoid it.
