### ISSUE TITLE
coredump when use ttyd to start a ipmitool command.

### ISSUE THREAD

**Issue by vincent-kuan** [tsl0922/ttyd#889]
**Describe the bug**
ttyd -i ip -p port -S -C -t titleFixed -a ipmitool **
**To Reproduce**
1. Go to protocol.c : 43  'if (json_object_object_get_ex(obj, "columns", &o)) *cols = (uint16_t)json_object_get_int(o); '
4. ![image](https://user-images.githubusercontent.com/56676539/155991623-629b3d05-9e09-4a30-8f17-e97cecee20d9.png)
5. segfault at c 

**Expected behavior**

**Screenshots**

**Environment:**
 - OS: [e.g. macOS 10.15.2]
 - Browser: [e.g. Chrome 79.0.3945.130]

**Additional context**

**Comment by tsl0922** [comment]
Check the latest release, which fixes some issues may related to it.
