### ISSUE TITLE
ERROR on binding fd 12 to port 7681 (-1 98)

### ISSUE THREAD

**Issue by 7980963** [tsl0922/ttyd#891]
Fri Feb 25 23:38:03 2022 daemon.notice procd: /etc/rc.d/S30ttyd: once 1
Fri Feb 25 23:38:03 2022 daemon.notice procd: /etc/rc.d/S45nfs: exportfs: could not open /var/lib/nfs/.etab.lock for locking: errno 2 (No such file or directory)
Fri Feb 25 23:38:03 2022 daemon.notice procd: /etc/rc.d/S45nfs: point 1
Fri Feb 25 23:38:03 2022 daemon.notice procd: /etc/rc.d/S45nfs: exportfs: could not open /var/lib/nfs/.etab.lock for locking: errno 2 (No such file or directory)
Fri Feb 25 23:38:03 2022 daemon.notice procd: /etc/rc.d/S45nfs: exportfs: can't lock /var/lib/nfs/etab for writing
Fri Feb 25 23:38:03 2022 daemon.notice procd: /etc/rc.d/S45nfs: point 2
Fri Feb 25 23:38:03 2022 daemon.notice procd: /etc/rc.d/S45nfs: point 3
Fri Feb 25 23:38:03 2022 daemon.notice ttyd[2960]: ttyd 1.6.3 (libwebsockets 4.1.6-20211107-376-g71d7ad88c)
Fri Feb 25 23:38:03 2022 daemon.notice ttyd[2960]: tty configuration:
Fri Feb 25 23:38:03 2022 daemon.notice ttyd[2960]:   start command: /bin/sh --login
Fri Feb 25 23:38:03 2022 daemon.notice ttyd[2960]:   close signal: SIGHUP (1)
Fri Feb 25 23:38:03 2022 daemon.notice ttyd[2960]:   terminal type: xterm-256color
Fri Feb 25 23:38:03 2022 daemon.notice ttyd[2960]:   once: true
Fri Feb 25 23:38:03 2022 daemon.notice ttyd[2960]: LWS: 4.1.6-20211107-376-g71d7ad88c, loglevel 7
Fri Feb 25 23:38:03 2022 daemon.notice ttyd[2960]: NET CLI SRV H1 H2 WS IPV6-off
Fri Feb 25 23:38:03 2022 daemon.notice ttyd[2960]:    /usr/lib/libwebsockets-evlib_uv.so
Fri Feb 25 23:38:03 2022 daemon.notice ttyd[2960]:  Using foreign event loop...
Fri Feb 25 23:38:03 2022 daemon.notice ttyd[2960]:  Listening on port: 7681

......................

Sat Feb 26 00:31:18 2022 daemon.notice ttyd[17111]: ttyd 1.6.3 (libwebsockets 4.1.6-20211107-376-g71d7ad88c)
Sat Feb 26 00:31:18 2022 daemon.notice ttyd[17111]: tty configuration:
Sat Feb 26 00:31:18 2022 daemon.notice ttyd[17111]:   start command: 127.0.0.1
Sat Feb 26 00:31:18 2022 daemon.notice ttyd[17111]:   close signal: SIGHUP (1)
Sat Feb 26 00:31:18 2022 daemon.notice ttyd[17111]:   terminal type: xterm-256color
Sat Feb 26 00:31:18 2022 daemon.notice ttyd[17111]: LWS: 4.1.6-20211107-376-g71d7ad88c, loglevel 7
Sat Feb 26 00:31:18 2022 daemon.notice ttyd[17111]: NET CLI SRV H1 H2 WS IPV6-off
Sat Feb 26 00:31:18 2022 daemon.notice ttyd[17111]:    /usr/lib/libwebsockets-evlib_uv.so
Sat Feb 26 00:31:18 2022 daemon.notice ttyd[17111]:  Using foreign event loop...
Sat Feb 26 00:31:18 2022 daemon.err ttyd[17111]: ERROR on binding fd 12 to port 7681 (-1 98)
Sat Feb 26 00:31:18 2022 daemon.err ttyd[17111]: init server failed
Sat Feb 26 00:31:18 2022 daemon.err ttyd[17111]: libwebsockets vhost creation failed

**Comment by tsl0922** [comment]
Should not be ttyd's issue, check https://github.com/warmcat/libwebsockets/issues/740
