### ISSUE TITLE
Screen becomes blank/garbled after some time with Chrome (only)

### ISSUE THREAD

**Issue by amsnek** [tsl0922/ttyd#900]
**Describe the bug**
After a somewhat random amount of time, the screen suddenly becomes "garbled" or sometimes seemingly "blank" (text can still be shown when highlighted with mouse). will provide screenshots on imgur for better understanding.
Reloading fixes the issue until it occurs again. Seems to be rendering related to chrome. No Errors in Chrome Console. 

**To Reproduce**
1) launch a ttyd  -p someport /bin/bash
2) connect with browser to http://host:port
3) wait a couple seconds/minutes / do some input after that time -> screen will "garble"

**Expected behavior**
no garble, works as expected in firefox/edge/etc ...

[**Screenshots**
https://imgur.com/a/OnMCAni

**Environment:**
 - OS:  Windows 10 21H2 (Build 19044.1526)
 - Browser: Chrome Version 98.0.4758.102

**Additional context**
doesnt happen with Firefox/Edge etc

**Comment by tsl0922** [comment]
Can't reproduce on my PC (windows 11 21H2 build 22000.778 Chrome 102.0.5005.63).

**Comment by jcubic** [comment]
@tsl0922 You can register for [Open Source support in BrowserStack](https://www.browserstack.com/open-source). I have an Open Source account and I use it to test against different browsers.

**Comment by amsnek** [comment]
i cant reproduce this issue either anymore, i suppose will close this bug until i can reproduce/it re-occurs
