### ISSUE TITLE
Auto run/start tmux without having to navigate via a web browser

### ISSUE THREAD

**Issue by kitos9112** [tsl0922/ttyd#903]
Hi,

I'd like to autorun a program within a tmux session that is wrapped up using `ttyd`, I'm struggling to get it kicked off without intervention until I open a web browser. I've skimmed through the repo issues but cannot find a response. Am I missing anything here?

```sh
start command: tmux -S /data/tmux.sock new -A -s myShell /bin/myProgram
```

**Comment by tsl0922** [comment]
ttyd is designed for browser, if you don't use a browser, why not use something else?

**Comment by kitos9112** [comment]
Hi @tsl0922! Thanks for your reply.

The use case of this tool suits perfectly my application. The only downside is resurrecting it whenever the application or server restarts/reboots. Why does it need user interaction via a Web browser to start?

I got the tool running in the container image, but I really want to kick off an autostart whenever kubelet (Kubernetes) restarts the pod/container. This way, I can allow an operator open a TTY to the process. Hope I make sense, happy to provide more information.

**Comment by tsl0922** [comment]
ttyd is not designed for this use case, maybe you can start your program with tmux first, then let ttyd run tmux attach to get access to the started session.
