### ISSUE TITLE
password is visible

### ISSUE THREAD

**Issue by uart-aplex** [tsl0922/ttyd#913]
Describe your problem or question here.
How to make the password input is invisible? Currently the password is visible when input.

**Comment by uart-aplex** [comment]
I found the problem, when I using USB keyboard through HID interface to input password, then the password input is invisible, but I am using the touch screen keyboard, when the on screen keyboard pass the key input to ttyd for password input, then the password is visible. Is there anyway to let this situation invisible for password input?

**Comment by tsl0922** [comment]
ttyd has no logic about password visibility, check your program.
