### ISSUE TITLE
compiling with libwebsockets 4.3.1 fails

### ISSUE THREAD

**Issue by Mindavi** [tsl0922/ttyd#918]
**Describe the bug**

Compiling with libwebsockets 4.3.1 fails.
Not sure if libwebsockets or this package is at fault, but I'm hoping you'd be able to shed some light on it.

**To Reproduce**
1. Apply the attached patch (updating libwebsockets to 4.3.1 in the cross-build script)
2. Run `env BUILD_TARGET=i686 ./scripts/cross-build.sh`
3. See build failure:

```shell
=== Building ttyd (i686-linux-musl)...
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 11.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /tmp/ttyd/cr/cross/bin/i686-linux-musl-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Git: /run/current-system/sw/bin/git (found version "2.35.1") 
-- Found LIBUV: /tmp/ttyd/cr/stage/i686-linux-musl/lib/libuv.a  
-- Found JSON-C: /tmp/ttyd/cr/stage/i686-linux-musl/lib/libjson-c.a  
-- Found ZLIB: /tmp/ttyd/cr/stage/i686-linux-musl/lib/libz.a (found version "1.2.12") 
CMake Error at /tmp/ttyd/cr/stage/i686-linux-musl/lib/cmake/libwebsockets/libwebsockets-config.cmake:35 (include):
  include could not find requested file:

    LwsCheckRequirements
Call Stack (most recent call first):
  CMakeLists.txt:54 (find_package)
```

```patch
diff --git a/scripts/cross-build.sh b/scripts/cross-build.sh
index 01e2a87..751ad56 100755
--- a/scripts/cross-build.sh
+++ b/scripts/cross-build.sh
@@ -14,7 +14,7 @@ ZLIB_VERSION="${ZLIB_VERSION:-1.2.12}"
 JSON_C_VERSION="${JSON_C_VERSION:-0.15}"
 MBEDTLS_VERSION="${MBEDTLS_VERSION:-2.16.8}"
 LIBUV_VERSION="${LIBUV_VERSION:-1.40.0}"
-LIBWEBSOCKETS_VERSION="${LIBWEBSOCKETS_VERSION:-4.2.1}"
+LIBWEBSOCKETS_VERSION="${LIBWEBSOCKETS_VERSION:-4.3.1}"
 
 build_zlib() {
     echo "=== Building zlib-${ZLIB_VERSION} (${TARGET})..."
```

**Expected behavior**

Build succeeds without cmake errors.

**Environment:**
 - OS: NixOS 22.05 Quokka
 - <s>Browser: [e.g. Chrome 79.0.3945.130]</s>

**Additional context**

I noticed this when updating libwebsockets in the nixpkgs package repository. It was working fine with 4.3.0, but broke with 4.3.1. See the PR to nixpkgs: https://github.com/NixOS/nixpkgs/pull/168304

**Comment by bbilas** [comment]
The same errors have been encountered in buildroot, see http://autobuild.buildroot.net/?reason=ttyd-1.6.3.

**Comment by tsl0922** [comment]
maybe an upstream issue, see also:

https://github.com/Homebrew/homebrew-core/pull/93354/files/fd529a79712d714d393cd85dc24f5cfb7c95625a#diff-7afcd4af638aa2e2d655a5d2844e83c4582c3848d514d0c92306135e463afb7d

**Comment by Mindavi** [comment]
Thanks, applying that patch fixes the build.
