### ISSUE TITLE
loongarch64-3C5000-version-ttyd

### ISSUE THREAD

**Issue by intionwun** [tsl0922/ttyd#919]
Describe your problem or question here.
CPU Arch: loongarch64
CPU: 3C5000
OS: Loongnix-Server-8.3
Support: ttyd.longarch64

**Comment by tsl0922** [comment]
It will be available when the cross toolchain for this arch is out.

or you can compile it on a longarch bard yourself, if you own a hardware.

**Comment by intionwun** [comment]
I have compiled it on a longarch64 machine，but there is a problem with the output file(ttyd)
Summary：
1、ttyd -p 14377 bash    #can input and run bash environment
2、ttyd -p 14377 login    #cannot input anything（black screen lock）,No account and password input prompt

Compilation process：

wget https://codeload.github.com/warmcat/libwebsockets/zip/refs/heads/v3.2-stable
unzip 3.2-stable.zip
cd libwebsockets-3.2-stable
mkdir build
cd build
cmake .. -DLWS_WITH_LIBUV=ON -DBUILD_SHARED_LIBS=OFF
make
make install

dnf install json-c-devel libwebsockets-devel libuv-devel zlib-devel -y
git clone https://github.com/tsl0922/ttyd.git
cd ttyd
mkdir build
cd build
cmake .. -DBUILD_SHARED_LIBS=OFF
make
make install

@tsl0922

**Comment by tsl0922** [comment]
`login` command is platform specific, it's not ttyd's issue if `bash` works.
