### ISSUE TITLE
Flashing Terminal With Copy-On-Select with less in tmux

### ISSUE THREAD

**Issue by r10r** [tsl0922/ttyd#938]
**Describe the bug**

With  #914 I've enabled the options key for copy-on-select on macOS.
We did run into certain situations where using copy-on-select may render the terminal unusable.

**To Reproduce**

1. Start a tmux session in ttyd `tmux`
1. Open output with less e.g `echo  'hello world' | less`
2. Double click (left mouse button) a word.

Selecting output within the pager less with a double-click (left mouse button) renders the terminal unusable.
Curiously the pager `more`  seems not to be affected.
I've used `strace` and attached to the less process which seems to loop constantly on the input.

**Environment:**
 - OS: [e.g. macOS 12.4]
 - Browser: [e.g. Chrome  102.0.5005.61]

**Solution**

Disabling the xterm.js option `altClickMovesCursor` seems to fix this issue.

* [ ] Check what the option **altClickMovesCursor** is good for at all.
* [ ] Check if it can be disabled safely.

I can send a pull request.

**Comment by tsl0922** [comment]
I've seen comments on your commit saying that it may break something too.

I'm going to revert this commit, you can always re-enable it with [Client Options](https://github.com/tsl0922/ttyd/wiki/Client-Options) without changing ttyd's code.

**Comment by r10r** [comment]
You're right. Thanks for the hint - I'll  use the client options then.
