### ISSUE TITLE
Programmatically reading terminal outputs

### ISSUE THREAD

**Issue by deka108** [tsl0922/ttyd#943]
Hi,

Would it be possible to read the output of a command that was executed on ttyd programmatically? Based on [this thread](https://github.com/tsl0922/ttyd/issues/620), we were able to run commands by simulating keyboard events on the textarea or using `window.term`. But I was wondering if there is a way to read the command output programmatically either using DOM or the terminal object.

Thanks!

**Comment by deka108** [comment]
Ah okay, I was able to get around this by programmatically selecting contents on the terminal. Thanks!

**Comment by tsl0922** [comment]
> But I was wondering if there is a way to read the command output programmatically either using DOM or the terminal object

the default renderer is webgl since 1.3, you can change it via command-line args:

```bash
ttyd -t rendererType=dom bash
```

You can access the xterm [Terminal](https://xtermjs.org/docs/api/terminal/classes/terminal/) object via `window.term`. btw, I'm not going to provide such APIs  in ttyd, check xterm's API.
