### ISSUE TITLE
windows build Libwebsocketss failed, how to solve this problem?

### ISSUE THREAD

**Issue by darkSystemCode** [tsl0922/ttyd#945]
Starting build()...
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

System is unknown to cmake, create:
Platform/MINGW64_NT-10.0-19043 to use this system, please post your config file on discourse.cmake.org so it can be added to cmake
Your CMakeCache.txt file was copied to CopyOfCMakeCache.txt. Please post that file on discourse.cmake.org.
-- CMAKE_TOOLCHAIN_FILE=''
-- Could NOT find Git (missing: GIT_EXECUTABLE)
zlib include dirs: /mingw64/include
zlib libraries: /mingw64/lib/libz.a
Compiling with SSL support
OpenSSL include dir: /mingw64/include
OpenSSL libraries: /mingw64/lib/libssl.a;/mingw64/lib/libcrypto.a
Searching for OpenSSL executable and dlls
OpenSSL executable: /usr/bin/openssl.exe
 GENCERTS = 1
Generating SSL Certificates for the test-server...
Generating a RSA private key
............+++++
...................+++++
writing new private key to '/d/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/build-x86_64/libwebsockets-test-server.key.pem'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:State or Province Name (full name) [Some-State]:Locality Name (eg, city) []:Organization Name (eg, company) [Internet Widgits Pty Ltd]:Organizational Unit Name (eg, section) []:Common Name (e.g. server FQDN or YOUR name) []:Email Address []:SUCCESSFULLY generated SSL certificate
---------------------------------------------------------------------
  Settings:  (For more help do cmake -LH <srcpath>)
---------------------------------------------------------------------
 LWS_WITH_STATIC = ON
 LWS_WITH_SHARED = ON
 LWS_WITH_SSL = ON (SSL Support)
 LWS_SSL_CLIENT_USE_OS_CA_CERTS = 1
 LWS_WITH_WOLFSSL = OFF (wolfSSL/CyaSSL replacement for OpenSSL)
 LWS_WITH_MBEDTLS = OFF (mbedTLS replacement for OpenSSL)
 LWS_WITHOUT_BUILTIN_SHA1 = OFF
 LWS_WITHOUT_BUILTIN_GETIFADDRS = OFF
 LWS_WITHOUT_CLIENT = OFF
 LWS_WITHOUT_SERVER = OFF
 LWS_LINK_TESTAPPS_DYNAMIC = OFF
 LWS_WITHOUT_TESTAPPS = ON
 LWS_WITHOUT_TEST_SERVER = OFF
 LWS_WITHOUT_TEST_SERVER_EXTPOLL = OFF
 LWS_WITHOUT_TEST_PING = OFF
 LWS_WITHOUT_TEST_ECHO = OFF
 LWS_WITHOUT_TEST_CLIENT = OFF
 LWS_WITHOUT_TEST_FRAGGLE = OFF
 LWS_WITHOUT_EXTENSIONS = OFF
 LWS_WITH_LATENCY = OFF
 LWS_WITHOUT_DAEMONIZE = ON
 LWS_WITH_LIBEV = OFF
 LWS_WITH_LIBUV = OFF
 LWS_WITH_LIBEVENT = OFF
 LWS_IPV6 = OFF
 LWS_UNIX_SOCK = OFF
 LWS_WITH_HTTP2 = OFF
 LWS_SSL_SERVER_WITH_ECDH_CERT = OFF
 LWS_MAX_SMP = 1
 LWS_WITH_CGI = OFF
 LWS_HAVE_OPENSSL_ECDH_H = 1
 LWS_HAVE_SSL_CTX_set1_param =
 LWS_HAVE_RSA_SET0_KEY =
 LWS_WITH_HTTP_PROXY = OFF
 LIBHUBBUB_LIBRARIES =
 PLUGINS =
 LWS_WITH_ACCESS_LOG = OFF
 LWS_WITH_SERVER_STATUS = OFF
 LWS_WITH_LEJP = OFF
 LWS_WITH_LEJP_CONF = OFF
 LWS_WITH_SMTP = OFF
 LWS_WITH_GENERIC_SESSIONS = OFF
 LWS_STATIC_PIC = OFF
 LWS_WITH_RANGES = ON
 LWS_PLAT_OPTEE = OFF
 LWS_WITH_ESP32 = OFF
 LWS_WITH_ZIP_FOPS = ON
 LWS_AVOID_SIGPIPE_IGN = OFF
 LWS_WITH_STATS = OFF
 LWS_WITH_SOCKS5 = OFF
 LWS_HAVE_SYS_CAPABILITY_H =
 LWS_HAVE_LIBCAP =
 LWS_WITH_PEER_LIMITS = OFF
 LWS_HAVE_ATOLL = 1
 LWS_HAVE__ATOI64 = 1
 LWS_HAVE_STAT32I64 =
 LWS_HAS_INTPTR_T = 1
---------------------------------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /d/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/build-x86_64
[  1%] Building C object CMakeFiles/websockets.dir/lib/misc/base64-decode.c.obj
[  5%] Building C object CMakeFiles/websockets_shared.dir/lib/handshake.c.obj
[  5%] Building C object CMakeFiles/websockets_shared.dir/lib/misc/base64-decode.c.obj
[  7%] Building C object CMakeFiles/websockets.dir/lib/handshake.c.obj
[  8%] Building C object CMakeFiles/websockets_shared.dir/lib/libwebsockets.c.obj
[ 14%] Building C object CMakeFiles/websockets_shared.dir/lib/service.c.obj
[ 14%] Building C object CMakeFiles/websockets.dir/lib/libwebsockets.c.obj
[ 14%] Building C object CMakeFiles/websockets_shared.dir/lib/pollfd.c.obj
[ 16%] Building C object CMakeFiles/websockets.dir/lib/service.c.obj
In file included from D:/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/libwebsockets-2.4.2/lib/handshake.c:22:
D:/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/libwebsockets-2.4.2/lib/private-libwebsockets.h:326:10: fatal error: gettimeofday.h: No such file or directory
  326 | #include <gettimeofday.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
In file included from D:/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/libwebsockets-2.4.2/lib/misc/base64-decode.c:43:
D:/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/libwebsockets-2.4.2/lib/private-libwebsockets.h:326:10: fatal error: gettimeofday.h: No such file or directory
  326 | #include <gettimeofday.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
In file included from D:/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/libwebsockets-2.4.2/lib/service.c:22:
D:/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/libwebsockets-2.4.2/lib/private-libwebsockets.h:326:10: fatal error: gettimeofday.h: No such file or directory
  326 | #include <gettimeofday.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
In file included from D:/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/libwebsockets-2.4.2/lib/libwebsockets.c:22:
D:/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/libwebsockets-2.4.2/lib/private-libwebsockets.h:326:10: fatal error: gettimeofday.h: No such file or directory
  326 | #include <gettimeofday.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/websockets_shared.dir/build.make:118: CMakeFiles/websockets_shared.dir/lib/service.c.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from D:/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/libwebsockets-2.4.2/lib/misc/base64-decode.c:43:
D:/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/libwebsockets-2.4.2/lib/private-libwebsockets.h:326:10: fatal error: gettimeofday.h: No such file or directory
  326 | #include <gettimeofday.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/websockets_shared.dir/build.make:90: CMakeFiles/websockets_shared.dir/lib/handshake.c.obj] Error 1
make[2]: *** [CMakeFiles/websockets.dir/build.make:104: CMakeFiles/websockets.dir/lib/libwebsockets.c.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from D:/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/libwebsockets-2.4.2/lib/handshake.c:22:
D:/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/libwebsockets-2.4.2/lib/private-libwebsockets.h:326:10: fatal error: gettimeofday.h: No such file or directory
  326 | #include <gettimeofday.h>
      |          ^~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/websockets.dir/build.make:76: CMakeFiles/websockets.dir/lib/misc/base64-decode.c.obj] Error 1
compilation terminated.
In file included from D:/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/libwebsockets-2.4.2/lib/pollfd.c:22:
D:/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/libwebsockets-2.4.2/lib/private-libwebsockets.h:326:10: fatal error: gettimeofday.h: No such file or directory
  326 | #include <gettimeofday.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/websockets.dir/build.make:90: CMakeFiles/websockets.dir/lib/handshake.c.obj] Error 1
In file included from D:/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/libwebsockets-2.4.2/lib/service.c:22:
D:/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/libwebsockets-2.4.2/lib/private-libwebsockets.h:326:10: fatal error: gettimeofday.h: No such file or directory
  326 | #include <gettimeofday.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/websockets_shared.dir/build.make:76: CMakeFiles/websockets_shared.dir/lib/misc/base64-decode.c.obj] Error 1
make[2]: *** [CMakeFiles/websockets_shared.dir/build.make:132: CMakeFiles/websockets_shared.dir/lib/pollfd.c.obj] Error 1
In file included from D:/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/libwebsockets-2.4.2/lib/libwebsockets.c:22:
D:/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/libwebsockets-2.4.2/lib/private-libwebsockets.h:326:10: fatal error: gettimeofday.h: No such file or directory
  326 | #include <gettimeofday.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
[ 17%] Building C object CMakeFiles/websockets.dir/lib/pollfd.c.obj
make[2]: *** [CMakeFiles/websockets_shared.dir/build.make:104: CMakeFiles/websockets_shared.dir/lib/libwebsockets.c.obj] Error 1
make[2]: *** [CMakeFiles/websockets.dir/build.make:118: CMakeFiles/websockets.dir/lib/service.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:112: CMakeFiles/websockets_shared.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from D:/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/libwebsockets-2.4.2/lib/pollfd.c:22:
D:/projects/ttyd-1.5.2/ttyd-1.5.2/msys2/libwebsockets/src/libwebsockets-2.4.2/lib/private-libwebsockets.h:326:10: fatal error: gettimeofday.h: No such file or directory
  326 | #include <gettimeofday.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/websockets.dir/build.make:132: CMakeFiles/websockets.dir/lib/pollfd.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:86: CMakeFiles/websockets.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by tsl0922** [comment]
upgrade libwebsockets, check: https://github.com/tsl0922/ttyd/runs/7182265903?check_suite_focus=true
