### ISSUE TITLE
Is --ping-interval/-P working as intended in official releases of v1.6.3?

### ISSUE THREAD

**Issue by a-forsythe** [tsl0922/ttyd#949]
I'm running ttyd by downloading the latest Linux x64 binary and running it from a Docker container with port 7681 exposed:

```bash
docker run --rm -it -p 7681:7681 ubuntu
apt-get update && apt-get -y install curl && rm -rf /var/lib/apt/lists/*
curl -L https://github.com/tsl0922/ttyd/releases/download/1.6.3/ttyd.x86_64 -o /usr/bin/ttyd && chmod +x /usr/bin/ttyd
ttyd --ping-interval 5 bash
```

If I load up http://localhost:7681, I have a bash shell and everything works normally. However, the `--ping-interval` option doesn't seem to have any effect.

If I open my browser's Network tab and examine the `/ws` connection, I can see the messages being sent in each direction whenever I send keyboard input, or whenever anything is printed to the terminal. However, given that I'm using `--ping-interval 5`, I would expect that after 5 seconds of inactivity, the ttyd server would send some kind of "ping" message across this connection. In other words, I would expect to see a new message appear in the "Messages" list for this websocket connection, but that never happens.

If I run `ttyd -h` I get version `1.6.3-3b174da`, and the option is listed as:

```
-P, --ping-interval     Websocket ping interval(sec) (default: 300)
```

...which would seem to indicate that this official binary was built with the proper libwebsockets version.

Am I misunderstanding what `--ping-interval/-P` is supposed to do? My understanding is that it's a heartbeat mechanism intended to keep the connection alive to get around timeouts that may be imposed by proxies between the client and the server - i.e. after _n_ seconds of inactivity, the server will send a 'ping' message, to which the client responds with a 'pong'. Is this not what the option does?

I get the same behavior when running ttyd 1.6.3 natively in Mac OS (installed via homebrew).

**Comment by dmartin** [comment]
I had the same concern at one point, but it does work. It sends WebSocket [ping control frames](https://www.rfc-editor.org/rfc/rfc6455#section-5.5.2). All major browser web inspectors seem to only display WebSocket data frame traffic. However, if you capture the traffic using something like Wireshark you'll see the ping / pong frames.
