### ISSUE TITLE
Executing a command doesn't work with zsh

### ISSUE THREAD

**Issue by wuestkamp** [tsl0922/ttyd#952]
Executing a command doesn't work with `zsh`.
In `zsh` a new line is added to the command line, but it's not executed. A manual press of Enter is necessary to execute.

## Details
- Browser and browser version: Chrome 103
- OS version: Ubuntu 20.04
- xterm.js version: 4.19.0 (what is shipped with ttyd 1.6.3)

### Steps to reproduce
Use `ttyd bash` vs `ttyd zsh`
Executing a command seems to only work with bash, not zsh:

```
window.term.paste('ls\n'); # bash only
window.term.paste('ls\r\n'); # bash only
window.term.paste('ls\r'); # bash only
window.term.write('ls\n'); # neither works
window.term.write('ls\r\n'); # neither works
window.term.write('ls\r'); # neither works
```

Any idea how this can be achieved with any shell?

**Comment by tsl0922** [comment]
Try this: https://github.com/tsl0922/ttyd/issues/620#issuecomment-789693717

Or if you think it is a bug, report it to the upstream ([xtermjs/xterm.js](https://github.com/xtermjs/xterm.js))
