### ISSUE TITLE
debian9编译安装无法直接用root登录

### ISSUE THREAD

**Issue by a1093773736** [tsl0922/ttyd#97]
您好，我系统debian9编译安装了你的ttyd，第一次登录可以root登录，但是机器重启后就不能直接root登录了，得先用普通用户登录再切换。
启动命令 screen -dmS ttyd ttyd -p 4200 login

提示Login incorrect.

**Comment by tsl0922** [comment]
用 root 启动 ttyd 试试。

**Comment by tsl0922** [comment]
这个问题应该和 ttyd 无关，ttyd 只管转发 pty 到网页，你去查下 login 相关的文档。

**Comment by a1093773736** [comment]
一般您是怎么后台运行ttyd的？这个screen不稳定的，有时候可以直接root登录有时候不行。
