### ISSUE TITLE
I want to ask about ttyd support for SSL

### ISSUE THREAD

**Issue by bcseputetto** [tsl0922/ttyd#972]
(Software translation to English)
When I turn on SSL support for ttyd
How can I make it automatically redirect to HTTPS link like opening HSTS
I'm using it on openwrt
![ttyd_config](https://user-images.githubusercontent.com/29139573/187035340-b54ebf3e-234e-4569-925e-22d39a630332.png)
It must be manually added with HTTPS before the URL before it can be accessed normally

**Comment by tsl0922** [comment]
none ssl connection on ssl port was not supported, I've added support at the latest main branch.
