### ISSUE TITLE
SSH terminates when running sz/rz utils

### ISSUE THREAD

**Issue by santosh0705** [tsl0922/ttyd#98]
When running `sz/rz` utility many times the ssh session get terminated. Debugging message as below:

```
[2018/04/10 10:14:45:3267] NOTICE: sending SIGHUP (1) to process 19486
[2018/04/10 10:14:45:3468] NOTICE: process exited with code 33024, pid: 19486
```

Some times its also happening when skipping the file download. Don't know it is problem of `ttyd` or the `lrzsz` or `zmodemjs`.

I'm testing it on Debian Jessie and client running Firefox on Mac.

**Comment by tsl0922** [comment]
This maybe a known issue to me, I've tried to fix it by reducing the buffer size which seems to work mostly, but not all, for example: large files.

**Comment by tsl0922** [comment]
Should be fixed on master now.
