### ISSUE TITLE
No cancel option for file upload

### ISSUE THREAD

**Issue by santosh0705** [tsl0922/ttyd#99]
There is no option to skip file uploading. When you run `rz` command in terminal it pop-up file upload modal box having no option to cancel it. It remain open until you select a file and upload it. Also while upload in progress there is no option to cancel it. Cancellation option should be there in case someone changed his/her mind after running `rz` command in the terminal.

**Comment by tsl0922** [comment]
Yes, because of lacking api from [zmodemjs](https://github.com/FGasper/zmodemjs).

**Comment by santosh0705** [comment]
At least there is an option (workaround) to cancel the file upload. We can start zmodem session only if the user select the file or he/she have option to cancel the session.

**Comment by tsl0922** [comment]
Nope, zmodem session started when rz/sz command is run, not file selection.

**Comment by santosh0705** [comment]
Let me work on this :)

**Comment by santosh0705** [comment]
This I have done by calling `send_files` with empty files object.

**Comment by FGasper** [comment]
@tsl0922 zmodem.js DOES support cancellation of a receive or send session.

**Comment by tsl0922** [comment]
@tianyuanhao the cancel option of zmodem is already [supported](https://github.com/tsl0922/ttyd/blob/master/html/src/components/zmodem/index.tsx#L95), just press <kbd>Ctrl</kbd> <kbd>C</kbd>.
